"use client";

import { useState } from "react";
import type { FormEvent } from "react";
import type {Locale} from "@/lib/i18n";

type RatePlan={id:string;name:string;code:string;roomName:string};
type Promotion={id:string;name:string;code:string;discountPercent:number;bookingStartsAt:string;bookingEndsAt:string;stayStartsOn:string;stayEndsOn:string;minimumNights:number;status:string;ratePlans:RatePlan[]};

export default function PromotionManager({hotelId,ratePlans,initialPromotions,locale}:{hotelId:string;ratePlans:RatePlan[];initialPromotions:Promotion[];locale:Locale}){
  const ar=locale==="ar";
  const [promotions,setPromotions]=useState(initialPromotions);const [message,setMessage]=useState<string|null>(null);const [busy,setBusy]=useState(false);
  async function createPromotion(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage(null);const formElement=event.currentTarget;const form=new FormData(formElement);try{const ratePlanIds=form.getAll("ratePlanIds").map(String);const created=await api<any>(`/api/v1/hotels/${hotelId}/promotions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:String(form.get("name")),code:String(form.get("code")).toUpperCase(),discountPercent:Number(form.get("discountPercent")),bookingStartsAt:new Date(String(form.get("bookingStartsAt"))).toISOString(),bookingEndsAt:new Date(String(form.get("bookingEndsAt"))).toISOString(),stayStartsOn:String(form.get("stayStartsOn")),stayEndsOn:String(form.get("stayEndsOn")),minimumNights:Number(form.get("minimumNights")),ratePlanIds})});setPromotions((items)=>[{id:created.id,name:created.name,code:created.code,discountPercent:Number(created.discountPercent),bookingStartsAt:created.bookingStartsAt,bookingEndsAt:created.bookingEndsAt,stayStartsOn:String(created.stayStartsOn).slice(0,10),stayEndsOn:String(created.stayEndsOn).slice(0,10),minimumNights:created.minimumNights,status:created.status,ratePlans:ratePlans.filter((plan)=>ratePlanIds.includes(plan.id))},...items]);formElement.reset();setMessage("Promotion created as Draft.");}catch(error){setMessage(error instanceof Error?error.message:"Unable to create promotion");}finally{setBusy(false);}}
  async function changeStatus(id:string,status:string){setBusy(true);setMessage(null);try{await api(`/api/v1/hotels/${hotelId}/promotions/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status})});setPromotions((items)=>items.map((item)=>item.id===id?{...item,status}:item));}catch(error){setMessage(error instanceof Error?error.message:"Unable to change promotion");}finally{setBusy(false);}}
  return <div className="grid2"><section className="panel"><span className="eyebrow">{ar?"إنشاء عرض":"Create deal"}</span><h2>{ar?"عرض جديد":"New promotion"}</h2><form className="stackForm" onSubmit={createPromotion}><label>{ar?"الاسم":"Name"}<input name="name" required maxLength={120}/></label><label>{ar?"الرمز":"Code"}<input name="code" required maxLength={40} placeholder="SUMMER10"/></label><label>{ar?"الخصم %":"Discount %"}<input name="discountPercent" type="number" min="0.01" max="80" step="0.01" required/></label><div className="formGrid"><label>{ar?"بداية الحجز":"Booking starts"}<input name="bookingStartsAt" type="datetime-local" required/></label><label>{ar?"نهاية الحجز":"Booking ends"}<input name="bookingEndsAt" type="datetime-local" required/></label><label>{ar?"بداية الإقامة":"Stay starts"}<input name="stayStartsOn" type="date" required/></label><label>{ar?"نهاية الإقامة":"Stay ends"}<input name="stayEndsOn" type="date" required/></label></div><label>{ar?"الحد الأدنى لليالي":"Minimum nights"}<input name="minimumNights" type="number" min="1" max="60" defaultValue="1" required/></label><div><strong>{ar?"خطط الأسعار":"Rate plans"}</strong>{ratePlans.map((plan)=><label className="inlineCheck" key={plan.id}><input type="checkbox" name="ratePlanIds" value={plan.id}/> {plan.roomName} · {plan.name}</label>)}</div><button className="primaryButton" disabled={busy||ratePlans.length===0}>{ar?"إنشاء العرض":"Create promotion"}</button></form>{message&&<div className="setupMessage">{message}</div>}</section><section className="panel"><span className="eyebrow">{ar?"العروض":"Deals"}</span><h2>{ar?"دورة حياة العرض":"Promotion lifecycle"}</h2><div className="stackForm">{promotions.length===0?<p className="muted">{ar?"لا توجد عروض بعد.":"No promotions yet."}</p>:promotions.map((promotion)=><article className="alertCard" key={promotion.id}><div style={{width:"100%"}}><div className="sectionHeading"><div><strong>{promotion.name} · {promotion.discountPercent}%</strong><p className="muted">{promotion.code} · {promotion.minimumNights}+ {ar?"ليلة":"night(s)"}</p></div><select value={promotion.status} disabled={busy} onChange={(event)=>void changeStatus(promotion.id,event.target.value)}><option value="DRAFT">{ar?"مسودة":"Draft"}</option><option value="ACTIVE">{ar?"نشط":"Active"}</option><option value="PAUSED">{ar?"متوقف مؤقتًا":"Paused"}</option><option value="ARCHIVED">{ar?"مؤرشف":"Archived"}</option></select></div><p className="muted">{ar?"الإقامة":"Stay"} {promotion.stayStartsOn} → {promotion.stayEndsOn}</p><div className="tags">{promotion.ratePlans.map((plan)=><span className="tag" key={plan.id}>{plan.roomName} · {plan.name}</span>)}</div></div></article>)}</div></section></div>;
}
async function api<T=unknown>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{...init,cache:"no-store"});const body=await response.json();if(!response.ok||body.error)throw new Error(body.error?.message||"Request failed");return body.data as T;}
