"use client";

import { useState } from "react";
import type { FormEvent } from "react";

type Review={id:string;bookingReference:string;guestName:string;stayCompleted:string;overall:number;cleanliness:number;staff:number;location:number;facilities:number;comfort:number;value:number;title:string|null;comment:string;status:string;hotelReply:string|null;repliedAt:string|null;createdAt:string};

export default function ReviewManager({hotelId,initialReviews}:{hotelId:string;initialReviews:Review[]}){
  const [reviews,setReviews]=useState(initialReviews);const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState<string|null>(null);
  async function reply(event:FormEvent<HTMLFormElement>,reviewId:string){event.preventDefault();const formElement=event.currentTarget;const form=new FormData(formElement);setBusy(reviewId);setMessage(null);try{const text=String(form.get("reply"));await api(`/api/v1/hotels/${hotelId}/reviews/${reviewId}/reply`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({reply:text})});setReviews((items)=>items.map((item)=>item.id===reviewId?{...item,hotelReply:text,repliedAt:new Date().toISOString()}:item));setMessage("Hotel response published.");}catch(error){setMessage(error instanceof Error?error.message:"Unable to reply");}finally{setBusy(null);}}
  const average=reviews.length?reviews.reduce((sum,item)=>sum+item.overall,0)/reviews.length:null;
  return <><div className="kpiGrid"><div className="kpi"><span>Verified reviews</span><strong>{reviews.length}</strong></div><div className="kpi"><span>Average</span><strong>{average===null?"—":`${average.toFixed(1)}/10`}</strong></div><div className="kpi"><span>Awaiting response</span><strong>{reviews.filter((item)=>!item.hotelReply).length}</strong></div></div>{message&&<div className="setupMessage" style={{margin:"20px 0"}}>{message}</div>}<div className="grid2" style={{marginTop:24}}>{reviews.length===0?<div className="panel"><h3>No verified reviews yet</h3><p className="muted">Reviews appear only after a completed booking.</p></div>:reviews.map((review)=><article className="panel" key={review.id}><span className="eyebrow">{review.bookingReference} · verified stay</span><h2>{review.overall}/10 · {review.guestName}</h2><p className="muted">Stay completed {review.stayCompleted}</p>{review.title&&<h3>{review.title}</h3>}<p>{review.comment}</p><div className="tags"><span className="tag">Cleanliness {review.cleanliness}</span><span className="tag">Staff {review.staff}</span><span className="tag">Location {review.location}</span><span className="tag">Comfort {review.comfort}</span><span className="tag">Value {review.value}</span></div>{review.hotelReply?<div className="alertCard" style={{marginTop:16}}><div><strong>Your response</strong><p>{review.hotelReply}</p></div></div>:<form className="stackForm" onSubmit={(event)=>reply(event,review.id)} style={{marginTop:16}}><textarea name="reply" rows={3} minLength={2} maxLength={3000} required placeholder="Public hotel response"/><button className="secondaryButton" disabled={busy===review.id}>Publish response</button></form>}</article>)}</div></>;
}
async function api<T=unknown>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{...init,cache:"no-store"});const body=await response.json();if(!response.ok||body.error)throw new Error(body.error?.message||"Request failed");return body.data as T;}
