"use client";

import {useState} from "react";
import type {FormEvent} from "react";
import type {Locale} from "@/lib/i18n";
import {portalDictionary} from "@/lib/portal-i18n";

type Review={id:string;bookingReference:string;guestName:string;stayCompleted:string;overall:number;cleanliness:number;staff:number;location:number;facilities:number;comfort:number;value:number;title:string|null;comment:string;status:string;hotelReply:string|null;repliedAt:string|null;createdAt:string};

export default function ReviewManager({hotelId,initialReviews,locale}:{hotelId:string;initialReviews:Review[];locale:Locale}){
  const [reviews,setReviews]=useState(initialReviews);const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState<string|null>(null);const [editing,setEditing]=useState<string|null>(null);const copy=portalDictionary(locale).partner;
  async function reply(event:FormEvent<HTMLFormElement>,reviewId:string){event.preventDefault();const formElement=event.currentTarget;const form=new FormData(formElement);const review=reviews.find((item)=>item.id===reviewId);setBusy(reviewId);setMessage(null);try{const text=String(form.get("reply"));await api(`/api/v1/hotels/${hotelId}/reviews/${reviewId}/reply`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({reply:text})});setReviews((items)=>items.map((item)=>item.id===reviewId?{...item,hotelReply:text,repliedAt:new Date().toISOString()}:item));setEditing(null);setMessage(review?.hotelReply?copy.responseUpdated:copy.responsePublished);}catch(error){setMessage(error instanceof Error?error.message:(locale==="ar"?"تعذر حفظ الرد":"Unable to save response"));}finally{setBusy(null);}}
  const average=reviews.length?reviews.reduce((sum,item)=>sum+item.overall,0)/reviews.length:null;
  return <><div className="kpiGrid"><div className="kpi"><span>{copy.verifiedReviews}</span><strong>{reviews.length}</strong></div><div className="kpi"><span>{copy.average}</span><strong>{average===null?"—":`${average.toFixed(1)}/10`}</strong></div><div className="kpi"><span>{copy.awaitingResponse}</span><strong>{reviews.filter((item)=>!item.hotelReply).length}</strong></div></div>{message&&<div className="setupMessage" style={{margin:"20px 0"}}>{message}</div>}<div className="grid2" style={{marginTop:24}}>{reviews.length===0?<div className="panel"><h3>{copy.noReviews}</h3><p className="muted">{copy.noReviewsBody}</p></div>:reviews.map((review)=><article className="panel" key={review.id}><span className="eyebrow">{review.bookingReference} · {copy.verifiedStay}</span><h2>{review.overall}/10 · {review.guestName}</h2><p className="muted">{copy.stayCompleted} {review.stayCompleted}</p>{review.title&&<h3>{review.title}</h3>}<p>{review.comment}</p><div className="tags"><span className="tag">{copy.cleanliness} {review.cleanliness}</span><span className="tag">{copy.staff} {review.staff}</span><span className="tag">{copy.location} {review.location}</span><span className="tag">{copy.comfort} {review.comfort}</span><span className="tag">{copy.value} {review.value}</span></div>{review.hotelReply&&editing!==review.id?<div className="alertCard" style={{marginTop:16}}><div style={{width:"100%"}}><strong>{copy.yourResponse}</strong><p>{review.hotelReply}</p><button type="button" className="secondaryButton" onClick={()=>setEditing(review.id)}>{copy.editResponse}</button></div></div>:<form className="stackForm" onSubmit={(event)=>reply(event,review.id)} style={{marginTop:16}}><textarea name="reply" rows={4} minLength={2} maxLength={3000} required defaultValue={review.hotelReply??""} placeholder={copy.publicResponse}/><div style={{display:"flex",gap:8}}><button className="secondaryButton" disabled={busy===review.id}>{review.hotelReply?copy.updateResponse:copy.publishResponse}</button>{review.hotelReply&&<button type="button" className="secondaryButton" onClick={()=>setEditing(null)}>{portalDictionary(locale).common.cancel}</button>}</div></form>}</article>)}</div></>;
}
async function api<T=unknown>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{...init,cache:"no-store"});const body=await response.json();if(!response.ok||body.error)throw new Error(body.error?.message||"Request failed");return body.data as T;}
