"use client";

import { useState } from "react";
import type { FormEvent } from "react";
import type {Locale} from "@/lib/i18n";

type Conversation={id:string;booking:{id:string;reference:string;guestName:string;arrival:string;departure:string;status:string};latestMessage:{body:string;senderKind:string;createdAt:string}|null;unreadCount:number;updatedAt:string};
type Message={id:string;senderKind:"GUEST"|"HOTEL";body:string;createdAt:string;sender?:{displayName:string}|null};

export default function MessageInbox({hotelId,initialConversations,locale}:{hotelId:string;initialConversations:Conversation[];locale:Locale}){
  const ar=locale==="ar";
  const [conversations,setConversations]=useState(initialConversations);const [selected,setSelected]=useState<string|null>(initialConversations[0]?.booking.id??null);const [messages,setMessages]=useState<Message[]>([]);const [loaded,setLoaded]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);
  async function openThread(bookingId:string){setSelected(bookingId);setBusy(true);setError(null);try{const next=await api<Message[]>(`/api/v1/hotels/${hotelId}/messages/${bookingId}`);setMessages(next);setLoaded(bookingId);setConversations((items)=>items.map((item)=>item.booking.id===bookingId?{...item,unreadCount:0}:item));}catch(cause){setError(cause instanceof Error?cause.message:"Unable to load conversation");}finally{setBusy(false);}}
  async function send(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const formElement=event.currentTarget;const form=new FormData(formElement);setBusy(true);setError(null);try{const created=await api<Message>(`/api/v1/hotels/${hotelId}/messages/${selected}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({body:String(form.get("body"))})});setMessages((items)=>[...items,created]);formElement.reset();}catch(cause){setError(cause instanceof Error?cause.message:"Unable to send message");}finally{setBusy(false);}}
  const active=conversations.find((item)=>item.booking.id===selected)??null;
  return <div className="grid2"><section className="panel"><span className="eyebrow">{ar?"الوارد":"Inbox"}</span><h2>{ar?"محادثات الحجوزات":"Booking conversations"}</h2><div className="stackForm">{conversations.length===0?<p className="muted">{ar?"لا توجد رسائل حجوزات بعد.":"No booking messages yet."}</p>:conversations.map((item)=><button key={item.id} className="alertCard" style={{textAlign:ar?"right":"left",cursor:"pointer"}} onClick={()=>void openThread(item.booking.id)}><div style={{width:"100%"}}><div className="sectionHeading"><strong>{item.booking.guestName} · {item.booking.reference}</strong>{item.unreadCount>0&&<span className="tag">{item.unreadCount} {ar?"جديد":"new"}</span>}</div><p className="muted">{item.booking.arrival} → {item.booking.departure}</p><p>{item.latestMessage?.body??(ar?"تم فتح المحادثة":"Conversation opened")}</p></div></button>)}</div></section><section className="panel"><span className="eyebrow">{ar?"المحادثة":"Conversation"}</span><h2>{active?`${active.booking.guestName} · ${active.booking.reference}`:(ar?"اختر حجزًا":"Select a booking")}</h2>{selected&&loaded!==selected?<button className="secondaryButton" disabled={busy} onClick={()=>void openThread(selected)}>{ar?"تحميل المحادثة":"Load conversation"}</button>:null}<div className="stackForm" style={{maxHeight:420,overflow:"auto",marginTop:14}}>{messages.map((item)=><div className="alertCard" key={item.id}><div><strong>{item.senderKind==="HOTEL"?(item.sender?.displayName??(ar?"الفندق":"Hotel")):(ar?"الضيف":"Guest")}</strong><p>{item.body}</p><small className="muted">{new Date(item.createdAt).toLocaleString(ar?"ar-JO":"en-GB")}</small></div></div>)}</div>{selected&&loaded===selected&&<form className="stackForm" onSubmit={send} style={{marginTop:16}}><textarea name="body" rows={3} maxLength={4000} required placeholder={ar?"رد على هذا الحجز":"Reply to this booking"}/><button className="primaryButton" disabled={busy}>{ar?"إرسال الرد":"Send reply"}</button></form>}{error&&<p className="danger">{error}</p>}</section></div>;
}
async function api<T=unknown>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{...init,cache:"no-store"});const body=await response.json();if(!response.ok||body.error)throw new Error(body.error?.message||"Request failed");return body.data as T;}
