"use client";
import Link from "next/link";
import { useState } from "react";

export function ResetPasswordForm({locale,token}:{locale:"en"|"ar";token:string}) {
  const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [busy,setBusy]=useState(false);const [done,setDone]=useState(false);const [error,setError]=useState("");
  async function submit(event:React.FormEvent){event.preventDefault();if(password!==confirm){setError(locale==="ar"?"كلمتا المرور غير متطابقتين.":"Passwords do not match.");return;}setBusy(true);setError("");try{const response=await fetch("/api/v1/auth/password/reset",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,newPassword:password})});const body=await response.json().catch(()=>null) as {error?:{message?:string}}|null;if(!response.ok)throw new Error(body?.error?.message??(locale==="ar"?"تعذر تغيير كلمة المرور.":"Could not reset password."));setDone(true);}catch(error){setError(error instanceof Error?error.message:"Request failed");}finally{setBusy(false);}}
  if(done)return <div className="opsNotice success"><strong>{locale==="ar"?"تم تغيير كلمة المرور":"Password changed"}</strong><p>{locale==="ar"?"تم تسجيل خروج الجلسات السابقة لحماية الحساب.":"Existing sessions were signed out to protect your account."}</p><Link className="opsPrimaryLink" href="/login">{locale==="ar"?"تسجيل الدخول":"Sign in"}</Link></div>;
  return <form className="opsForm" onSubmit={submit}><label><span>{locale==="ar"?"كلمة المرور الجديدة":"New password"}</span><input type="password" minLength={12} maxLength={128} required autoComplete="new-password" value={password} onChange={(e)=>setPassword(e.target.value)}/><small>{locale==="ar"?"12 حرفاً على الأقل":"At least 12 characters"}</small></label><label><span>{locale==="ar"?"تأكيد كلمة المرور":"Confirm password"}</span><input type="password" minLength={12} maxLength={128} required autoComplete="new-password" value={confirm} onChange={(e)=>setConfirm(e.target.value)}/></label>{error&&<p className="opsError">{error}</p>}<button type="submit" disabled={busy}>{busy?(locale==="ar"?"جارٍ التحديث…":"Updating…"):(locale==="ar"?"تغيير كلمة المرور":"Change password")}</button></form>;
}
