import Link from "next/link";
import { redirect } from "next/navigation";
import { hotelPerformanceQuerySchema } from "@platform/contracts";
import { getHotelPerformance, listUserHotels } from "@platform/server";
import { currentUser } from "@/lib/server-session";

export const dynamic = "force-dynamic";

export default async function PerformancePage({searchParams}:{searchParams:Promise<{hotelId?:string;days?:string}>}){
  const user=await currentUser();if(!user)redirect("/login");
  const hotels=await listUserHotels(user.id);if(!hotels.length)redirect("/partner/onboarding");
  const query=await searchParams;const selected=hotels.find((hotel)=>hotel.id===query.hotelId)??hotels[0];if(!selected)redirect("/hotel-dashboard");
  const parsed=hotelPerformanceQuerySchema.safeParse({days:query.days??"30"});const input=parsed.success?parsed.data:{days:30};
  const data=await getHotelPerformance(user.id,selected.id,input);
  return <main className="soft"><header className="shell topbar"><Link href="/" className="brand">B</Link><nav><Link href={`/hotel-dashboard?hotelId=${selected.id}`}>Property</Link><Link href={`/hotel-dashboard/promotions?hotelId=${selected.id}`}>Promotions</Link><Link href={`/hotel-dashboard/reservations?hotelId=${selected.id}`}>Reservations</Link></nav></header><section className="shell section">
    <div className="sectionHead"><div><span className="eyebrow">First-party revenue intelligence</span><h1>Performance · {data.hotel.name}</h1><p className="muted">Measured from real platform searches, property views, live checkout quotes and bookings. No synthetic traffic and no AI estimates.</p></div><div style={{display:"flex",gap:8}}>{[7,30,90].map((days)=><Link key={days} className={days===input.days?"primary":"secondaryButton"} href={`/hotel-dashboard/performance?hotelId=${selected.id}&days=${days}`}>{days} days</Link>)}</div></div>
    <div className="kpiGrid"><Metric label="Search impressions" value={data.funnel.impressions}/><Metric label="Hotel views" value={data.funnel.views} sub={pct(data.funnel.viewRate)+" view rate"}/><Metric label="Checkout starts" value={data.funnel.checkoutStarts} sub={pct(data.funnel.checkoutRate)+" of views"}/><Metric label="Booking holds" value={data.funnel.holds} sub={pct(data.funnel.holdRate)+" of checkout"}/><Metric label="Confirmed bookings" value={data.funnel.confirmed} sub={pct(data.funnel.bookingRateFromCheckout)+" checkout conversion"}/><Metric label="Active booked value" value={`${data.outcomes.activeBookedValue.toFixed(2)} ${data.hotel.currency}`}/></div>
    <div className="grid2" style={{marginTop:22}}><section className="panel"><span className="eyebrow">Conversion funnel</span><h2>Where guests drop</h2><FunnelRow label="Impression → view" value={data.funnel.viewRate}/><FunnelRow label="View → checkout" value={data.funnel.checkoutRate}/><FunnelRow label="Checkout → hold" value={data.funnel.holdRate}/><FunnelRow label="Checkout → confirmed" value={data.funnel.bookingRateFromCheckout}/><FunnelRow label="Impression → confirmed" value={data.funnel.bookingRateFromImpression}/><div className="breakdown"><span>Cancellation rate</span><strong>{pct(data.outcomes.cancellationRate)}</strong></div><div className="breakdown"><span>Hold expiry rate</span><strong>{pct(data.outcomes.holdExpiryRate)}</strong></div></section><section className="panel"><span className="eyebrow">Opportunity engine</span><h2>Deterministic signals</h2><p className="muted">These are rule-based observations from your actual funnel. They are not AI-generated advice.</p>{data.signals.map((signal)=><div className="alertCard" key={signal.code}><div><strong>{signal.title}</strong><p>{signal.detail}</p><small className={signal.severity==="ATTENTION"?"danger":signal.severity==="OPPORTUNITY"?"status":"muted"}>{signal.severity}</small></div></div>)}</section></div>
    <section className="panel" style={{marginTop:22}}><span className="eyebrow">Market demand</span><h2>Most requested future arrival dates in {data.hotel.city}</h2><p className="muted">Demand is aggregated from destination searches made during the selected reporting window. No guest identity, IP address or fingerprint is stored.</p>{data.demand.topArrivalDates.length===0?<p className="muted">Not enough future search demand yet.</p>:<div className="roomTable"><div className="roomRow roomHead"><span>Arrival date</span><span>Searches</span><span>Guest demand</span><span>Zero-result searches</span><span></span></div>{data.demand.topArrivalDates.map((item)=><div className="roomRow" key={item.date}><strong>{item.date}</strong><span>{item.searches}</span><span>{item.guestDemand}</span><span>{item.zeroResultSearches}</span><span></span></div>)}</div>}</section>
  </section></main>;
}

function Metric({label,value,sub}:{label:string;value:string|number;sub?:string}){return <div className="kpi"><span>{label}</span><strong>{value}</strong>{sub&&<small className="muted">{sub}</small>}</div>;}
function FunnelRow({label,value}:{label:string;value:number}){return <div className="breakdown"><span>{label}</span><strong>{pct(value)}</strong></div>;}
function pct(value:number){return `${(value*100).toFixed(1)}%`;}
