import type {GuestLocale} from "./guest-market";

type Copy=Readonly<{
  welcome:(name:string)=>string;walletBalance:(currency:string)=>string;points:string;walletBody:string;convertible:(points:string)=>string;openWallet:string;earn:(rate:number)=>string;qualifying:(nights:number,stays:number)=>string;openRewards:string;memberSince:(date:string)=>string;memberTier:string;
}>;
const COPY:Record<GuestLocale,Copy>={
  en:{welcome:n=>`Welcome back, ${n}`,walletBalance:c=>`Wallet balance · ${c}`,points:"HandMeKey points",walletBody:"Convert Rewards points into credit and use it alone or together with another payment method on bookings.",convertible:p=>`${p} points currently available to convert`,openWallet:"Open Wallet",earn:r=>`Earn ${r} points for every eligible JOD of room base after a completed stay.`,qualifying:(n,s)=>`${n} qualifying nights · ${s} completed stays`,openRewards:"Open rewards",memberSince:d=>`Member since ${d}`,memberTier:"Rewards Member"},
  ar:{welcome:n=>`مرحبًا بعودتك، ${n}`,walletBalance:c=>`رصيد المحفظة · ${c}`,points:"نقاط HandMeKey",walletBody:"حوّل نقاط Rewards إلى رصيد واستخدمه وحده أو مع وسيلة دفع ثانية على حجوزاتك.",convertible:p=>`${p} نقطة متاحة للتحويل حاليًا`,openWallet:"افتح المحفظة",earn:r=>`اكسب ${r} نقطة لكل دينار مؤهل من سعر الغرفة بعد إتمام الإقامة.`,qualifying:(n,s)=>`${n} ليلة مؤهلة · ${s} إقامة مكتملة`,openRewards:"افتح المكافآت",memberSince:d=>`عضو منذ ${d}`,memberTier:"عضو Rewards"},
  zh:{welcome:n=>`欢迎回来，${n}`,walletBalance:c=>`钱包余额 · ${c}`,points:"HandMeKey 积分",walletBody:"将 Rewards 积分兑换为余额，可单独使用或与其他付款方式组合支付预订。",convertible:p=>`当前有 ${p} 积分可兑换`,openWallet:"打开钱包",earn:r=>`每完成一次符合条件的住宿，每 1 JOD 房费可赚取 ${r} 积分。`,qualifying:(n,s)=>`${n} 个有效住宿晚数 · ${s} 次已完成住宿`,openRewards:"打开奖励",memberSince:d=>`加入于 ${d}`,memberTier:"Rewards 会员"},
  fr:{welcome:n=>`Bon retour, ${n}`,walletBalance:c=>`Solde du portefeuille · ${c}`,points:"Points HandMeKey",walletBody:"Convertissez vos points Rewards en crédit et utilisez-le seul ou avec un autre moyen de paiement.",convertible:p=>`${p} points actuellement convertibles`,openWallet:"Ouvrir le portefeuille",earn:r=>`Gagnez ${r} points par JOD éligible de prix de chambre après un séjour terminé.`,qualifying:(n,s)=>`${n} nuits éligibles · ${s} séjours terminés`,openRewards:"Ouvrir les récompenses",memberSince:d=>`Membre depuis ${d}`,memberTier:"Membre Rewards"},
  de:{welcome:n=>`Willkommen zurück, ${n}`,walletBalance:c=>`Wallet-Guthaben · ${c}`,points:"HandMeKey-Punkte",walletBody:"Wandeln Sie Rewards-Punkte in Guthaben um und nutzen Sie es allein oder zusammen mit einer anderen Zahlungsart.",convertible:p=>`${p} Punkte derzeit umwandelbar`,openWallet:"Wallet öffnen",earn:r=>`Sammeln Sie ${r} Punkte pro berechtigtem JOD Zimmergrundpreis nach einem abgeschlossenen Aufenthalt.`,qualifying:(n,s)=>`${n} qualifizierende Nächte · ${s} abgeschlossene Aufenthalte`,openRewards:"Prämien öffnen",memberSince:d=>`Mitglied seit ${d}`,memberTier:"Rewards-Mitglied"},
  es:{welcome:n=>`Bienvenido de nuevo, ${n}`,walletBalance:c=>`Saldo del monedero · ${c}`,points:"Puntos HandMeKey",walletBody:"Convierte puntos Rewards en crédito y úsalo solo o junto con otro método de pago en tus reservas.",convertible:p=>`${p} puntos disponibles para convertir`,openWallet:"Abrir monedero",earn:r=>`Gana ${r} puntos por cada JOD elegible de tarifa base tras una estancia completada.`,qualifying:(n,s)=>`${n} noches elegibles · ${s} estancias completadas`,openRewards:"Abrir recompensas",memberSince:d=>`Miembro desde ${d}`,memberTier:"Miembro Rewards"},
  it:{welcome:n=>`Bentornato, ${n}`,walletBalance:c=>`Saldo portafoglio · ${c}`,points:"Punti HandMeKey",walletBody:"Converti i punti Rewards in credito e usalo da solo o insieme a un altro metodo di pagamento.",convertible:p=>`${p} punti disponibili per la conversione`,openWallet:"Apri portafoglio",earn:r=>`Guadagna ${r} punti per ogni JOD idoneo di tariffa base dopo un soggiorno completato.`,qualifying:(n,s)=>`${n} notti idonee · ${s} soggiorni completati`,openRewards:"Apri premi",memberSince:d=>`Membro da ${d}`,memberTier:"Membro Rewards"},
  tr:{welcome:n=>`Tekrar hoş geldiniz, ${n}`,walletBalance:c=>`Cüzdan bakiyesi · ${c}`,points:"HandMeKey puanları",walletBody:"Rewards puanlarını bakiyeye çevirin ve rezervasyonlarda tek başına veya başka bir ödeme yöntemiyle kullanın.",convertible:p=>`${p} puan şu anda dönüştürülebilir`,openWallet:"Cüzdanı aç",earn:r=>`Tamamlanan konaklamadan sonra uygun oda ücretinin her 1 JOD’u için ${r} puan kazanın.`,qualifying:(n,s)=>`${n} uygun gece · ${s} tamamlanan konaklama`,openRewards:"Ödülleri aç",memberSince:d=>`${d} tarihinden beri üye`,memberTier:"Rewards Üyesi"},
  ru:{welcome:n=>`С возвращением, ${n}`,walletBalance:c=>`Баланс кошелька · ${c}`,points:"Баллы HandMeKey",walletBody:"Конвертируйте баллы Rewards в кредит и используйте его отдельно или вместе с другим способом оплаты.",convertible:p=>`Сейчас доступно для конвертации: ${p} баллов`,openWallet:"Открыть кошелёк",earn:r=>`Получайте ${r} баллов за каждый подходящий JOD базовой стоимости номера после завершённого проживания.`,qualifying:(n,s)=>`${n} квалификационных ночей · ${s} завершённых проживаний`,openRewards:"Открыть награды",memberSince:d=>`Участник с ${d}`,memberTier:"Участник Rewards"},
  ja:{welcome:n=>`おかえりなさい、${n}`,walletBalance:c=>`ウォレット残高 · ${c}`,points:"HandMeKeyポイント",walletBody:"Rewardsポイントをクレジットに交換し、単独または別の支払い方法と組み合わせて予約に使用できます。",convertible:p=>`現在 ${p} ポイントを交換可能`,openWallet:"ウォレットを開く",earn:r=>`宿泊完了後、対象の客室基本料金1 JODにつき${r}ポイント獲得。`,qualifying:(n,s)=>`対象宿泊 ${n} 泊 · 完了済み ${s} 滞在`,openRewards:"リワードを開く",memberSince:d=>`${d}から会員`,memberTier:"Rewardsメンバー"},
  ko:{welcome:n=>`다시 오신 것을 환영합니다, ${n}`,walletBalance:c=>`지갑 잔액 · ${c}`,points:"HandMeKey 포인트",walletBody:"Rewards 포인트를 크레딧으로 전환해 단독 또는 다른 결제 수단과 함께 예약에 사용하세요.",convertible:p=>`현재 ${p}포인트 전환 가능`,openWallet:"지갑 열기",earn:r=>`숙박 완료 후 적격 객실 기본요금 1 JOD당 ${r}포인트를 적립합니다.`,qualifying:(n,s)=>`적격 ${n}박 · 완료 숙박 ${s}회`,openRewards:"리워드 열기",memberSince:d=>`${d}부터 회원`,memberTier:"Rewards 회원"},
  hi:{welcome:n=>`वापसी पर स्वागत है, ${n}`,walletBalance:c=>`वॉलेट बैलेंस · ${c}`,points:"HandMeKey पॉइंट",walletBody:"Rewards पॉइंट को क्रेडिट में बदलें और बुकिंग पर अकेले या दूसरी भुगतान विधि के साथ उपयोग करें।",convertible:p=>`${p} पॉइंट अभी बदलने के लिए उपलब्ध`,openWallet:"वॉलेट खोलें",earn:r=>`पूरी हुई ठहराव के बाद हर योग्य 1 JOD कमरे के बेस पर ${r} पॉइंट कमाएँ।`,qualifying:(n,s)=>`${n} योग्य रातें · ${s} पूरी हुई ठहराव`,openRewards:"रिवॉर्ड्स खोलें",memberSince:d=>`${d} से सदस्य`,memberTier:"Rewards सदस्य"},
  pt:{welcome:n=>`Bem-vindo de volta, ${n}`,walletBalance:c=>`Saldo da carteira · ${c}`,points:"Pontos HandMeKey",walletBody:"Converta pontos Rewards em crédito e use-o sozinho ou com outra forma de pagamento nas reservas.",convertible:p=>`${p} pontos disponíveis para converter`,openWallet:"Abrir carteira",earn:r=>`Ganhe ${r} pontos por cada JOD elegível da diária base após uma estadia concluída.`,qualifying:(n,s)=>`${n} noites qualificáveis · ${s} estadias concluídas`,openRewards:"Abrir recompensas",memberSince:d=>`Membro desde ${d}`,memberTier:"Membro Rewards"},
  id:{welcome:n=>`Selamat datang kembali, ${n}`,walletBalance:c=>`Saldo dompet · ${c}`,points:"Poin HandMeKey",walletBody:"Tukar poin Rewards menjadi kredit dan gunakan sendiri atau bersama metode pembayaran lain pada reservasi.",convertible:p=>`${p} poin tersedia untuk ditukar`,openWallet:"Buka dompet",earn:r=>`Dapatkan ${r} poin untuk setiap 1 JOD tarif kamar dasar yang memenuhi syarat setelah menginap selesai.`,qualifying:(n,s)=>`${n} malam memenuhi syarat · ${s} masa inap selesai`,openRewards:"Buka Reward",memberSince:d=>`Anggota sejak ${d}`,memberTier:"Anggota Rewards"},
  th:{welcome:n=>`ยินดีต้อนรับกลับ ${n}`,walletBalance:c=>`ยอดวอลเล็ต · ${c}`,points:"คะแนน HandMeKey",walletBody:"แปลงคะแนน Rewards เป็นเครดิต แล้วใช้เดี่ยวหรือร่วมกับวิธีชำระเงินอื่นในการจอง",convertible:p=>`มี ${p} คะแนนที่แปลงได้ตอนนี้`,openWallet:"เปิดวอลเล็ต",earn:r=>`รับ ${r} คะแนนต่อค่าห้องพื้นฐานที่เข้าเกณฑ์ทุก 1 JOD หลังจบการเข้าพัก`,qualifying:(n,s)=>`${n} คืนที่เข้าเกณฑ์ · ${s} การเข้าพักที่เสร็จสิ้น`,openRewards:"เปิดรางวัล",memberSince:d=>`สมาชิกตั้งแต่ ${d}`,memberTier:"สมาชิก Rewards"},
};
export function accountOverviewUiCopy(locale:GuestLocale):Copy{return COPY[locale];}
