import type {GuestLocale} from "./guest-market";

type Copy=Readonly<{
  removedSearch:string;stoppedWatch:string;priceIntelligence:string;activeWatches:string;noWatches:string;started:string;current:string;lowest:string;target:string;reached:string;openStay:string;stopWatch:string;notifications:string;priceAlerts:string;noAlerts:string;open:string;markRead:string;savedDiscovery:string;savedSearches:string;noSearches:string;runSearch:string;remove:string;adult:(count:number)=>string;children:string;
}>;
const COPY:Record<GuestLocale,Copy>={
  en:{removedSearch:"Saved search removed.",stoppedWatch:"Price watch stopped.",priceIntelligence:"Price intelligence",activeWatches:"Active price watches",noWatches:"No active price watches yet. Open a hotel stay and choose “Watch this price”.",started:"Started",current:"Current",lowest:"Lowest",target:"Target",reached:"reached",openStay:"Open stay",stopWatch:"Stop watch",notifications:"Notifications",priceAlerts:"Price alerts",noAlerts:"No price alerts yet.",open:"Open",markRead:"Mark read",savedDiscovery:"Saved discovery",savedSearches:"Saved searches",noSearches:"No saved searches yet.",runSearch:"Run search",remove:"Remove",adult:c=>c===1?"adult":"adults",children:"children"},
  ar:{removedSearch:"تمت إزالة البحث المحفوظ.",stoppedWatch:"تم إيقاف مراقبة السعر.",priceIntelligence:"متابعة الأسعار",activeWatches:"مراقبات السعر النشطة",noWatches:"لا توجد مراقبات سعر نشطة بعد. افتح إقامة واختر مراقبة هذا السعر.",started:"البداية",current:"الحالي",lowest:"الأدنى",target:"الهدف",reached:"تحقق",openStay:"فتح الإقامة",stopWatch:"إيقاف المراقبة",notifications:"الإشعارات",priceAlerts:"تنبيهات الأسعار",noAlerts:"لا توجد تنبيهات سعر بعد.",open:"فتح",markRead:"تحديد كمقروء",savedDiscovery:"عمليات البحث المحفوظة",savedSearches:"عمليات البحث المحفوظة",noSearches:"لا توجد عمليات بحث محفوظة بعد.",runSearch:"تشغيل البحث",remove:"إزالة",adult:()=>"بالغ",children:"أطفال"},
  zh:{removedSearch:"已删除保存的搜索。",stoppedWatch:"已停止价格监控。",priceIntelligence:"价格跟踪",activeWatches:"正在监控的价格",noWatches:"暂无价格监控。打开酒店住宿并选择“监控此价格”。",started:"开始价",current:"当前",lowest:"最低",target:"目标",reached:"已达到",openStay:"打开住宿",stopWatch:"停止监控",notifications:"通知",priceAlerts:"价格提醒",noAlerts:"暂无价格提醒。",open:"打开",markRead:"标为已读",savedDiscovery:"保存的搜索",savedSearches:"保存的搜索",noSearches:"暂无保存的搜索。",runSearch:"运行搜索",remove:"删除",adult:()=>"成人",children:"儿童"},
  fr:{removedSearch:"Recherche enregistrée supprimée.",stoppedWatch:"Suivi de prix arrêté.",priceIntelligence:"Suivi des prix",activeWatches:"Suivis de prix actifs",noWatches:"Aucun suivi actif. Ouvrez un séjour et choisissez de surveiller son prix.",started:"Départ",current:"Actuel",lowest:"Plus bas",target:"Objectif",reached:"atteint",openStay:"Ouvrir le séjour",stopWatch:"Arrêter le suivi",notifications:"Notifications",priceAlerts:"Alertes de prix",noAlerts:"Aucune alerte de prix.",open:"Ouvrir",markRead:"Marquer comme lu",savedDiscovery:"Recherches enregistrées",savedSearches:"Recherches enregistrées",noSearches:"Aucune recherche enregistrée.",runSearch:"Relancer la recherche",remove:"Supprimer",adult:c=>c===1?"adulte":"adultes",children:"enfants"},
  de:{removedSearch:"Gespeicherte Suche entfernt.",stoppedWatch:"Preisbeobachtung beendet.",priceIntelligence:"Preisbeobachtung",activeWatches:"Aktive Preisbeobachtungen",noWatches:"Noch keine aktive Preisbeobachtung. Öffnen Sie einen Aufenthalt und wählen Sie „Preis beobachten“.",started:"Start",current:"Aktuell",lowest:"Tiefster",target:"Ziel",reached:"erreicht",openStay:"Aufenthalt öffnen",stopWatch:"Beobachtung stoppen",notifications:"Benachrichtigungen",priceAlerts:"Preisalarme",noAlerts:"Noch keine Preisalarme.",open:"Öffnen",markRead:"Als gelesen markieren",savedDiscovery:"Gespeicherte Suche",savedSearches:"Gespeicherte Suchen",noSearches:"Noch keine gespeicherten Suchen.",runSearch:"Suche ausführen",remove:"Entfernen",adult:c=>c===1?"Erwachsener":"Erwachsene",children:"Kinder"},
  es:{removedSearch:"Búsqueda guardada eliminada.",stoppedWatch:"Seguimiento de precio detenido.",priceIntelligence:"Seguimiento de precios",activeWatches:"Seguimientos de precio activos",noWatches:"Aún no hay seguimientos activos. Abre una estancia y elige vigilar su precio.",started:"Inicio",current:"Actual",lowest:"Más bajo",target:"Objetivo",reached:"alcanzado",openStay:"Abrir estancia",stopWatch:"Detener seguimiento",notifications:"Notificaciones",priceAlerts:"Alertas de precio",noAlerts:"Aún no hay alertas de precio.",open:"Abrir",markRead:"Marcar como leído",savedDiscovery:"Búsquedas guardadas",savedSearches:"Búsquedas guardadas",noSearches:"Aún no hay búsquedas guardadas.",runSearch:"Ejecutar búsqueda",remove:"Eliminar",adult:c=>c===1?"adulto":"adultos",children:"niños"},
  it:{removedSearch:"Ricerca salvata rimossa.",stoppedWatch:"Monitoraggio prezzo interrotto.",priceIntelligence:"Monitoraggio prezzi",activeWatches:"Monitoraggi prezzo attivi",noWatches:"Nessun monitoraggio attivo. Apri un soggiorno e scegli di monitorarne il prezzo.",started:"Inizio",current:"Attuale",lowest:"Più basso",target:"Obiettivo",reached:"raggiunto",openStay:"Apri soggiorno",stopWatch:"Interrompi monitoraggio",notifications:"Notifiche",priceAlerts:"Avvisi di prezzo",noAlerts:"Nessun avviso di prezzo.",open:"Apri",markRead:"Segna come letto",savedDiscovery:"Ricerche salvate",savedSearches:"Ricerche salvate",noSearches:"Nessuna ricerca salvata.",runSearch:"Esegui ricerca",remove:"Rimuovi",adult:c=>c===1?"adulto":"adulti",children:"bambini"},
  tr:{removedSearch:"Kayıtlı arama kaldırıldı.",stoppedWatch:"Fiyat takibi durduruldu.",priceIntelligence:"Fiyat takibi",activeWatches:"Aktif fiyat takipleri",noWatches:"Henüz aktif fiyat takibi yok. Bir konaklama açıp fiyatı takip etmeyi seçin.",started:"Başlangıç",current:"Güncel",lowest:"En düşük",target:"Hedef",reached:"ulaşıldı",openStay:"Konaklamayı aç",stopWatch:"Takibi durdur",notifications:"Bildirimler",priceAlerts:"Fiyat uyarıları",noAlerts:"Henüz fiyat uyarısı yok.",open:"Aç",markRead:"Okundu işaretle",savedDiscovery:"Kayıtlı aramalar",savedSearches:"Kayıtlı aramalar",noSearches:"Henüz kayıtlı arama yok.",runSearch:"Aramayı çalıştır",remove:"Kaldır",adult:()=>"yetişkin",children:"çocuk"},
  ru:{removedSearch:"Сохранённый поиск удалён.",stoppedWatch:"Отслеживание цены остановлено.",priceIntelligence:"Отслеживание цен",activeWatches:"Активные отслеживания",noWatches:"Активных отслеживаний пока нет. Откройте проживание и включите наблюдение за ценой.",started:"Начальная",current:"Текущая",lowest:"Минимальная",target:"Цель",reached:"достигнута",openStay:"Открыть проживание",stopWatch:"Остановить",notifications:"Уведомления",priceAlerts:"Ценовые уведомления",noAlerts:"Ценовых уведомлений пока нет.",open:"Открыть",markRead:"Отметить прочитанным",savedDiscovery:"Сохранённые поиски",savedSearches:"Сохранённые поиски",noSearches:"Сохранённых поисков пока нет.",runSearch:"Запустить поиск",remove:"Удалить",adult:()=>"взрослых",children:"детей"},
  ja:{removedSearch:"保存した検索を削除しました。",stoppedWatch:"価格監視を停止しました。",priceIntelligence:"価格トラッキング",activeWatches:"有効な価格監視",noWatches:"有効な価格監視はまだありません。宿泊を開き、価格監視を選択してください。",started:"開始時",current:"現在",lowest:"最安",target:"目標",reached:"達成",openStay:"宿泊を開く",stopWatch:"監視を停止",notifications:"通知",priceAlerts:"価格アラート",noAlerts:"価格アラートはまだありません。",open:"開く",markRead:"既読にする",savedDiscovery:"保存した検索",savedSearches:"保存した検索",noSearches:"保存した検索はまだありません。",runSearch:"検索を実行",remove:"削除",adult:()=>"大人",children:"子供"},
  ko:{removedSearch:"저장된 검색을 삭제했습니다.",stoppedWatch:"가격 추적을 중지했습니다.",priceIntelligence:"가격 추적",activeWatches:"활성 가격 추적",noWatches:"활성 가격 추적이 없습니다. 숙박을 열고 가격 추적을 선택하세요.",started:"시작",current:"현재",lowest:"최저",target:"목표",reached:"달성",openStay:"숙박 열기",stopWatch:"추적 중지",notifications:"알림",priceAlerts:"가격 알림",noAlerts:"가격 알림이 없습니다.",open:"열기",markRead:"읽음 표시",savedDiscovery:"저장된 검색",savedSearches:"저장된 검색",noSearches:"저장된 검색이 없습니다.",runSearch:"검색 실행",remove:"삭제",adult:()=>"성인",children:"아동"},
  hi:{removedSearch:"सहेजी गई खोज हटा दी गई।",stoppedWatch:"मूल्य निगरानी रोक दी गई।",priceIntelligence:"मूल्य निगरानी",activeWatches:"सक्रिय मूल्य निगरानी",noWatches:"अभी कोई सक्रिय मूल्य निगरानी नहीं है। कोई ठहराव खोलें और मूल्य निगरानी चुनें।",started:"शुरुआत",current:"वर्तमान",lowest:"सबसे कम",target:"लक्ष्य",reached:"पूरा",openStay:"ठहराव खोलें",stopWatch:"निगरानी रोकें",notifications:"सूचनाएँ",priceAlerts:"मूल्य अलर्ट",noAlerts:"अभी कोई मूल्य अलर्ट नहीं।",open:"खोलें",markRead:"पढ़ा हुआ",savedDiscovery:"सहेजी गई खोज",savedSearches:"सहेजी गई खोजें",noSearches:"अभी कोई सहेजी गई खोज नहीं।",runSearch:"खोज चलाएँ",remove:"हटाएँ",adult:()=>"वयस्क",children:"बच्चे"},
  pt:{removedSearch:"Pesquisa salva removida.",stoppedWatch:"Monitoramento de preço interrompido.",priceIntelligence:"Monitoramento de preços",activeWatches:"Monitoramentos ativos",noWatches:"Ainda não há monitoramentos ativos. Abra uma estadia e escolha acompanhar o preço.",started:"Início",current:"Atual",lowest:"Menor",target:"Meta",reached:"atingida",openStay:"Abrir estadia",stopWatch:"Parar monitoramento",notifications:"Notificações",priceAlerts:"Alertas de preço",noAlerts:"Ainda não há alertas de preço.",open:"Abrir",markRead:"Marcar como lido",savedDiscovery:"Pesquisas salvas",savedSearches:"Pesquisas salvas",noSearches:"Ainda não há pesquisas salvas.",runSearch:"Executar pesquisa",remove:"Remover",adult:c=>c===1?"adulto":"adultos",children:"crianças"},
  id:{removedSearch:"Pencarian tersimpan dihapus.",stoppedWatch:"Pemantauan harga dihentikan.",priceIntelligence:"Pemantauan harga",activeWatches:"Pemantauan harga aktif",noWatches:"Belum ada pemantauan aktif. Buka penginapan dan pilih untuk memantau harganya.",started:"Awal",current:"Saat ini",lowest:"Terendah",target:"Target",reached:"tercapai",openStay:"Buka penginapan",stopWatch:"Hentikan pemantauan",notifications:"Notifikasi",priceAlerts:"Peringatan harga",noAlerts:"Belum ada peringatan harga.",open:"Buka",markRead:"Tandai dibaca",savedDiscovery:"Pencarian tersimpan",savedSearches:"Pencarian tersimpan",noSearches:"Belum ada pencarian tersimpan.",runSearch:"Jalankan pencarian",remove:"Hapus",adult:()=>"dewasa",children:"anak"},
  th:{removedSearch:"ลบการค้นหาที่บันทึกแล้ว",stoppedWatch:"หยุดติดตามราคาแล้ว",priceIntelligence:"ติดตามราคา",activeWatches:"การติดตามราคาที่ใช้งาน",noWatches:"ยังไม่มีการติดตามราคา เปิดที่พักแล้วเลือกติดตามราคานี้",started:"เริ่มต้น",current:"ปัจจุบัน",lowest:"ต่ำสุด",target:"เป้าหมาย",reached:"ถึงแล้ว",openStay:"เปิดที่พัก",stopWatch:"หยุดติดตาม",notifications:"การแจ้งเตือน",priceAlerts:"แจ้งเตือนราคา",noAlerts:"ยังไม่มีการแจ้งเตือนราคา",open:"เปิด",markRead:"ทำเครื่องหมายว่าอ่านแล้ว",savedDiscovery:"การค้นหาที่บันทึก",savedSearches:"การค้นหาที่บันทึก",noSearches:"ยังไม่มีการค้นหาที่บันทึก",runSearch:"ค้นหาอีกครั้ง",remove:"ลบ",adult:()=>"ผู้ใหญ่",children:"เด็ก"},
};
export function alertsUiCopy(locale:GuestLocale):Copy{return COPY[locale];}
