import type {GuestLocale} from "./guest-market";

type AuthCopy=Readonly<{
  unable:string;signIn:string;createAccount:string;partnerAccess:string;account:string;welcome:string;createTitle:string;partnerBody:string;guestBody:string;fullName:string;namePlaceholder:string;email:string;password:string;passwordHint:string;forgot:string;wait:string;createButton:string;partnerFoot:string;guestFoot:string;
}>;
const COPY:Record<GuestLocale,AuthCopy>={
  en:{unable:"Unable to continue",signIn:"Sign in",createAccount:"Create account",partnerAccess:"Partner access",account:"HandMeKey account",welcome:"Welcome back",createTitle:"Create your account",partnerBody:"Manage properties, reservations, rates and performance from Partner Hub.",guestBody:"Keep your trips, price alerts and booking messages in one place.",fullName:"Full name",namePlaceholder:"Your full name",email:"Email address",password:"Password",passwordHint:"At least 10 characters",forgot:"Forgot password?",wait:"Please wait…",createButton:"Create account",partnerFoot:"Property access is permission-based. Your account only sees hotels you are authorized to manage.",guestFoot:"Your booking access stays tied to your account and verified booking credentials."},
  ar:{unable:"تعذر المتابعة",signIn:"تسجيل الدخول",createAccount:"إنشاء حساب",partnerAccess:"دخول الشريك",account:"حساب HandMeKey",welcome:"مرحبًا بعودتك",createTitle:"أنشئ حسابك",partnerBody:"أدر منشآتك وحجوزاتك وأسعارك وأداءك من بوابة الشركاء.",guestBody:"احتفظ بحجوزاتك وتنبيهات الأسعار ورسائل الحجز في مكان واحد.",fullName:"الاسم الكامل",namePlaceholder:"اسمك الكامل",email:"البريد الإلكتروني",password:"كلمة المرور",passwordHint:"10 أحرف على الأقل",forgot:"نسيت كلمة المرور؟",wait:"يرجى الانتظار…",createButton:"إنشاء الحساب",partnerFoot:"صلاحيات المنشأة محددة؛ لا يرى حسابك إلا الفنادق المصرح له بإدارتها.",guestFoot:"يبقى الوصول إلى حجوزاتك مرتبطًا بحسابك وبيانات الحجز الموثقة."},
  zh:{unable:"无法继续",signIn:"登录",createAccount:"创建账户",partnerAccess:"合作伙伴入口",account:"HandMeKey 账户",welcome:"欢迎回来",createTitle:"创建账户",partnerBody:"通过合作伙伴中心管理酒店、预订、价格和表现。",guestBody:"在一个地方管理行程、价格提醒和预订消息。",fullName:"姓名",namePlaceholder:"您的姓名",email:"电子邮箱",password:"密码",passwordHint:"至少 10 个字符",forgot:"忘记密码？",wait:"请稍候…",createButton:"创建账户",partnerFoot:"酒店访问权限按授权控制。您的账户只会看到获准管理的酒店。",guestFoot:"您的预订访问权限始终与账户和已验证的预订凭据绑定。"},
  fr:{unable:"Impossible de continuer",signIn:"Se connecter",createAccount:"Créer un compte",partnerAccess:"Accès partenaire",account:"Compte HandMeKey",welcome:"Bon retour",createTitle:"Créez votre compte",partnerBody:"Gérez établissements, réservations, tarifs et performances depuis Partner Hub.",guestBody:"Gardez vos séjours, alertes de prix et messages de réservation au même endroit.",fullName:"Nom complet",namePlaceholder:"Votre nom complet",email:"Adresse e-mail",password:"Mot de passe",passwordHint:"Au moins 10 caractères",forgot:"Mot de passe oublié ?",wait:"Veuillez patienter…",createButton:"Créer le compte",partnerFoot:"L’accès aux établissements dépend des autorisations. Votre compte ne voit que les hôtels que vous êtes autorisé à gérer.",guestFoot:"L’accès à vos réservations reste lié à votre compte et à vos identifiants de réservation vérifiés."},
  de:{unable:"Fortfahren nicht möglich",signIn:"Anmelden",createAccount:"Konto erstellen",partnerAccess:"Partnerzugang",account:"HandMeKey-Konto",welcome:"Willkommen zurück",createTitle:"Konto erstellen",partnerBody:"Verwalten Sie Unterkünfte, Buchungen, Preise und Performance im Partner Hub.",guestBody:"Verwalten Sie Reisen, Preisalarme und Buchungsnachrichten an einem Ort.",fullName:"Vollständiger Name",namePlaceholder:"Ihr vollständiger Name",email:"E-Mail-Adresse",password:"Passwort",passwordHint:"Mindestens 10 Zeichen",forgot:"Passwort vergessen?",wait:"Bitte warten…",createButton:"Konto erstellen",partnerFoot:"Der Unterkunftszugriff ist berechtigungsbasiert. Ihr Konto sieht nur Hotels, die Sie verwalten dürfen.",guestFoot:"Der Zugriff auf Ihre Buchungen bleibt an Ihr Konto und verifizierte Buchungsdaten gebunden."},
  es:{unable:"No se puede continuar",signIn:"Iniciar sesión",createAccount:"Crear cuenta",partnerAccess:"Acceso para socios",account:"Cuenta HandMeKey",welcome:"Bienvenido de nuevo",createTitle:"Crea tu cuenta",partnerBody:"Gestiona alojamientos, reservas, tarifas y rendimiento desde Partner Hub.",guestBody:"Mantén tus viajes, alertas de precios y mensajes de reserva en un solo lugar.",fullName:"Nombre completo",namePlaceholder:"Tu nombre completo",email:"Correo electrónico",password:"Contraseña",passwordHint:"Al menos 10 caracteres",forgot:"¿Olvidaste tu contraseña?",wait:"Espera un momento…",createButton:"Crear cuenta",partnerFoot:"El acceso a propiedades depende de permisos. Tu cuenta solo ve los hoteles que estás autorizado a gestionar.",guestFoot:"El acceso a tus reservas permanece vinculado a tu cuenta y a credenciales de reserva verificadas."},
  it:{unable:"Impossibile continuare",signIn:"Accedi",createAccount:"Crea account",partnerAccess:"Accesso partner",account:"Account HandMeKey",welcome:"Bentornato",createTitle:"Crea il tuo account",partnerBody:"Gestisci strutture, prenotazioni, tariffe e performance dal Partner Hub.",guestBody:"Tieni viaggi, avvisi di prezzo e messaggi di prenotazione in un unico posto.",fullName:"Nome completo",namePlaceholder:"Il tuo nome completo",email:"Indirizzo e-mail",password:"Password",passwordHint:"Almeno 10 caratteri",forgot:"Password dimenticata?",wait:"Attendi…",createButton:"Crea account",partnerFoot:"L’accesso alle strutture dipende dai permessi. Il tuo account vede solo gli hotel che sei autorizzato a gestire.",guestFoot:"L’accesso alle prenotazioni resta legato al tuo account e alle credenziali di prenotazione verificate."},
  tr:{unable:"Devam edilemiyor",signIn:"Giriş yap",createAccount:"Hesap oluştur",partnerAccess:"İş ortağı erişimi",account:"HandMeKey hesabı",welcome:"Tekrar hoş geldiniz",createTitle:"Hesabınızı oluşturun",partnerBody:"Tesisleri, rezervasyonları, fiyatları ve performansı Partner Hub'dan yönetin.",guestBody:"Seyahatlerinizi, fiyat uyarılarınızı ve rezervasyon mesajlarınızı tek yerde tutun.",fullName:"Ad soyad",namePlaceholder:"Adınız ve soyadınız",email:"E-posta adresi",password:"Şifre",passwordHint:"En az 10 karakter",forgot:"Şifrenizi mi unuttunuz?",wait:"Lütfen bekleyin…",createButton:"Hesap oluştur",partnerFoot:"Tesis erişimi yetkilere bağlıdır. Hesabınız yalnızca yönetmeye yetkili olduğunuz otelleri görür.",guestFoot:"Rezervasyon erişiminiz hesabınıza ve doğrulanmış rezervasyon bilgilerinize bağlı kalır."},
  ru:{unable:"Не удалось продолжить",signIn:"Войти",createAccount:"Создать аккаунт",partnerAccess:"Вход для партнёров",account:"Аккаунт HandMeKey",welcome:"С возвращением",createTitle:"Создайте аккаунт",partnerBody:"Управляйте объектами, бронированиями, тарифами и показателями в Partner Hub.",guestBody:"Храните поездки, ценовые уведомления и сообщения по бронированиям в одном месте.",fullName:"Полное имя",namePlaceholder:"Ваше полное имя",email:"Электронная почта",password:"Пароль",passwordHint:"Не менее 10 символов",forgot:"Забыли пароль?",wait:"Подождите…",createButton:"Создать аккаунт",partnerFoot:"Доступ к объектам определяется правами. Аккаунт видит только отели, которыми вам разрешено управлять.",guestFoot:"Доступ к бронированиям остаётся привязанным к аккаунту и подтверждённым данным бронирования."},
  ja:{unable:"続行できません",signIn:"ログイン",createAccount:"アカウント作成",partnerAccess:"パートナーアクセス",account:"HandMeKey アカウント",welcome:"おかえりなさい",createTitle:"アカウントを作成",partnerBody:"Partner Hub で施設、予約、料金、パフォーマンスを管理できます。",guestBody:"旅行、価格アラート、予約メッセージをひとつにまとめて管理できます。",fullName:"氏名",namePlaceholder:"氏名を入力",email:"メールアドレス",password:"パスワード",passwordHint:"10文字以上",forgot:"パスワードをお忘れですか？",wait:"お待ちください…",createButton:"アカウント作成",partnerFoot:"施設へのアクセスは権限に基づきます。管理を許可されたホテルのみ表示されます。",guestFoot:"予約へのアクセスはアカウントと確認済み予約情報に紐づきます。"},
  ko:{unable:"계속할 수 없습니다",signIn:"로그인",createAccount:"계정 만들기",partnerAccess:"파트너 접속",account:"HandMeKey 계정",welcome:"다시 오신 것을 환영합니다",createTitle:"계정을 만드세요",partnerBody:"Partner Hub에서 숙소, 예약, 요금 및 성과를 관리하세요.",guestBody:"여행, 가격 알림 및 예약 메시지를 한곳에서 관리하세요.",fullName:"이름",namePlaceholder:"이름을 입력하세요",email:"이메일 주소",password:"비밀번호",passwordHint:"10자 이상",forgot:"비밀번호를 잊으셨나요?",wait:"잠시만 기다려 주세요…",createButton:"계정 만들기",partnerFoot:"숙소 접근은 권한에 따라 제한됩니다. 관리 권한이 있는 호텔만 표시됩니다.",guestFoot:"예약 접근 권한은 계정과 확인된 예약 자격 정보에 연결됩니다."},
  hi:{unable:"आगे नहीं बढ़ा जा सका",signIn:"साइन इन",createAccount:"खाता बनाएँ",partnerAccess:"पार्टनर एक्सेस",account:"HandMeKey खाता",welcome:"वापसी पर स्वागत है",createTitle:"अपना खाता बनाएँ",partnerBody:"Partner Hub से प्रॉपर्टी, बुकिंग, रेट और प्रदर्शन प्रबंधित करें।",guestBody:"यात्राएँ, कीमत अलर्ट और बुकिंग संदेश एक जगह रखें।",fullName:"पूरा नाम",namePlaceholder:"आपका पूरा नाम",email:"ईमेल पता",password:"पासवर्ड",passwordHint:"कम से कम 10 अक्षर",forgot:"पासवर्ड भूल गए?",wait:"कृपया प्रतीक्षा करें…",createButton:"खाता बनाएँ",partnerFoot:"प्रॉपर्टी एक्सेस अनुमति आधारित है। आपका खाता केवल उन्हीं होटलों को देखता है जिन्हें प्रबंधित करने की अनुमति है।",guestFoot:"आपकी बुकिंग एक्सेस आपके खाते और सत्यापित बुकिंग क्रेडेंशियल से जुड़ी रहती है।"},
  pt:{unable:"Não foi possível continuar",signIn:"Entrar",createAccount:"Criar conta",partnerAccess:"Acesso de parceiro",account:"Conta HandMeKey",welcome:"Bem-vindo de volta",createTitle:"Crie sua conta",partnerBody:"Gerencie propriedades, reservas, tarifas e desempenho no Partner Hub.",guestBody:"Mantenha viagens, alertas de preços e mensagens de reserva em um só lugar.",fullName:"Nome completo",namePlaceholder:"Seu nome completo",email:"Endereço de e-mail",password:"Senha",passwordHint:"Pelo menos 10 caracteres",forgot:"Esqueceu a senha?",wait:"Aguarde…",createButton:"Criar conta",partnerFoot:"O acesso à propriedade depende de permissões. Sua conta só vê hotéis que você está autorizado a gerenciar.",guestFoot:"O acesso às suas reservas permanece vinculado à sua conta e às credenciais de reserva verificadas."},
  id:{unable:"Tidak dapat melanjutkan",signIn:"Masuk",createAccount:"Buat akun",partnerAccess:"Akses mitra",account:"Akun HandMeKey",welcome:"Selamat datang kembali",createTitle:"Buat akun Anda",partnerBody:"Kelola properti, reservasi, harga, dan performa dari Partner Hub.",guestBody:"Simpan perjalanan, peringatan harga, dan pesan reservasi di satu tempat.",fullName:"Nama lengkap",namePlaceholder:"Nama lengkap Anda",email:"Alamat email",password:"Kata sandi",passwordHint:"Minimal 10 karakter",forgot:"Lupa kata sandi?",wait:"Mohon tunggu…",createButton:"Buat akun",partnerFoot:"Akses properti berdasarkan izin. Akun Anda hanya melihat hotel yang diizinkan untuk Anda kelola.",guestFoot:"Akses reservasi tetap terhubung ke akun dan kredensial reservasi terverifikasi."},
  th:{unable:"ไม่สามารถดำเนินการต่อได้",signIn:"เข้าสู่ระบบ",createAccount:"สร้างบัญชี",partnerAccess:"เข้าสำหรับพาร์ทเนอร์",account:"บัญชี HandMeKey",welcome:"ยินดีต้อนรับกลับ",createTitle:"สร้างบัญชีของคุณ",partnerBody:"จัดการที่พัก การจอง ราคา และประสิทธิภาพจาก Partner Hub",guestBody:"เก็บทริป การแจ้งเตือนราคา และข้อความการจองไว้ในที่เดียว",fullName:"ชื่อ-นามสกุล",namePlaceholder:"ชื่อ-นามสกุลของคุณ",email:"อีเมล",password:"รหัสผ่าน",passwordHint:"อย่างน้อย 10 ตัวอักษร",forgot:"ลืมรหัสผ่าน?",wait:"กรุณารอสักครู่…",createButton:"สร้างบัญชี",partnerFoot:"การเข้าถึงที่พักขึ้นอยู่กับสิทธิ์ บัญชีของคุณจะเห็นเฉพาะโรงแรมที่ได้รับอนุญาตให้จัดการ",guestFoot:"สิทธิ์เข้าถึงการจองยังคงเชื่อมกับบัญชีและข้อมูลการจองที่ยืนยันแล้ว"},
};
export function authUiCopy(locale:GuestLocale):AuthCopy{return COPY[locale];}
