export type DemoCar = Readonly<{
  id: string;
  brand: string;
  model: string;
  year: number;
  category: "Economy"|"Compact"|"Sedan"|"SUV"|"Luxury"|"Van"|"Electric"|"Pickup";
  transmission: "Automatic"|"Manual";
  fuel: "Petrol"|"Diesel"|"Hybrid"|"Electric";
  seats: number;
  bags: number;
  doors: number;
  dailyPrice: number;
  supplier: string;
  supplierRating: number;
  deposit: number;
  unlimitedMileage: boolean;
  freeCancellation: boolean;
  airportPickup: boolean;
  airConditioning: boolean;
  image: string;
  imageAlt: string;
}>;

export const demoCars: DemoCar[] = [
  {id:"toyota-yaris",brand:"Toyota",model:"Yaris",year:2026,category:"Economy",transmission:"Automatic",fuel:"Petrol",seats:5,bags:2,doors:4,dailyPrice:22,supplier:"Jordan Drive",supplierRating:8.9,deposit:100,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Toyota%20Yaris%20car?lock=101",imageAlt:"Toyota Yaris"},
  {id:"toyota-corolla",brand:"Toyota",model:"Corolla",year:2026,category:"Sedan",transmission:"Automatic",fuel:"Petrol",seats:5,bags:3,doors:4,dailyPrice:28,supplier:"Jordan Drive",supplierRating:9.1,deposit:120,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Toyota%20Corolla%20car?lock=102",imageAlt:"Toyota Corolla"},
  {id:"toyota-camry",brand:"Toyota",model:"Camry",year:2026,category:"Sedan",transmission:"Automatic",fuel:"Hybrid",seats:5,bags:3,doors:4,dailyPrice:42,supplier:"KeyCar Jordan",supplierRating:9.0,deposit:180,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Toyota%20Camry%20car?lock=103",imageAlt:"Toyota Camry"},
  {id:"toyota-rav4",brand:"Toyota",model:"RAV4",year:2026,category:"SUV",transmission:"Automatic",fuel:"Hybrid",seats:5,bags:4,doors:5,dailyPrice:49,supplier:"KeyCar Jordan",supplierRating:9.2,deposit:200,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Toyota%20RAV4%20car?lock=104",imageAlt:"Toyota RAV4"},
  {id:"toyota-prado",brand:"Toyota",model:"Land Cruiser Prado",year:2026,category:"SUV",transmission:"Automatic",fuel:"Petrol",seats:7,bags:5,doors:5,dailyPrice:88,supplier:"Desert Wheels",supplierRating:9.3,deposit:350,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Toyota%20Land%20Cruiser%20Prado%20car?lock=105",imageAlt:"Toyota Land Cruiser Prado"},
  {id:"toyota-hiace",brand:"Toyota",model:"Hiace",year:2025,category:"Van",transmission:"Automatic",fuel:"Diesel",seats:12,bags:8,doors:4,dailyPrice:82,supplier:"Amman Mobility",supplierRating:8.8,deposit:300,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Toyota%20Hiace%20car?lock=106",imageAlt:"Toyota Hiace"},
  {id:"hyundai-accent",brand:"Hyundai",model:"Accent",year:2026,category:"Economy",transmission:"Automatic",fuel:"Petrol",seats:5,bags:2,doors:4,dailyPrice:23,supplier:"Amman Mobility",supplierRating:8.7,deposit:100,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Hyundai%20Accent%20car?lock=107",imageAlt:"Hyundai Accent"},
  {id:"hyundai-elantra",brand:"Hyundai",model:"Elantra",year:2026,category:"Sedan",transmission:"Automatic",fuel:"Petrol",seats:5,bags:3,doors:4,dailyPrice:29,supplier:"Amman Mobility",supplierRating:8.9,deposit:120,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Hyundai%20Elantra%20car?lock=108",imageAlt:"Hyundai Elantra"},
  {id:"hyundai-tucson",brand:"Hyundai",model:"Tucson",year:2026,category:"SUV",transmission:"Automatic",fuel:"Hybrid",seats:5,bags:4,doors:5,dailyPrice:47,supplier:"Jordan Drive",supplierRating:9.1,deposit:180,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Hyundai%20Tucson%20car?lock=109",imageAlt:"Hyundai Tucson"},
  {id:"hyundai-santa-fe",brand:"Hyundai",model:"Santa Fe",year:2026,category:"SUV",transmission:"Automatic",fuel:"Hybrid",seats:7,bags:4,doors:5,dailyPrice:62,supplier:"Jordan Drive",supplierRating:9.0,deposit:240,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Hyundai%20Santa%20Fe%20car?lock=110",imageAlt:"Hyundai Santa Fe"},
  {id:"hyundai-staria",brand:"Hyundai",model:"Staria",year:2026,category:"Van",transmission:"Automatic",fuel:"Diesel",seats:9,bags:6,doors:5,dailyPrice:79,supplier:"Petra Rent",supplierRating:8.9,deposit:280,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Hyundai%20Staria%20car?lock=111",imageAlt:"Hyundai Staria"},
  {id:"kia-picanto",brand:"Kia",model:"Picanto",year:2026,category:"Economy",transmission:"Automatic",fuel:"Petrol",seats:4,bags:2,doors:5,dailyPrice:21,supplier:"Petra Rent",supplierRating:8.8,deposit:80,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Kia%20Picanto%20car?lock=112",imageAlt:"Kia Picanto"},
  {id:"kia-cerato",brand:"Kia",model:"Cerato",year:2026,category:"Sedan",transmission:"Automatic",fuel:"Petrol",seats:5,bags:3,doors:4,dailyPrice:27,supplier:"Petra Rent",supplierRating:8.9,deposit:110,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Kia%20Cerato%20car?lock=113",imageAlt:"Kia Cerato"},
  {id:"kia-sportage",brand:"Kia",model:"Sportage",year:2026,category:"SUV",transmission:"Automatic",fuel:"Hybrid",seats:5,bags:4,doors:5,dailyPrice:46,supplier:"KeyCar Jordan",supplierRating:9.2,deposit:180,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Kia%20Sportage%20car?lock=114",imageAlt:"Kia Sportage"},
  {id:"kia-sorento",brand:"Kia",model:"Sorento",year:2026,category:"SUV",transmission:"Automatic",fuel:"Hybrid",seats:7,bags:4,doors:5,dailyPrice:61,supplier:"KeyCar Jordan",supplierRating:9.1,deposit:240,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Kia%20Sorento%20car?lock=115",imageAlt:"Kia Sorento"},
  {id:"kia-carnival",brand:"Kia",model:"Carnival",year:2026,category:"Van",transmission:"Automatic",fuel:"Petrol",seats:8,bags:5,doors:5,dailyPrice:74,supplier:"Amman Mobility",supplierRating:8.9,deposit:260,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Kia%20Carnival%20car?lock=116",imageAlt:"Kia Carnival"},
  {id:"nissan-sunny",brand:"Nissan",model:"Sunny",year:2026,category:"Economy",transmission:"Automatic",fuel:"Petrol",seats:5,bags:2,doors:4,dailyPrice:22,supplier:"Jordan Drive",supplierRating:8.7,deposit:90,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Nissan%20Sunny%20car?lock=117",imageAlt:"Nissan Sunny"},
  {id:"nissan-sentra",brand:"Nissan",model:"Sentra",year:2026,category:"Sedan",transmission:"Automatic",fuel:"Petrol",seats:5,bags:3,doors:4,dailyPrice:28,supplier:"Jordan Drive",supplierRating:8.8,deposit:110,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Nissan%20Sentra%20car?lock=118",imageAlt:"Nissan Sentra"},
  {id:"nissan-xtrail",brand:"Nissan",model:"X-Trail",year:2026,category:"SUV",transmission:"Automatic",fuel:"Hybrid",seats:7,bags:4,doors:5,dailyPrice:52,supplier:"Desert Wheels",supplierRating:9.0,deposit:200,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Nissan%20X-Trail%20car?lock=119",imageAlt:"Nissan X-Trail"},
  {id:"nissan-patrol",brand:"Nissan",model:"Patrol",year:2026,category:"Luxury",transmission:"Automatic",fuel:"Petrol",seats:7,bags:5,doors:5,dailyPrice:105,supplier:"Desert Wheels",supplierRating:9.4,deposit:450,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Nissan%20Patrol%20car?lock=120",imageAlt:"Nissan Patrol"},
  {id:"mitsubishi-attrage",brand:"Mitsubishi",model:"Attrage",year:2025,category:"Economy",transmission:"Automatic",fuel:"Petrol",seats:5,bags:2,doors:4,dailyPrice:20,supplier:"Petra Rent",supplierRating:8.6,deposit:80,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Mitsubishi%20Attrage%20car?lock=121",imageAlt:"Mitsubishi Attrage"},
  {id:"mitsubishi-asx",brand:"Mitsubishi",model:"ASX",year:2025,category:"SUV",transmission:"Automatic",fuel:"Petrol",seats:5,bags:3,doors:5,dailyPrice:39,supplier:"Petra Rent",supplierRating:8.8,deposit:150,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Mitsubishi%20ASX%20car?lock=122",imageAlt:"Mitsubishi ASX"},
  {id:"mitsubishi-pajero-sport",brand:"Mitsubishi",model:"Pajero Sport",year:2025,category:"SUV",transmission:"Automatic",fuel:"Diesel",seats:7,bags:4,doors:5,dailyPrice:66,supplier:"Desert Wheels",supplierRating:9.0,deposit:250,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Mitsubishi%20Pajero%20Sport%20car?lock=123",imageAlt:"Mitsubishi Pajero Sport"},
  {id:"mitsubishi-l200",brand:"Mitsubishi",model:"L200",year:2025,category:"Pickup",transmission:"Automatic",fuel:"Diesel",seats:5,bags:2,doors:4,dailyPrice:58,supplier:"Desert Wheels",supplierRating:8.8,deposit:220,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Mitsubishi%20L200%20car?lock=124",imageAlt:"Mitsubishi L200"},
  {id:"ford-territory",brand:"Ford",model:"Territory",year:2026,category:"SUV",transmission:"Automatic",fuel:"Petrol",seats:5,bags:4,doors:5,dailyPrice:45,supplier:"KeyCar Jordan",supplierRating:8.9,deposit:170,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Ford%20Territory%20car?lock=125",imageAlt:"Ford Territory"},
  {id:"ford-everest",brand:"Ford",model:"Everest",year:2026,category:"SUV",transmission:"Automatic",fuel:"Diesel",seats:7,bags:4,doors:5,dailyPrice:69,supplier:"KeyCar Jordan",supplierRating:9.0,deposit:260,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Ford%20Everest%20car?lock=126",imageAlt:"Ford Everest"},
  {id:"ford-ranger",brand:"Ford",model:"Ranger",year:2026,category:"Pickup",transmission:"Automatic",fuel:"Diesel",seats:5,bags:2,doors:4,dailyPrice:64,supplier:"Desert Wheels",supplierRating:9.0,deposit:250,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Ford%20Ranger%20car?lock=127",imageAlt:"Ford Ranger"},
  {id:"ford-mustang",brand:"Ford",model:"Mustang",year:2026,category:"Luxury",transmission:"Automatic",fuel:"Petrol",seats:4,bags:2,doors:2,dailyPrice:118,supplier:"KeyCar Jordan",supplierRating:9.3,deposit:500,unlimitedMileage:false,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Ford%20Mustang%20car?lock=128",imageAlt:"Ford Mustang"},
  {id:"chevrolet-spark",brand:"Chevrolet",model:"Spark",year:2025,category:"Economy",transmission:"Automatic",fuel:"Petrol",seats:4,bags:2,doors:5,dailyPrice:19,supplier:"Amman Mobility",supplierRating:8.5,deposit:0,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Chevrolet%20Spark%20car?lock=129",imageAlt:"Chevrolet Spark"},
  {id:"chevrolet-captiva",brand:"Chevrolet",model:"Captiva",year:2026,category:"SUV",transmission:"Automatic",fuel:"Petrol",seats:7,bags:3,doors:5,dailyPrice:44,supplier:"Amman Mobility",supplierRating:8.8,deposit:160,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Chevrolet%20Captiva%20car?lock=130",imageAlt:"Chevrolet Captiva"},
  {id:"chevrolet-tahoe",brand:"Chevrolet",model:"Tahoe",year:2026,category:"Luxury",transmission:"Automatic",fuel:"Petrol",seats:7,bags:5,doors:5,dailyPrice:112,supplier:"Desert Wheels",supplierRating:9.2,deposit:450,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Chevrolet%20Tahoe%20car?lock=131",imageAlt:"Chevrolet Tahoe"},
  {id:"honda-city",brand:"Honda",model:"City",year:2026,category:"Sedan",transmission:"Automatic",fuel:"Petrol",seats:5,bags:3,doors:4,dailyPrice:27,supplier:"Jordan Drive",supplierRating:8.9,deposit:100,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Honda%20City%20car?lock=132",imageAlt:"Honda City"},
  {id:"honda-civic",brand:"Honda",model:"Civic",year:2026,category:"Sedan",transmission:"Automatic",fuel:"Hybrid",seats:5,bags:3,doors:4,dailyPrice:36,supplier:"Jordan Drive",supplierRating:9.0,deposit:130,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Honda%20Civic%20car?lock=133",imageAlt:"Honda Civic"},
  {id:"honda-crv",brand:"Honda",model:"CR-V",year:2026,category:"SUV",transmission:"Automatic",fuel:"Hybrid",seats:5,bags:4,doors:5,dailyPrice:51,supplier:"Jordan Drive",supplierRating:9.1,deposit:190,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Honda%20CR-V%20car?lock=134",imageAlt:"Honda CR-V"},
  {id:"mazda-3",brand:"Mazda",model:"3",year:2026,category:"Sedan",transmission:"Automatic",fuel:"Petrol",seats:5,bags:3,doors:4,dailyPrice:31,supplier:"Petra Rent",supplierRating:8.9,deposit:120,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Mazda%203%20car?lock=135",imageAlt:"Mazda 3"},
  {id:"mazda-cx5",brand:"Mazda",model:"CX-5",year:2026,category:"SUV",transmission:"Automatic",fuel:"Petrol",seats:5,bags:4,doors:5,dailyPrice:48,supplier:"Petra Rent",supplierRating:9.0,deposit:180,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Mazda%20CX-5%20car?lock=136",imageAlt:"Mazda CX-5"},
  {id:"vw-troc",brand:"Volkswagen",model:"T-Roc",year:2026,category:"Compact",transmission:"Automatic",fuel:"Petrol",seats:5,bags:3,doors:5,dailyPrice:43,supplier:"KeyCar Jordan",supplierRating:9.0,deposit:170,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Volkswagen%20T-Roc%20car?lock=137",imageAlt:"Volkswagen T-Roc"},
  {id:"vw-tiguan",brand:"Volkswagen",model:"Tiguan",year:2026,category:"SUV",transmission:"Automatic",fuel:"Petrol",seats:5,bags:4,doors:5,dailyPrice:54,supplier:"KeyCar Jordan",supplierRating:9.1,deposit:210,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Volkswagen%20Tiguan%20car?lock=138",imageAlt:"Volkswagen Tiguan"},
  {id:"bmw-320i",brand:"BMW",model:"320i",year:2026,category:"Luxury",transmission:"Automatic",fuel:"Petrol",seats:5,bags:3,doors:4,dailyPrice:82,supplier:"KeyCar Jordan",supplierRating:9.3,deposit:350,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/BMW%20320i%20car?lock=139",imageAlt:"BMW 320i"},
  {id:"bmw-x3",brand:"BMW",model:"X3",year:2026,category:"Luxury",transmission:"Automatic",fuel:"Petrol",seats:5,bags:4,doors:5,dailyPrice:99,supplier:"KeyCar Jordan",supplierRating:9.4,deposit:400,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/BMW%20X3%20car?lock=140",imageAlt:"BMW X3"},
  {id:"mercedes-c200",brand:"Mercedes-Benz",model:"C200",year:2026,category:"Luxury",transmission:"Automatic",fuel:"Petrol",seats:5,bags:3,doors:4,dailyPrice:89,supplier:"Desert Wheels",supplierRating:9.4,deposit:380,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Mercedes-Benz%20C200%20car?lock=141",imageAlt:"Mercedes-Benz C200"},
  {id:"mercedes-glc",brand:"Mercedes-Benz",model:"GLC",year:2026,category:"Luxury",transmission:"Automatic",fuel:"Petrol",seats:5,bags:4,doors:5,dailyPrice:108,supplier:"Desert Wheels",supplierRating:9.5,deposit:450,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Mercedes-Benz%20GLC%20car?lock=142",imageAlt:"Mercedes-Benz GLC"},
  {id:"audi-a4",brand:"Audi",model:"A4",year:2026,category:"Luxury",transmission:"Automatic",fuel:"Petrol",seats:5,bags:3,doors:4,dailyPrice:84,supplier:"KeyCar Jordan",supplierRating:9.3,deposit:360,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Audi%20A4%20car?lock=143",imageAlt:"Audi A4"},
  {id:"audi-q5",brand:"Audi",model:"Q5",year:2026,category:"Luxury",transmission:"Automatic",fuel:"Petrol",seats:5,bags:4,doors:5,dailyPrice:103,supplier:"KeyCar Jordan",supplierRating:9.4,deposit:420,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Audi%20Q5%20car?lock=144",imageAlt:"Audi Q5"},
  {id:"tesla-model-3",brand:"Tesla",model:"Model 3",year:2026,category:"Electric",transmission:"Automatic",fuel:"Electric",seats:5,bags:3,doors:4,dailyPrice:69,supplier:"Amman Mobility",supplierRating:9.2,deposit:0,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Tesla%20Model%203%20car?lock=145",imageAlt:"Tesla Model 3"},
  {id:"tesla-model-y",brand:"Tesla",model:"Model Y",year:2026,category:"Electric",transmission:"Automatic",fuel:"Electric",seats:5,bags:4,doors:5,dailyPrice:79,supplier:"Amman Mobility",supplierRating:9.3,deposit:0,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Tesla%20Model%20Y%20car?lock=146",imageAlt:"Tesla Model Y"},
  {id:"byd-atto-3",brand:"BYD",model:"Atto 3",year:2026,category:"Electric",transmission:"Automatic",fuel:"Electric",seats:5,bags:4,doors:5,dailyPrice:54,supplier:"Jordan Drive",supplierRating:9.0,deposit:0,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/BYD%20Atto%203%20car?lock=147",imageAlt:"BYD Atto 3"},
  {id:"mg-zs-ev",brand:"MG",model:"ZS EV",year:2026,category:"Electric",transmission:"Automatic",fuel:"Electric",seats:5,bags:3,doors:5,dailyPrice:49,supplier:"Petra Rent",supplierRating:8.9,deposit:0,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/MG%20ZS%20EV%20car?lock=148",imageAlt:"MG ZS EV"},
  {id:"geely-coolray",brand:"Geely",model:"Coolray",year:2026,category:"Compact",transmission:"Automatic",fuel:"Petrol",seats:5,bags:3,doors:5,dailyPrice:35,supplier:"Amman Mobility",supplierRating:8.8,deposit:120,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Geely%20Coolray%20car?lock=149",imageAlt:"Geely Coolray"},
  {id:"suzuki-swift",brand:"Suzuki",model:"Swift",year:2026,category:"Economy",transmission:"Automatic",fuel:"Petrol",seats:5,bags:2,doors:5,dailyPrice:21,supplier:"Petra Rent",supplierRating:8.7,deposit:80,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Suzuki%20Swift%20car?lock=150",imageAlt:"Suzuki Swift"},
  {id:"jeep-wrangler",brand:"Jeep",model:"Wrangler",year:2026,category:"SUV",transmission:"Automatic",fuel:"Petrol",seats:5,bags:3,doors:5,dailyPrice:92,supplier:"Desert Wheels",supplierRating:9.2,deposit:350,unlimitedMileage:false,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Jeep%20Wrangler%20car?lock=151",imageAlt:"Jeep Wrangler"},
  {id:"land-rover-defender",brand:"Land Rover",model:"Defender",year:2026,category:"Luxury",transmission:"Automatic",fuel:"Petrol",seats:5,bags:4,doors:5,dailyPrice:145,supplier:"Desert Wheels",supplierRating:9.5,deposit:600,unlimitedMileage:false,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Land%20Rover%20Defender%20car?lock=152",imageAlt:"Land Rover Defender"},
  {id:"lexus-es",brand:"Lexus",model:"ES 300h",year:2026,category:"Luxury",transmission:"Automatic",fuel:"Hybrid",seats:5,bags:3,doors:4,dailyPrice:96,supplier:"KeyCar Jordan",supplierRating:9.4,deposit:400,unlimitedMileage:true,freeCancellation:true,airportPickup:true,airConditioning:true,image:"https://loremflickr.com/1200/800/Lexus%20ES%20300h%20car?lock=153",imageAlt:"Lexus ES 300h"},
];
