import type {GuestLocale} from "./guest-market";

const COPY:Record<GuestLocale,Readonly<Record<string,string>>>={
  en:{AIR_CONDITIONING:"Air conditioning",FLAT_SCREEN_TV:"Flat-screen TV",SOUNDPROOFING:"Soundproofing",PRIVATE_ENTRANCE:"Private entrance",REFRIGERATOR:"Refrigerator",TEA_COFFEE:"Tea/coffee facilities",BALCONY:"Balcony",GARDEN_VIEW:"Garden view",POOL_VIEW:"Pool view",CITY_VIEW:"City view",KITCHENETTE:"Kitchenette",WIFI:"Wi-Fi",SAFE:"Safe",MINIBAR:"Minibar",DESK:"Desk",WASHING_MACHINE:"Washing machine",SEATING_AREA:"Seating area",SEA_VIEW:"Sea view",PRIVATE_POOL:"Private pool"},
  ar:{AIR_CONDITIONING:"تكييف",FLAT_SCREEN_TV:"تلفاز بشاشة مسطحة",SOUNDPROOFING:"عزل صوتي",PRIVATE_ENTRANCE:"مدخل خاص",REFRIGERATOR:"ثلاجة",TEA_COFFEE:"آلة شاي وقهوة",BALCONY:"شرفة",GARDEN_VIEW:"إطلالة على الحديقة",POOL_VIEW:"إطلالة على المسبح",CITY_VIEW:"إطلالة على المدينة",KITCHENETTE:"مطبخ صغير",WIFI:"واي فاي",SAFE:"خزنة",MINIBAR:"ميني بار",DESK:"مكتب",WASHING_MACHINE:"غسالة",SEATING_AREA:"منطقة جلوس",SEA_VIEW:"إطلالة بحرية",PRIVATE_POOL:"مسبح خاص"},
  zh:{AIR_CONDITIONING:"空调",FLAT_SCREEN_TV:"平板电视",SOUNDPROOFING:"隔音",PRIVATE_ENTRANCE:"私人入口",REFRIGERATOR:"冰箱",TEA_COFFEE:"茶/咖啡设施",BALCONY:"阳台",GARDEN_VIEW:"花园景",POOL_VIEW:"泳池景",CITY_VIEW:"城市景",KITCHENETTE:"小厨房",WIFI:"无线网络",SAFE:"保险箱",MINIBAR:"迷你吧",DESK:"书桌",WASHING_MACHINE:"洗衣机",SEATING_AREA:"休息区",SEA_VIEW:"海景",PRIVATE_POOL:"私人泳池"},
  fr:{AIR_CONDITIONING:"Climatisation",FLAT_SCREEN_TV:"Télévision à écran plat",SOUNDPROOFING:"Insonorisation",PRIVATE_ENTRANCE:"Entrée privée",REFRIGERATOR:"Réfrigérateur",TEA_COFFEE:"Plateau thé/café",BALCONY:"Balcon",GARDEN_VIEW:"Vue sur le jardin",POOL_VIEW:"Vue sur la piscine",CITY_VIEW:"Vue sur la ville",KITCHENETTE:"Kitchenette",WIFI:"Wi-Fi",SAFE:"Coffre-fort",MINIBAR:"Minibar",DESK:"Bureau",WASHING_MACHINE:"Lave-linge",SEATING_AREA:"Coin salon",SEA_VIEW:"Vue sur la mer",PRIVATE_POOL:"Piscine privée"},
  de:{AIR_CONDITIONING:"Klimaanlage",FLAT_SCREEN_TV:"Flachbild-TV",SOUNDPROOFING:"Schallisolierung",PRIVATE_ENTRANCE:"Privater Eingang",REFRIGERATOR:"Kühlschrank",TEA_COFFEE:"Tee-/Kaffeezubehör",BALCONY:"Balkon",GARDEN_VIEW:"Gartenblick",POOL_VIEW:"Poolblick",CITY_VIEW:"Stadtblick",KITCHENETTE:"Kochnische",WIFI:"WLAN",SAFE:"Safe",MINIBAR:"Minibar",DESK:"Schreibtisch",WASHING_MACHINE:"Waschmaschine",SEATING_AREA:"Sitzbereich",SEA_VIEW:"Meerblick",PRIVATE_POOL:"Privater Pool"},
  es:{AIR_CONDITIONING:"Aire acondicionado",FLAT_SCREEN_TV:"TV de pantalla plana",SOUNDPROOFING:"Insonorización",PRIVATE_ENTRANCE:"Entrada privada",REFRIGERATOR:"Nevera",TEA_COFFEE:"Té/café",BALCONY:"Balcón",GARDEN_VIEW:"Vista al jardín",POOL_VIEW:"Vista a la piscina",CITY_VIEW:"Vista a la ciudad",KITCHENETTE:"Zona de cocina",WIFI:"Wi-Fi",SAFE:"Caja fuerte",MINIBAR:"Minibar",DESK:"Escritorio",WASHING_MACHINE:"Lavadora",SEATING_AREA:"Zona de estar",SEA_VIEW:"Vista al mar",PRIVATE_POOL:"Piscina privada"},
  it:{AIR_CONDITIONING:"Aria condizionata",FLAT_SCREEN_TV:"TV a schermo piatto",SOUNDPROOFING:"Insonorizzazione",PRIVATE_ENTRANCE:"Ingresso privato",REFRIGERATOR:"Frigorifero",TEA_COFFEE:"Set per tè/caffè",BALCONY:"Balcone",GARDEN_VIEW:"Vista giardino",POOL_VIEW:"Vista piscina",CITY_VIEW:"Vista città",KITCHENETTE:"Angolo cottura",WIFI:"Wi-Fi",SAFE:"Cassaforte",MINIBAR:"Minibar",DESK:"Scrivania",WASHING_MACHINE:"Lavatrice",SEATING_AREA:"Area salotto",SEA_VIEW:"Vista mare",PRIVATE_POOL:"Piscina privata"},
  tr:{AIR_CONDITIONING:"Klima",FLAT_SCREEN_TV:"Düz ekran TV",SOUNDPROOFING:"Ses yalıtımı",PRIVATE_ENTRANCE:"Özel giriş",REFRIGERATOR:"Buzdolabı",TEA_COFFEE:"Çay/kahve olanakları",BALCONY:"Balkon",GARDEN_VIEW:"Bahçe manzarası",POOL_VIEW:"Havuz manzarası",CITY_VIEW:"Şehir manzarası",KITCHENETTE:"Mini mutfak",WIFI:"Wi-Fi",SAFE:"Kasa",MINIBAR:"Minibar",DESK:"Çalışma masası",WASHING_MACHINE:"Çamaşır makinesi",SEATING_AREA:"Oturma alanı",SEA_VIEW:"Deniz manzarası",PRIVATE_POOL:"Özel havuz"},
  ru:{AIR_CONDITIONING:"Кондиционер",FLAT_SCREEN_TV:"Телевизор с плоским экраном",SOUNDPROOFING:"Звукоизоляция",PRIVATE_ENTRANCE:"Отдельный вход",REFRIGERATOR:"Холодильник",TEA_COFFEE:"Чай/кофе",BALCONY:"Балкон",GARDEN_VIEW:"Вид на сад",POOL_VIEW:"Вид на бассейн",CITY_VIEW:"Вид на город",KITCHENETTE:"Мини-кухня",WIFI:"Wi-Fi",SAFE:"Сейф",MINIBAR:"Мини-бар",DESK:"Рабочий стол",WASHING_MACHINE:"Стиральная машина",SEATING_AREA:"Гостиная зона",SEA_VIEW:"Вид на море",PRIVATE_POOL:"Частный бассейн"},
  ja:{AIR_CONDITIONING:"エアコン",FLAT_SCREEN_TV:"薄型テレビ",SOUNDPROOFING:"防音",PRIVATE_ENTRANCE:"専用エントランス",REFRIGERATOR:"冷蔵庫",TEA_COFFEE:"紅茶・コーヒー設備",BALCONY:"バルコニー",GARDEN_VIEW:"ガーデンビュー",POOL_VIEW:"プールビュー",CITY_VIEW:"シティビュー",KITCHENETTE:"簡易キッチン",WIFI:"Wi-Fi",SAFE:"セーフティボックス",MINIBAR:"ミニバー",DESK:"デスク",WASHING_MACHINE:"洗濯機",SEATING_AREA:"シーティングエリア",SEA_VIEW:"シービュー",PRIVATE_POOL:"専用プール"},
  ko:{AIR_CONDITIONING:"에어컨",FLAT_SCREEN_TV:"평면 TV",SOUNDPROOFING:"방음",PRIVATE_ENTRANCE:"전용 출입구",REFRIGERATOR:"냉장고",TEA_COFFEE:"차/커피 시설",BALCONY:"발코니",GARDEN_VIEW:"정원 전망",POOL_VIEW:"수영장 전망",CITY_VIEW:"도시 전망",KITCHENETTE:"간이 주방",WIFI:"Wi-Fi",SAFE:"금고",MINIBAR:"미니바",DESK:"책상",WASHING_MACHINE:"세탁기",SEATING_AREA:"휴식 공간",SEA_VIEW:"바다 전망",PRIVATE_POOL:"전용 수영장"},
  hi:{AIR_CONDITIONING:"एयर कंडीशनिंग",FLAT_SCREEN_TV:"फ्लैट-स्क्रीन टीवी",SOUNDPROOFING:"साउंडप्रूफिंग",PRIVATE_ENTRANCE:"निजी प्रवेश",REFRIGERATOR:"रेफ्रिजरेटर",TEA_COFFEE:"चाय/कॉफी सुविधा",BALCONY:"बालकनी",GARDEN_VIEW:"बगीचे का दृश्य",POOL_VIEW:"पूल का दृश्य",CITY_VIEW:"शहर का दृश्य",KITCHENETTE:"किचनेट",WIFI:"वाई-फाई",SAFE:"तिजोरी",MINIBAR:"मिनीबार",DESK:"डेस्क",WASHING_MACHINE:"वॉशिंग मशीन",SEATING_AREA:"बैठने का क्षेत्र",SEA_VIEW:"समुद्र का दृश्य",PRIVATE_POOL:"निजी पूल"},
  pt:{AIR_CONDITIONING:"Ar-condicionado",FLAT_SCREEN_TV:"TV de tela plana",SOUNDPROOFING:"Isolamento acústico",PRIVATE_ENTRANCE:"Entrada privativa",REFRIGERATOR:"Geladeira",TEA_COFFEE:"Comodidades para chá/café",BALCONY:"Varanda",GARDEN_VIEW:"Vista para o jardim",POOL_VIEW:"Vista para a piscina",CITY_VIEW:"Vista da cidade",KITCHENETTE:"Cozinha compacta",WIFI:"Wi-Fi",SAFE:"Cofre",MINIBAR:"Frigobar",DESK:"Escrivaninha",WASHING_MACHINE:"Máquina de lavar",SEATING_AREA:"Área de estar",SEA_VIEW:"Vista para o mar",PRIVATE_POOL:"Piscina privativa"},
  id:{AIR_CONDITIONING:"AC",FLAT_SCREEN_TV:"TV layar datar",SOUNDPROOFING:"Kedap suara",PRIVATE_ENTRANCE:"Pintu masuk pribadi",REFRIGERATOR:"Kulkas",TEA_COFFEE:"Fasilitas teh/kopi",BALCONY:"Balkon",GARDEN_VIEW:"Pemandangan taman",POOL_VIEW:"Pemandangan kolam",CITY_VIEW:"Pemandangan kota",KITCHENETTE:"Dapur kecil",WIFI:"Wi-Fi",SAFE:"Brankas",MINIBAR:"Minibar",DESK:"Meja kerja",WASHING_MACHINE:"Mesin cuci",SEATING_AREA:"Area duduk",SEA_VIEW:"Pemandangan laut",PRIVATE_POOL:"Kolam renang pribadi"},
  th:{AIR_CONDITIONING:"เครื่องปรับอากาศ",FLAT_SCREEN_TV:"ทีวีจอแบน",SOUNDPROOFING:"เก็บเสียง",PRIVATE_ENTRANCE:"ทางเข้าส่วนตัว",REFRIGERATOR:"ตู้เย็น",TEA_COFFEE:"อุปกรณ์ชงชา/กาแฟ",BALCONY:"ระเบียง",GARDEN_VIEW:"วิวสวน",POOL_VIEW:"วิวสระว่ายน้ำ",CITY_VIEW:"วิวเมือง",KITCHENETTE:"ครัวขนาดเล็ก",WIFI:"Wi-Fi",SAFE:"ตู้นิรภัย",MINIBAR:"มินิบาร์",DESK:"โต๊ะทำงาน",WASHING_MACHINE:"เครื่องซักผ้า",SEATING_AREA:"พื้นที่นั่งเล่น",SEA_VIEW:"วิวทะเล",PRIVATE_POOL:"สระว่ายน้ำส่วนตัว"},
};

export function hotelRoomFacilityLabel(locale:GuestLocale,code:string,fallback:string):string{return COPY[locale][code]??fallback;}
