import type {GuestLocale} from "./guest-market";

type Copy=Readonly<{
  roomPhotoPending:string;fits:string;infants:string;crib:string;extraBed:string;privateBathroom:string;offerMeal:string;paymentBenefits:string;off:string;includes:string;bestLiveRate:string;guests:string;rateChoices:string;seeRoomsRates:string;learnRewards:string;bestPrice:string;flexible:string;mostIncluded:string;
  earnPoints:(points:string)=>string;rewardsPoints:(points:string)=>string;
}>;

const COPY:Record<GuestLocale,Copy>={
  en:{roomPhotoPending:"Room photo pending",fits:"Fits:",infants:"infants",crib:"Crib available on request",extraBed:"Extra bed on request",privateBathroom:"Private bathroom",offerMeal:"Offer & meal",paymentBenefits:"Payment & benefits",off:"off",includes:"Includes",bestLiveRate:"Best live rate available now",guests:"Guests",rateChoices:"Rate choices",seeRoomsRates:"See rooms & rates",learnRewards:"Learn about HandMeKey Rewards",bestPrice:"Best price",flexible:"Flexible",mostIncluded:"Most included",earnPoints:p=>`Earn at least ${p} HandMeKey points`,rewardsPoints:p=>`From ${p} Rewards points`},
  ar:{roomPhotoPending:"صورة الغرفة قيد الإضافة",fits:"تتسع:",infants:"رضّع",crib:"مهد متاح عند الطلب",extraBed:"سرير إضافي عند الطلب",privateBathroom:"حمام خاص",offerMeal:"العرض والوجبة",paymentBenefits:"الدفع والمزايا",off:"خصم",includes:"يشمل",bestLiveRate:"أفضل سعر مباشر متاح الآن",guests:"الضيوف",rateChoices:"خيارات الأسعار",seeRoomsRates:"شاهد الغرف والأسعار",learnRewards:"اعرف أكثر عن HandMeKey Rewards",bestPrice:"أفضل سعر",flexible:"مرن",mostIncluded:"إقامة شاملة",earnPoints:p=>`اكسب من ${p} نقطة HandMeKey`,rewardsPoints:p=>`من ${p} نقطة Rewards`},
  zh:{roomPhotoPending:"房型图片待上传",fits:"可住：",infants:"婴儿",crib:"可应要求提供婴儿床",extraBed:"可应要求提供加床",privateBathroom:"私人浴室",offerMeal:"优惠与餐食",paymentBenefits:"付款与权益",off:"优惠",includes:"包含",bestLiveRate:"当前最佳实时价格",guests:"住客",rateChoices:"价格方案",seeRoomsRates:"查看房型和价格",learnRewards:"了解 HandMeKey Rewards",bestPrice:"最佳价格",flexible:"灵活",mostIncluded:"包含更多",earnPoints:p=>`至少赚取 ${p} HandMeKey 积分`,rewardsPoints:p=>`至少 ${p} Rewards 积分`},
  fr:{roomPhotoPending:"Photo de la chambre en attente",fits:"Capacité :",infants:"bébés",crib:"Lit bébé disponible sur demande",extraBed:"Lit d’appoint sur demande",privateBathroom:"Salle de bains privative",offerMeal:"Offre et repas",paymentBenefits:"Paiement et avantages",off:"de réduction",includes:"Comprend",bestLiveRate:"Meilleur tarif en direct disponible",guests:"Voyageurs",rateChoices:"Choix de tarifs",seeRoomsRates:"Voir chambres et tarifs",learnRewards:"Découvrir HandMeKey Rewards",bestPrice:"Meilleur prix",flexible:"Flexible",mostIncluded:"Le plus inclus",earnPoints:p=>`Gagnez au moins ${p} points HandMeKey`,rewardsPoints:p=>`À partir de ${p} points Rewards`},
  de:{roomPhotoPending:"Zimmerfoto folgt",fits:"Geeignet für:",infants:"Kleinkinder",crib:"Babybett auf Anfrage",extraBed:"Zustellbett auf Anfrage",privateBathroom:"Eigenes Bad",offerMeal:"Angebot & Verpflegung",paymentBenefits:"Zahlung & Vorteile",off:"Rabatt",includes:"Enthält",bestLiveRate:"Bester aktuell verfügbarer Live-Preis",guests:"Gäste",rateChoices:"Tarifoptionen",seeRoomsRates:"Zimmer & Preise ansehen",learnRewards:"Mehr über HandMeKey Rewards",bestPrice:"Bester Preis",flexible:"Flexibel",mostIncluded:"Meiste Leistungen",earnPoints:p=>`Mindestens ${p} HandMeKey-Punkte sammeln`,rewardsPoints:p=>`Ab ${p} Rewards-Punkten`},
  es:{roomPhotoPending:"Foto de la habitación pendiente",fits:"Capacidad:",infants:"bebés",crib:"Cuna disponible bajo petición",extraBed:"Cama supletoria bajo petición",privateBathroom:"Baño privado",offerMeal:"Oferta y comida",paymentBenefits:"Pago y ventajas",off:"de descuento",includes:"Incluye",bestLiveRate:"Mejor tarifa en vivo disponible ahora",guests:"Huéspedes",rateChoices:"Opciones de tarifa",seeRoomsRates:"Ver habitaciones y tarifas",learnRewards:"Conoce HandMeKey Rewards",bestPrice:"Mejor precio",flexible:"Flexible",mostIncluded:"Más incluido",earnPoints:p=>`Gana al menos ${p} puntos HandMeKey`,rewardsPoints:p=>`Desde ${p} puntos Rewards`},
  it:{roomPhotoPending:"Foto della camera in arrivo",fits:"Ospita:",infants:"neonati",crib:"Culla disponibile su richiesta",extraBed:"Letto extra su richiesta",privateBathroom:"Bagno privato",offerMeal:"Offerta e pasti",paymentBenefits:"Pagamento e vantaggi",off:"di sconto",includes:"Include",bestLiveRate:"Migliore tariffa live disponibile ora",guests:"Ospiti",rateChoices:"Opzioni tariffarie",seeRoomsRates:"Vedi camere e tariffe",learnRewards:"Scopri HandMeKey Rewards",bestPrice:"Miglior prezzo",flexible:"Flessibile",mostIncluded:"Più servizi inclusi",earnPoints:p=>`Guadagna almeno ${p} punti HandMeKey`,rewardsPoints:p=>`Da ${p} punti Rewards`},
  tr:{roomPhotoPending:"Oda fotoğrafı bekleniyor",fits:"Kapasite:",infants:"bebek",crib:"Talep üzerine bebek yatağı",extraBed:"Talep üzerine ilave yatak",privateBathroom:"Özel banyo",offerMeal:"Teklif ve yemek",paymentBenefits:"Ödeme ve avantajlar",off:"indirim",includes:"Dahil",bestLiveRate:"Şu an mevcut en iyi canlı fiyat",guests:"Misafirler",rateChoices:"Fiyat seçenekleri",seeRoomsRates:"Odaları ve fiyatları gör",learnRewards:"HandMeKey Rewards hakkında bilgi alın",bestPrice:"En iyi fiyat",flexible:"Esnek",mostIncluded:"En çok dahil",earnPoints:p=>`En az ${p} HandMeKey puanı kazanın`,rewardsPoints:p=>`${p} Rewards puanından`},
  ru:{roomPhotoPending:"Фото номера скоро появится",fits:"Вмещает:",infants:"младенцы",crib:"Детская кроватка по запросу",extraBed:"Дополнительная кровать по запросу",privateBathroom:"Собственная ванная",offerMeal:"Предложение и питание",paymentBenefits:"Оплата и преимущества",off:"скидка",includes:"Включено",bestLiveRate:"Лучший актуальный тариф сейчас",guests:"Гости",rateChoices:"Варианты тарифов",seeRoomsRates:"Посмотреть номера и тарифы",learnRewards:"Подробнее о HandMeKey Rewards",bestPrice:"Лучшая цена",flexible:"Гибкий",mostIncluded:"Больше включено",earnPoints:p=>`Получите не менее ${p} баллов HandMeKey`,rewardsPoints:p=>`От ${p} баллов Rewards`},
  ja:{roomPhotoPending:"客室写真は準備中です",fits:"定員：",infants:"乳幼児",crib:"ベビーベッドはリクエスト可",extraBed:"エキストラベッドはリクエスト可",privateBathroom:"専用バスルーム",offerMeal:"プラン・食事",paymentBenefits:"支払い・特典",off:"割引",includes:"含まれるもの",bestLiveRate:"現在利用可能なベストライブ料金",guests:"宿泊者",rateChoices:"料金プラン",seeRoomsRates:"客室と料金を見る",learnRewards:"HandMeKey Rewardsについて",bestPrice:"ベスト価格",flexible:"柔軟",mostIncluded:"特典充実",earnPoints:p=>`少なくとも ${p} HandMeKeyポイント獲得`,rewardsPoints:p=>`${p} Rewardsポイントから`},
  ko:{roomPhotoPending:"객실 사진 준비 중",fits:"정원:",infants:"유아",crib:"요청 시 유아용 침대 제공",extraBed:"요청 시 엑스트라 베드 제공",privateBathroom:"전용 욕실",offerMeal:"상품 및 식사",paymentBenefits:"결제 및 혜택",off:"할인",includes:"포함",bestLiveRate:"현재 이용 가능한 최저 실시간 요금",guests:"투숙객",rateChoices:"요금 선택",seeRoomsRates:"객실 및 요금 보기",learnRewards:"HandMeKey Rewards 알아보기",bestPrice:"최저가",flexible:"유연함",mostIncluded:"혜택 최다",earnPoints:p=>`최소 ${p} HandMeKey 포인트 적립`,rewardsPoints:p=>`${p} Rewards 포인트부터`},
  hi:{roomPhotoPending:"कमरे की फ़ोटो जल्द आएगी",fits:"क्षमता:",infants:"शिशु",crib:"अनुरोध पर बेबी कॉट",extraBed:"अनुरोध पर अतिरिक्त बिस्तर",privateBathroom:"निजी बाथरूम",offerMeal:"ऑफ़र और भोजन",paymentBenefits:"भुगतान और लाभ",off:"छूट",includes:"शामिल",bestLiveRate:"अभी उपलब्ध सर्वोत्तम लाइव रेट",guests:"मेहमान",rateChoices:"रेट विकल्प",seeRoomsRates:"कमरे और रेट देखें",learnRewards:"HandMeKey Rewards के बारे में जानें",bestPrice:"सर्वोत्तम कीमत",flexible:"लचीला",mostIncluded:"सबसे अधिक शामिल",earnPoints:p=>`कम से कम ${p} HandMeKey पॉइंट कमाएँ`,rewardsPoints:p=>`${p} Rewards पॉइंट से`},
  pt:{roomPhotoPending:"Foto do quarto em breve",fits:"Capacidade:",infants:"bebês",crib:"Berço disponível mediante solicitação",extraBed:"Cama extra mediante solicitação",privateBathroom:"Banheiro privativo",offerMeal:"Oferta e refeição",paymentBenefits:"Pagamento e benefícios",off:"de desconto",includes:"Inclui",bestLiveRate:"Melhor tarifa ao vivo disponível agora",guests:"Hóspedes",rateChoices:"Opções de tarifa",seeRoomsRates:"Ver quartos e tarifas",learnRewards:"Saiba mais sobre HandMeKey Rewards",bestPrice:"Melhor preço",flexible:"Flexível",mostIncluded:"Mais benefícios incluídos",earnPoints:p=>`Ganhe pelo menos ${p} pontos HandMeKey`,rewardsPoints:p=>`A partir de ${p} pontos Rewards`},
  id:{roomPhotoPending:"Foto kamar segera tersedia",fits:"Kapasitas:",infants:"bayi",crib:"Ranjang bayi tersedia atas permintaan",extraBed:"Tempat tidur tambahan atas permintaan",privateBathroom:"Kamar mandi pribadi",offerMeal:"Penawaran & makanan",paymentBenefits:"Pembayaran & manfaat",off:"diskon",includes:"Termasuk",bestLiveRate:"Harga live terbaik yang tersedia saat ini",guests:"Tamu",rateChoices:"Pilihan harga",seeRoomsRates:"Lihat kamar & harga",learnRewards:"Pelajari HandMeKey Rewards",bestPrice:"Harga terbaik",flexible:"Fleksibel",mostIncluded:"Paling banyak termasuk",earnPoints:p=>`Dapatkan setidaknya ${p} poin HandMeKey`,rewardsPoints:p=>`Mulai ${p} poin Rewards`},
  th:{roomPhotoPending:"รูปห้องพักกำลังมา",fits:"รองรับ:",infants:"ทารก",crib:"มีเตียงเด็กเมื่อแจ้งขอ",extraBed:"มีเตียงเสริมเมื่อแจ้งขอ",privateBathroom:"ห้องน้ำส่วนตัว",offerMeal:"ข้อเสนอและอาหาร",paymentBenefits:"การชำระเงินและสิทธิประโยชน์",off:"ส่วนลด",includes:"รวม",bestLiveRate:"ราคาสดที่ดีที่สุดในขณะนี้",guests:"ผู้เข้าพัก",rateChoices:"ตัวเลือกราคา",seeRoomsRates:"ดูห้องและราคา",learnRewards:"เรียนรู้เกี่ยวกับ HandMeKey Rewards",bestPrice:"ราคาดีที่สุด",flexible:"ยืดหยุ่น",mostIncluded:"รวมมากที่สุด",earnPoints:p=>`รับอย่างน้อย ${p} คะแนน HandMeKey`,rewardsPoints:p=>`เริ่มจาก ${p} คะแนน Rewards`},
};

const BED:Record<GuestLocale,Readonly<Record<string,string>>>={
  en:{SINGLE:"single bed",DOUBLE:"double bed",QUEEN:"queen bed",KING:"king bed",EXTRA_LARGE_DOUBLE:"extra-large double bed",SOFA_BED:"sofa bed",BUNK_BED:"bunk bed",FUTON:"futon bed",MURPHY_BED:"Murphy bed"},
  ar:{SINGLE:"سرير فردي",DOUBLE:"سرير مزدوج",QUEEN:"سرير كوين",KING:"سرير كينغ",EXTRA_LARGE_DOUBLE:"سرير مزدوج كبير جدًا",SOFA_BED:"سرير أريكة",BUNK_BED:"سرير بطابقين",FUTON:"سرير فوتون",MURPHY_BED:"سرير جداري"},
  zh:{SINGLE:"单人床",DOUBLE:"双人床",QUEEN:"大床",KING:"特大床",EXTRA_LARGE_DOUBLE:"超大双人床",SOFA_BED:"沙发床",BUNK_BED:"双层床",FUTON:"日式床垫",MURPHY_BED:"壁床"},
  fr:{SINGLE:"lit simple",DOUBLE:"lit double",QUEEN:"lit queen-size",KING:"lit king-size",EXTRA_LARGE_DOUBLE:"très grand lit double",SOFA_BED:"canapé-lit",BUNK_BED:"lit superposé",FUTON:"futon",MURPHY_BED:"lit escamotable"},
  de:{SINGLE:"Einzelbett",DOUBLE:"Doppelbett",QUEEN:"Queensize-Bett",KING:"Kingsize-Bett",EXTRA_LARGE_DOUBLE:"extra großes Doppelbett",SOFA_BED:"Schlafsofa",BUNK_BED:"Etagenbett",FUTON:"Futonbett",MURPHY_BED:"Schrankbett"},
  es:{SINGLE:"cama individual",DOUBLE:"cama doble",QUEEN:"cama queen",KING:"cama king",EXTRA_LARGE_DOUBLE:"cama doble extragrande",SOFA_BED:"sofá cama",BUNK_BED:"litera",FUTON:"futón",MURPHY_BED:"cama abatible"},
  it:{SINGLE:"letto singolo",DOUBLE:"letto matrimoniale",QUEEN:"letto queen",KING:"letto king",EXTRA_LARGE_DOUBLE:"letto matrimoniale extra-large",SOFA_BED:"divano letto",BUNK_BED:"letto a castello",FUTON:"futon",MURPHY_BED:"letto a scomparsa"},
  tr:{SINGLE:"tek kişilik yatak",DOUBLE:"çift kişilik yatak",QUEEN:"queen yatak",KING:"king yatak",EXTRA_LARGE_DOUBLE:"ekstra büyük çift kişilik yatak",SOFA_BED:"çekyat",BUNK_BED:"ranza",FUTON:"futon yatak",MURPHY_BED:"duvar yatağı"},
  ru:{SINGLE:"односпальная кровать",DOUBLE:"двуспальная кровать",QUEEN:"кровать queen-size",KING:"кровать king-size",EXTRA_LARGE_DOUBLE:"очень большая двуспальная кровать",SOFA_BED:"диван-кровать",BUNK_BED:"двухъярусная кровать",FUTON:"футон",MURPHY_BED:"откидная кровать"},
  ja:{SINGLE:"シングルベッド",DOUBLE:"ダブルベッド",QUEEN:"クイーンベッド",KING:"キングベッド",EXTRA_LARGE_DOUBLE:"特大ダブルベッド",SOFA_BED:"ソファベッド",BUNK_BED:"二段ベッド",FUTON:"布団",MURPHY_BED:"収納式ベッド"},
  ko:{SINGLE:"싱글 침대",DOUBLE:"더블 침대",QUEEN:"퀸 침대",KING:"킹 침대",EXTRA_LARGE_DOUBLE:"엑스트라 라지 더블 침대",SOFA_BED:"소파 베드",BUNK_BED:"이층 침대",FUTON:"요이불",MURPHY_BED:"벽장 침대"},
  hi:{SINGLE:"सिंगल बेड",DOUBLE:"डबल बेड",QUEEN:"क्वीन बेड",KING:"किंग बेड",EXTRA_LARGE_DOUBLE:"अतिरिक्त बड़ा डबल बेड",SOFA_BED:"सोफ़ा बेड",BUNK_BED:"बंक बेड",FUTON:"फ्यूटन बेड",MURPHY_BED:"मर्फी बेड"},
  pt:{SINGLE:"cama de solteiro",DOUBLE:"cama de casal",QUEEN:"cama queen",KING:"cama king",EXTRA_LARGE_DOUBLE:"cama de casal extragrande",SOFA_BED:"sofá-cama",BUNK_BED:"beliche",FUTON:"futon",MURPHY_BED:"cama retrátil"},
  id:{SINGLE:"tempat tidur single",DOUBLE:"tempat tidur double",QUEEN:"tempat tidur queen",KING:"tempat tidur king",EXTRA_LARGE_DOUBLE:"tempat tidur double ekstra besar",SOFA_BED:"sofa bed",BUNK_BED:"tempat tidur susun",FUTON:"futon",MURPHY_BED:"tempat tidur lipat dinding"},
  th:{SINGLE:"เตียงเดี่ยว",DOUBLE:"เตียงคู่",QUEEN:"เตียงควีน",KING:"เตียงคิง",EXTRA_LARGE_DOUBLE:"เตียงคู่ขนาดใหญ่พิเศษ",SOFA_BED:"โซฟาเบด",BUNK_BED:"เตียงสองชั้น",FUTON:"ฟูกญี่ปุ่น",MURPHY_BED:"เตียงพับติดผนัง"},
};

const UNIT:Record<GuestLocale,Readonly<Record<string,string>>>={
  en:{ROOM:"Room",STUDIO:"Entire studio",SUITE:"Suite",APARTMENT:"Entire apartment",VILLA:"Villa",CHALET:"Chalet",BUNGALOW:"Bungalow",HOLIDAY_HOME:"Holiday home",DORMITORY_ROOM:"Dormitory room",BED_IN_DORMITORY:"Bed in dormitory"},
  ar:{ROOM:"غرفة",STUDIO:"استوديو كامل",SUITE:"جناح",APARTMENT:"شقة كاملة",VILLA:"فيلا",CHALET:"شاليه",BUNGALOW:"بنغلو",HOLIDAY_HOME:"بيت عطلات",DORMITORY_ROOM:"غرفة مشتركة",BED_IN_DORMITORY:"سرير في غرفة مشتركة"},
  zh:{ROOM:"客房",STUDIO:"整套单间",SUITE:"套房",APARTMENT:"整套公寓",VILLA:"别墅",CHALET:"木屋",BUNGALOW:"平房",HOLIDAY_HOME:"度假屋",DORMITORY_ROOM:"宿舍间",BED_IN_DORMITORY:"宿舍床位"},
  fr:{ROOM:"Chambre",STUDIO:"Studio entier",SUITE:"Suite",APARTMENT:"Appartement entier",VILLA:"Villa",CHALET:"Chalet",BUNGALOW:"Bungalow",HOLIDAY_HOME:"Maison de vacances",DORMITORY_ROOM:"Dortoir",BED_IN_DORMITORY:"Lit en dortoir"},
  de:{ROOM:"Zimmer",STUDIO:"Ganzes Studio",SUITE:"Suite",APARTMENT:"Ganze Wohnung",VILLA:"Villa",CHALET:"Chalet",BUNGALOW:"Bungalow",HOLIDAY_HOME:"Ferienhaus",DORMITORY_ROOM:"Schlafsaal",BED_IN_DORMITORY:"Bett im Schlafsaal"},
  es:{ROOM:"Habitación",STUDIO:"Estudio entero",SUITE:"Suite",APARTMENT:"Apartamento entero",VILLA:"Villa",CHALET:"Chalet",BUNGALOW:"Bungalow",HOLIDAY_HOME:"Casa vacacional",DORMITORY_ROOM:"Dormitorio compartido",BED_IN_DORMITORY:"Cama en dormitorio"},
  it:{ROOM:"Camera",STUDIO:"Intero monolocale",SUITE:"Suite",APARTMENT:"Intero appartamento",VILLA:"Villa",CHALET:"Chalet",BUNGALOW:"Bungalow",HOLIDAY_HOME:"Casa vacanze",DORMITORY_ROOM:"Dormitorio",BED_IN_DORMITORY:"Letto in dormitorio"},
  tr:{ROOM:"Oda",STUDIO:"Tüm stüdyo",SUITE:"Süit",APARTMENT:"Tüm daire",VILLA:"Villa",CHALET:"Dağ evi",BUNGALOW:"Bungalov",HOLIDAY_HOME:"Tatil evi",DORMITORY_ROOM:"Yatakhane odası",BED_IN_DORMITORY:"Yatakhanede yatak"},
  ru:{ROOM:"Номер",STUDIO:"Студия целиком",SUITE:"Люкс",APARTMENT:"Апартаменты целиком",VILLA:"Вилла",CHALET:"Шале",BUNGALOW:"Бунгало",HOLIDAY_HOME:"Дом для отпуска",DORMITORY_ROOM:"Общий номер",BED_IN_DORMITORY:"Кровать в общем номере"},
  ja:{ROOM:"客室",STUDIO:"スタジオ貸切",SUITE:"スイート",APARTMENT:"アパートメント貸切",VILLA:"ヴィラ",CHALET:"シャレー",BUNGALOW:"バンガロー",HOLIDAY_HOME:"別荘",DORMITORY_ROOM:"ドミトリールーム",BED_IN_DORMITORY:"ドミトリーのベッド"},
  ko:{ROOM:"객실",STUDIO:"스튜디오 전체",SUITE:"스위트",APARTMENT:"아파트 전체",VILLA:"빌라",CHALET:"샬레",BUNGALOW:"방갈로",HOLIDAY_HOME:"홀리데이 홈",DORMITORY_ROOM:"도미토리 객실",BED_IN_DORMITORY:"도미토리 침대"},
  hi:{ROOM:"कमरा",STUDIO:"पूरा स्टूडियो",SUITE:"सुइट",APARTMENT:"पूरा अपार्टमेंट",VILLA:"विला",CHALET:"शैले",BUNGALOW:"बंगला",HOLIDAY_HOME:"हॉलिडे होम",DORMITORY_ROOM:"डॉर्मिटरी कमरा",BED_IN_DORMITORY:"डॉर्मिटरी में बेड"},
  pt:{ROOM:"Quarto",STUDIO:"Estúdio inteiro",SUITE:"Suíte",APARTMENT:"Apartamento inteiro",VILLA:"Villa",CHALET:"Chalé",BUNGALOW:"Bangalô",HOLIDAY_HOME:"Casa de temporada",DORMITORY_ROOM:"Dormitório",BED_IN_DORMITORY:"Cama em dormitório"},
  id:{ROOM:"Kamar",STUDIO:"Seluruh studio",SUITE:"Suite",APARTMENT:"Seluruh apartemen",VILLA:"Vila",CHALET:"Chalet",BUNGALOW:"Bungalo",HOLIDAY_HOME:"Rumah liburan",DORMITORY_ROOM:"Kamar asrama",BED_IN_DORMITORY:"Tempat tidur di asrama"},
  th:{ROOM:"ห้องพัก",STUDIO:"สตูดิโอทั้งห้อง",SUITE:"ห้องสวีท",APARTMENT:"อพาร์ตเมนต์ทั้งห้อง",VILLA:"วิลลา",CHALET:"ชาเลต์",BUNGALOW:"บังกะโล",HOLIDAY_HOME:"บ้านพักตากอากาศ",DORMITORY_ROOM:"ห้องพักรวม",BED_IN_DORMITORY:"เตียงในห้องพักรวม"},
};

export function hotelRoomUiCopy(locale:GuestLocale):Copy{return COPY[locale];}
export function hotelBedLabel(locale:GuestLocale,value:string):string{return BED[locale][value]??value;}
export function hotelUnitTypeLabel(locale:GuestLocale,value:string):string{return UNIT[locale][value]??value;}
export function hotelBedAreaLabel(locale:GuestLocale,value:string):string{
  const bedroom=/^bedroom\s*(\d+)?$/i.exec(value.trim());
  const living=/^living room$/i.test(value.trim());
  const names:Record<GuestLocale,{bedroom:string;living:string}>={en:{bedroom:"Bedroom",living:"Living room"},ar:{bedroom:"غرفة النوم",living:"غرفة المعيشة"},zh:{bedroom:"卧室",living:"客厅"},fr:{bedroom:"Chambre",living:"Salon"},de:{bedroom:"Schlafzimmer",living:"Wohnzimmer"},es:{bedroom:"Dormitorio",living:"Sala de estar"},it:{bedroom:"Camera da letto",living:"Soggiorno"},tr:{bedroom:"Yatak odası",living:"Oturma odası"},ru:{bedroom:"Спальня",living:"Гостиная"},ja:{bedroom:"ベッドルーム",living:"リビングルーム"},ko:{bedroom:"침실",living:"거실"},hi:{bedroom:"बेडरूम",living:"लिविंग रूम"},pt:{bedroom:"Quarto",living:"Sala de estar"},id:{bedroom:"Kamar tidur",living:"Ruang tamu"},th:{bedroom:"ห้องนอน",living:"ห้องนั่งเล่น"}};
  if(bedroom)return bedroom[1]?`${names[locale].bedroom} ${bedroom[1]}`:names[locale].bedroom;
  if(living)return names[locale].living;
  return value;
}
