import type {GuestLocale} from "./guest-market";

const COPY:Record<GuestLocale,Readonly<Record<string,string>>>={
  en:{WIFI:"Free Wi-Fi",BREAKFAST:"Breakfast",PARKING:"Parking",GYM:"Fitness centre",POOL:"Pool",SPA:"Spa",AIRPORT_SHUTTLE:"Airport shuttle",FAMILY_ROOMS:"Family rooms",BUSINESS_CENTER:"Business centre",RESTAURANT:"Restaurant",ROOM_SERVICE:"Room service",ROOFTOP:"Rooftop terrace",PLAY_AREA:"Children’s play area",BEACH_SHUTTLE:"Beach shuttle",BEACH_ACCESS:"Beach access",MARINA:"Marina access",WATER_SPORTS:"Water sports",TERRACE:"Terrace"},
  ar:{WIFI:"واي فاي مجاني",BREAKFAST:"إفطار",PARKING:"موقف سيارات",GYM:"مركز لياقة بدنية",POOL:"مسبح",SPA:"سبا",AIRPORT_SHUTTLE:"تنقلات المطار",FAMILY_ROOMS:"غرف عائلية",BUSINESS_CENTER:"مركز أعمال",RESTAURANT:"مطعم",ROOM_SERVICE:"خدمة الغرف",ROOFTOP:"تراس على السطح",PLAY_AREA:"منطقة ألعاب للأطفال",BEACH_SHUTTLE:"نقل إلى الشاطئ",BEACH_ACCESS:"وصول إلى الشاطئ",MARINA:"وصول إلى المارينا",WATER_SPORTS:"رياضات مائية",TERRACE:"تراس"},
  zh:{WIFI:"免费无线网络",BREAKFAST:"早餐",PARKING:"停车场",GYM:"健身中心",POOL:"游泳池",SPA:"水疗中心",AIRPORT_SHUTTLE:"机场接送",FAMILY_ROOMS:"家庭房",BUSINESS_CENTER:"商务中心",RESTAURANT:"餐厅",ROOM_SERVICE:"客房服务",ROOFTOP:"屋顶露台",PLAY_AREA:"儿童游乐区",BEACH_SHUTTLE:"海滩班车",BEACH_ACCESS:"海滩通道",MARINA:"码头通道",WATER_SPORTS:"水上运动",TERRACE:"露台"},
  fr:{WIFI:"Wi-Fi gratuit",BREAKFAST:"Petit-déjeuner",PARKING:"Parking",GYM:"Salle de sport",POOL:"Piscine",SPA:"Spa",AIRPORT_SHUTTLE:"Navette aéroport",FAMILY_ROOMS:"Chambres familiales",BUSINESS_CENTER:"Centre d’affaires",RESTAURANT:"Restaurant",ROOM_SERVICE:"Service en chambre",ROOFTOP:"Terrasse sur le toit",PLAY_AREA:"Aire de jeux pour enfants",BEACH_SHUTTLE:"Navette plage",BEACH_ACCESS:"Accès à la plage",MARINA:"Accès à la marina",WATER_SPORTS:"Sports nautiques",TERRACE:"Terrasse"},
  de:{WIFI:"Kostenloses WLAN",BREAKFAST:"Frühstück",PARKING:"Parkplatz",GYM:"Fitnesscenter",POOL:"Pool",SPA:"Spa",AIRPORT_SHUTTLE:"Flughafentransfer",FAMILY_ROOMS:"Familienzimmer",BUSINESS_CENTER:"Businesscenter",RESTAURANT:"Restaurant",ROOM_SERVICE:"Zimmerservice",ROOFTOP:"Dachterrasse",PLAY_AREA:"Kinderspielbereich",BEACH_SHUTTLE:"Strandshuttle",BEACH_ACCESS:"Strandzugang",MARINA:"Marinazugang",WATER_SPORTS:"Wassersport",TERRACE:"Terrasse"},
  es:{WIFI:"Wi-Fi gratis",BREAKFAST:"Desayuno",PARKING:"Aparcamiento",GYM:"Gimnasio",POOL:"Piscina",SPA:"Spa",AIRPORT_SHUTTLE:"Traslado al aeropuerto",FAMILY_ROOMS:"Habitaciones familiares",BUSINESS_CENTER:"Centro de negocios",RESTAURANT:"Restaurante",ROOM_SERVICE:"Servicio de habitaciones",ROOFTOP:"Terraza en la azotea",PLAY_AREA:"Zona de juegos infantil",BEACH_SHUTTLE:"Traslado a la playa",BEACH_ACCESS:"Acceso a la playa",MARINA:"Acceso al puerto deportivo",WATER_SPORTS:"Deportes acuáticos",TERRACE:"Terraza"},
  it:{WIFI:"Wi-Fi gratuito",BREAKFAST:"Colazione",PARKING:"Parcheggio",GYM:"Centro fitness",POOL:"Piscina",SPA:"Spa",AIRPORT_SHUTTLE:"Navetta aeroportuale",FAMILY_ROOMS:"Camere familiari",BUSINESS_CENTER:"Centro business",RESTAURANT:"Ristorante",ROOM_SERVICE:"Servizio in camera",ROOFTOP:"Terrazza sul tetto",PLAY_AREA:"Area giochi per bambini",BEACH_SHUTTLE:"Navetta spiaggia",BEACH_ACCESS:"Accesso alla spiaggia",MARINA:"Accesso al porto turistico",WATER_SPORTS:"Sport acquatici",TERRACE:"Terrazza"},
  tr:{WIFI:"Ücretsiz Wi-Fi",BREAKFAST:"Kahvaltı",PARKING:"Otopark",GYM:"Fitness merkezi",POOL:"Havuz",SPA:"Spa",AIRPORT_SHUTTLE:"Havaalanı servisi",FAMILY_ROOMS:"Aile odaları",BUSINESS_CENTER:"İş merkezi",RESTAURANT:"Restoran",ROOM_SERVICE:"Oda servisi",ROOFTOP:"Çatı terası",PLAY_AREA:"Çocuk oyun alanı",BEACH_SHUTTLE:"Plaj servisi",BEACH_ACCESS:"Plaj erişimi",MARINA:"Marina erişimi",WATER_SPORTS:"Su sporları",TERRACE:"Teras"},
  ru:{WIFI:"Бесплатный Wi-Fi",BREAKFAST:"Завтрак",PARKING:"Парковка",GYM:"Фитнес-центр",POOL:"Бассейн",SPA:"Спа",AIRPORT_SHUTTLE:"Трансфер из аэропорта",FAMILY_ROOMS:"Семейные номера",BUSINESS_CENTER:"Бизнес-центр",RESTAURANT:"Ресторан",ROOM_SERVICE:"Обслуживание номеров",ROOFTOP:"Терраса на крыше",PLAY_AREA:"Детская игровая зона",BEACH_SHUTTLE:"Трансфер до пляжа",BEACH_ACCESS:"Доступ к пляжу",MARINA:"Доступ к марине",WATER_SPORTS:"Водные виды спорта",TERRACE:"Терраса"},
  ja:{WIFI:"無料Wi-Fi",BREAKFAST:"朝食",PARKING:"駐車場",GYM:"フィットネスセンター",POOL:"プール",SPA:"スパ",AIRPORT_SHUTTLE:"空港シャトル",FAMILY_ROOMS:"ファミリールーム",BUSINESS_CENTER:"ビジネスセンター",RESTAURANT:"レストラン",ROOM_SERVICE:"ルームサービス",ROOFTOP:"屋上テラス",PLAY_AREA:"子ども用プレイエリア",BEACH_SHUTTLE:"ビーチシャトル",BEACH_ACCESS:"ビーチアクセス",MARINA:"マリーナアクセス",WATER_SPORTS:"ウォータースポーツ",TERRACE:"テラス"},
  ko:{WIFI:"무료 Wi-Fi",BREAKFAST:"조식",PARKING:"주차",GYM:"피트니스 센터",POOL:"수영장",SPA:"스파",AIRPORT_SHUTTLE:"공항 셔틀",FAMILY_ROOMS:"가족 객실",BUSINESS_CENTER:"비즈니스 센터",RESTAURANT:"레스토랑",ROOM_SERVICE:"룸서비스",ROOFTOP:"루프탑 테라스",PLAY_AREA:"어린이 놀이 공간",BEACH_SHUTTLE:"해변 셔틀",BEACH_ACCESS:"해변 이용",MARINA:"마리나 이용",WATER_SPORTS:"수상 스포츠",TERRACE:"테라스"},
  hi:{WIFI:"मुफ़्त वाई-फाई",BREAKFAST:"नाश्ता",PARKING:"पार्किंग",GYM:"फिटनेस सेंटर",POOL:"पूल",SPA:"स्पा",AIRPORT_SHUTTLE:"एयरपोर्ट शटल",FAMILY_ROOMS:"परिवार कक्ष",BUSINESS_CENTER:"बिज़नेस सेंटर",RESTAURANT:"रेस्तरां",ROOM_SERVICE:"रूम सर्विस",ROOFTOP:"रूफटॉप टैरेस",PLAY_AREA:"बच्चों का खेल क्षेत्र",BEACH_SHUTTLE:"बीच शटल",BEACH_ACCESS:"समुद्र तट पहुँच",MARINA:"मरीना पहुँच",WATER_SPORTS:"वॉटर स्पोर्ट्स",TERRACE:"टैरेस"},
  pt:{WIFI:"Wi-Fi grátis",BREAKFAST:"Café da manhã",PARKING:"Estacionamento",GYM:"Academia",POOL:"Piscina",SPA:"Spa",AIRPORT_SHUTTLE:"Transfer do aeroporto",FAMILY_ROOMS:"Quartos familiares",BUSINESS_CENTER:"Centro de negócios",RESTAURANT:"Restaurante",ROOM_SERVICE:"Serviço de quarto",ROOFTOP:"Terraço na cobertura",PLAY_AREA:"Área infantil",BEACH_SHUTTLE:"Transfer para a praia",BEACH_ACCESS:"Acesso à praia",MARINA:"Acesso à marina",WATER_SPORTS:"Esportes aquáticos",TERRACE:"Terraço"},
  id:{WIFI:"Wi-Fi gratis",BREAKFAST:"Sarapan",PARKING:"Parkir",GYM:"Pusat kebugaran",POOL:"Kolam renang",SPA:"Spa",AIRPORT_SHUTTLE:"Antar-jemput bandara",FAMILY_ROOMS:"Kamar keluarga",BUSINESS_CENTER:"Pusat bisnis",RESTAURANT:"Restoran",ROOM_SERVICE:"Layanan kamar",ROOFTOP:"Teras atap",PLAY_AREA:"Area bermain anak",BEACH_SHUTTLE:"Antar-jemput pantai",BEACH_ACCESS:"Akses pantai",MARINA:"Akses marina",WATER_SPORTS:"Olahraga air",TERRACE:"Teras"},
  th:{WIFI:"Wi-Fi ฟรี",BREAKFAST:"อาหารเช้า",PARKING:"ที่จอดรถ",GYM:"ฟิตเนส",POOL:"สระว่ายน้ำ",SPA:"สปา",AIRPORT_SHUTTLE:"รถรับส่งสนามบิน",FAMILY_ROOMS:"ห้องสำหรับครอบครัว",BUSINESS_CENTER:"ศูนย์ธุรกิจ",RESTAURANT:"ห้องอาหาร",ROOM_SERVICE:"รูมเซอร์วิส",ROOFTOP:"ดาดฟ้า",PLAY_AREA:"พื้นที่เล่นสำหรับเด็ก",BEACH_SHUTTLE:"รถรับส่งชายหาด",BEACH_ACCESS:"ทางเข้าชายหาด",MARINA:"ทางเข้ามารีนา",WATER_SPORTS:"กีฬาทางน้ำ",TERRACE:"ระเบียง"},
};

export function hotelAmenityLabel(locale:GuestLocale,code:string,fallback:string):string{return COPY[locale][code]??fallback;}
