import type {GuestLocale} from "./guest-market";

type Copy=Readonly<{eyebrow:string;title:string;description:string;emptyTitle:string;emptyBody:string;cancellationNote:string;bookingInvoice:string;openInvoice:string}>;
const COPY:Record<GuestLocale,Copy>={
  en:{eyebrow:"Financial records",title:"Invoices & documents",description:"Booking documents are generated from persisted reservation records and can be printed or saved as PDF.",emptyTitle:"No invoices yet",emptyBody:"A booking invoice appears after confirmation.",cancellationNote:"Cancellation note",bookingInvoice:"Booking invoice",openInvoice:"Open invoice"},
  ar:{eyebrow:"السجلات المالية",title:"الفواتير والمستندات",description:"كل فاتورة مبنية من سجل الحجز المحفوظ، مع رابط قابل للطباعة والحفظ PDF.",emptyTitle:"لا توجد فواتير بعد",emptyBody:"تظهر فاتورة الحجز بعد تأكيد الحجز.",cancellationNote:"إشعار إلغاء",bookingInvoice:"فاتورة حجز",openInvoice:"فتح الفاتورة"},
  zh:{eyebrow:"财务记录",title:"发票与文件",description:"预订文件根据已保存的预订记录生成，可打印或保存为 PDF。",emptyTitle:"暂无发票",emptyBody:"预订确认后会生成发票。",cancellationNote:"取消通知",bookingInvoice:"预订发票",openInvoice:"打开发票"},
  fr:{eyebrow:"Documents financiers",title:"Factures et documents",description:"Les documents de réservation sont générés à partir des dossiers enregistrés et peuvent être imprimés ou sauvegardés en PDF.",emptyTitle:"Aucune facture",emptyBody:"Une facture apparaît après la confirmation de la réservation.",cancellationNote:"Avis d’annulation",bookingInvoice:"Facture de réservation",openInvoice:"Ouvrir la facture"},
  de:{eyebrow:"Finanzunterlagen",title:"Rechnungen & Dokumente",description:"Buchungsdokumente werden aus gespeicherten Reservierungsdaten erstellt und können gedruckt oder als PDF gespeichert werden.",emptyTitle:"Noch keine Rechnungen",emptyBody:"Nach der Buchungsbestätigung erscheint eine Rechnung.",cancellationNote:"Stornierungsbeleg",bookingInvoice:"Buchungsrechnung",openInvoice:"Rechnung öffnen"},
  es:{eyebrow:"Registros financieros",title:"Facturas y documentos",description:"Los documentos se generan a partir de registros de reserva guardados y pueden imprimirse o guardarse como PDF.",emptyTitle:"Aún no hay facturas",emptyBody:"La factura aparece tras confirmar la reserva.",cancellationNote:"Nota de cancelación",bookingInvoice:"Factura de reserva",openInvoice:"Abrir factura"},
  it:{eyebrow:"Documenti finanziari",title:"Fatture e documenti",description:"I documenti di prenotazione sono generati dai dati salvati e possono essere stampati o salvati in PDF.",emptyTitle:"Nessuna fattura",emptyBody:"La fattura appare dopo la conferma della prenotazione.",cancellationNote:"Nota di cancellazione",bookingInvoice:"Fattura prenotazione",openInvoice:"Apri fattura"},
  tr:{eyebrow:"Finansal kayıtlar",title:"Faturalar ve belgeler",description:"Rezervasyon belgeleri kayıtlı rezervasyon verilerinden oluşturulur ve yazdırılabilir veya PDF olarak kaydedilebilir.",emptyTitle:"Henüz fatura yok",emptyBody:"Rezervasyon onaylandıktan sonra fatura görünür.",cancellationNote:"İptal belgesi",bookingInvoice:"Rezervasyon faturası",openInvoice:"Faturayı aç"},
  ru:{eyebrow:"Финансовые документы",title:"Счета и документы",description:"Документы формируются из сохранённых данных бронирования и могут быть распечатаны или сохранены в PDF.",emptyTitle:"Счетов пока нет",emptyBody:"Счёт появится после подтверждения бронирования.",cancellationNote:"Уведомление об отмене",bookingInvoice:"Счёт за бронирование",openInvoice:"Открыть счёт"},
  ja:{eyebrow:"会計記録",title:"請求書と書類",description:"予約書類は保存済みの予約記録から生成され、印刷または PDF 保存できます。",emptyTitle:"請求書はまだありません",emptyBody:"予約確定後に請求書が表示されます。",cancellationNote:"キャンセル通知",bookingInvoice:"予約請求書",openInvoice:"請求書を開く"},
  ko:{eyebrow:"재무 기록",title:"청구서 및 문서",description:"예약 문서는 저장된 예약 기록을 기반으로 생성되며 인쇄하거나 PDF로 저장할 수 있습니다.",emptyTitle:"아직 청구서가 없습니다",emptyBody:"예약 확정 후 청구서가 표시됩니다.",cancellationNote:"취소 안내서",bookingInvoice:"예약 청구서",openInvoice:"청구서 열기"},
  hi:{eyebrow:"वित्तीय रिकॉर्ड",title:"इनवॉइस और दस्तावेज़",description:"बुकिंग दस्तावेज़ सहेजे गए आरक्षण रिकॉर्ड से बनते हैं और प्रिंट या PDF में सहेजे जा सकते हैं।",emptyTitle:"अभी कोई इनवॉइस नहीं",emptyBody:"बुकिंग की पुष्टि के बाद इनवॉइस दिखाई देता है।",cancellationNote:"रद्दीकरण नोट",bookingInvoice:"बुकिंग इनवॉइस",openInvoice:"इनवॉइस खोलें"},
  pt:{eyebrow:"Registros financeiros",title:"Faturas e documentos",description:"Os documentos são gerados a partir dos registros de reserva salvos e podem ser impressos ou salvos em PDF.",emptyTitle:"Ainda não há faturas",emptyBody:"A fatura aparece após a confirmação da reserva.",cancellationNote:"Aviso de cancelamento",bookingInvoice:"Fatura da reserva",openInvoice:"Abrir fatura"},
  id:{eyebrow:"Catatan keuangan",title:"Faktur & dokumen",description:"Dokumen reservasi dibuat dari data reservasi tersimpan dan dapat dicetak atau disimpan sebagai PDF.",emptyTitle:"Belum ada faktur",emptyBody:"Faktur reservasi muncul setelah konfirmasi.",cancellationNote:"Catatan pembatalan",bookingInvoice:"Faktur reservasi",openInvoice:"Buka faktur"},
  th:{eyebrow:"เอกสารการเงิน",title:"ใบแจ้งหนี้และเอกสาร",description:"เอกสารการจองสร้างจากข้อมูลการจองที่บันทึกไว้ และสามารถพิมพ์หรือบันทึกเป็น PDF ได้",emptyTitle:"ยังไม่มีใบแจ้งหนี้",emptyBody:"ใบแจ้งหนี้จะปรากฏหลังยืนยันการจอง",cancellationNote:"เอกสารยกเลิก",bookingInvoice:"ใบแจ้งหนี้การจอง",openInvoice:"เปิดใบแจ้งหนี้"},
};
export function invoicesUiCopy(locale:GuestLocale):Copy{return COPY[locale];}
