import type {Locale} from "./i18n";

const en = {
  common: {
    save: "Save changes", saving: "Saving…", search: "Search", all: "All", edit: "Edit", cancel: "Cancel", back: "Back", open: "Open", reason: "Reason", status: "Status", actions: "Actions", signedInAs: "Signed in as", signOut: "Sign out", signingOut: "Signing out…", noResults: "No matching results", language: "Language",
  },
  admin: {
    name: "Control Center", operate: "Operate", control: "Control", overview: "Overview", verification: "Verification", properties: "Properties", reviews: "Guest reviews", access: "Access", audit: "Audit log",
    eyebrow: "Platform administration", title: "Control Center", intro: "Review the work that needs a platform decision, then keep every sensitive action attributable.", secureSession: "Admin-scoped session", expires: "Expires",
    liveState: "Live platform state", attention: "What needs attention", decisionsPending: "decisions pending", queuesClear: "Queues clear", allProperties: "All property workspaces", live: "Live", activeDiscoverable: "Active and discoverable", propertyReviews: "Property reviews", waitingDecision: "Waiting for a decision", documents: "Documents", privatePending: "Private files pending", suspended: "Suspended", removedDiscovery: "Removed from discovery", accounts: "Accounts", hotelUsers: "hotel users",
    publishingGate: "Publishing gate", verificationQueues: "Verification queues", verificationIntro: "Only the exact reviewed revision and approved required documents can publish a property.",
    propertyNetwork: "Property network", publishingStatus: "Publishing status", propertyIntro: "Open any property to edit its public identity, operations and commercial configuration. Every change is audited.", manageProperties: "Manage properties", property: "Property", location: "Location", verificationLabel: "Verification", revision: "Revision", verified: "Verified", notVerified: "Not verified", unpublished: "unpublished",
    identityAccess: "Identity and access", administrators: "Platform administrators", accessIntro: "Public administrator registration is disabled. Administrator access remains explicit, isolated and audited.", travelers: "travelers", administratorSince: "Administrator since", activeSession: "active admin session", activeSessions: "active admin sessions", lastActivity: "Last activity", noActiveSession: "No active session",
    accountability: "Accountability", recentAudit: "Recent audit activity", auditIntro: "Newest sensitive and operational mutations recorded by the shared domain services.", noAudit: "No audit activity has been recorded yet.", systemAction: "System action",
    propertyManager: "Property manager", propertyManagerTitle: "Find and operate every property.", propertyManagerIntro: "Search by name, slug, city or address. Open a property to edit it with an attributable administrator action.", searchPlaceholder: "Hotel, slug, city or address", anyStatus: "Any status", rooms: "Rooms", bookings: "Bookings", guestReviews: "Reviews", team: "Team", openEditor: "Open editor",
    editProperty: "Edit property", editPropertyIntro: "Update platform-governed property data. Saving creates a new publishing revision and a complete before/after audit event.", identity: "Identity & location", publicContent: "Public content", operations: "Operations", commercial: "Commercial governance", amenities: "Amenities", nameLabel: "Property name", slug: "Slug", city: "City", country: "Country code", address: "Full address", area: "Area / neighborhood", description: "Description", stars: "Official star rating", latitude: "Latitude", longitude: "Longitude", checkIn: "Check-in time", checkOut: "Check-out time", timezone: "Timezone", currency: "Currency", commission: "Platform commission %", service: "Service charge %", tax: "Tax / mandatory charges %", overbooking: "Allow controlled overbooking", amenityHelp: "One per line: CODE | Display name | optional category", saved: "Property changes saved and audited.", integrityNote: "The slug and publishing decision are protected here. Use the dedicated suspension or verification action for status changes.",
    moderation: "Review moderation", moderationTitle: "Protect trust without rewriting guests.", moderationIntro: "Administrators can hide or restore a review with a recorded reason. Original guest text and the hotel response remain unchanged.", reviewSearch: "Review text, hotel or booking reference", anyVisibility: "Any visibility", published: "Published", hidden: "Hidden", verifiedStay: "verified stay", hotelResponse: "Hotel response", noResponse: "No hotel response", moderationReason: "Moderation reason", moderatedBy: "Moderated by", hide: "Hide review", restore: "Restore review", hideConfirm: "Hide this review from public hotel pages? The original text will be preserved.", restoreConfirm: "Restore this unchanged review to public hotel pages?", reasonPlaceholder: "Explain the policy or trust reason (minimum 10 characters)", moderated: "Review moderation saved.", integrity: "Integrity rule", integrityBody: "HandMeKey never lets an administrator silently edit a guest’s words. Moderation changes visibility and records who acted, when and why.",
    restricted: "Restricted access", signIn: "Administrator sign in", loginIntro: "Use a provisioned HandMeKey platform-administrator account. Public registration is disabled.", email: "Email address", password: "Password", verifying: "Verifying access…", enter: "Enter Control Center", sessionNote: "Admin sessions expire independently and never reuse the traveler session cookie.", loginHero: "One secure door for platform decisions.", loginBody: "Property publishing, private verification documents and sensitive platform actions stay behind an administrator-scoped session.", returnMarketplace: "Return to marketplace", separateScope: "Separate session scope", separateScopeBody: "A traveler login cannot authorize an administrator endpoint.", auditedActions: "Audited actions", auditedActionsBody: "Publishing and access decisions remain attributable.", noRegistration: "No public admin registration", noRegistrationBody: "The first administrator is provisioned once by an operator.", invalidCredentials: "Administrator sign-in failed",
  },
  partner: {
    name: "Partner Hub", currentProperty: "Current property", operate: "Operate", property: "Property", rooms: "Rooms & units", reservations: "Reservations", grow: "Grow", performance: "Performance", promotions: "Promotions", guests: "Guests", messages: "Messages", reviews: "Reviews", addProperty: "Add another property", openMarketplace: "Open HandMeKey",
    workspace: "Property workspace", addPropertyShort: "Add property", publishingReadiness: "Publishing readiness", requirementsComplete: "requirements complete", roomTypes: "Room types", configuredCategories: "configured categories", ratePlans: "Rate plans", commercialPackages: "commercial packages", teamMembers: "Team members", propertyAccess: "property access", serviceCharge: "Service charge", pricingConfiguration: "pricing configuration", taxCharges: "Tax / charges", reviewGated: "Publishing stays review-gated", reviewGatedBody: "Only the exact submitted property revision can become live after platform review.", completeListing: "Complete the listing before selling", completeListingBody: "Content, media, commercial setup and approved business documents all feed one readiness gate.",
    reservationsEyebrow: "Reservations", stayOperations: "Stay operations", commercialContext: "Commercial booking + guest context", commercialContextBody: "Arrival state, guest requests and staff notes stay operationally separate from the reservation’s commercial status.",
    performanceEyebrow: "Performance intelligence", performanceTitle: "See where demand becomes revenue.", firstParty: "first-party platform signals only", days: "days", impressions: "Search impressions", views: "Hotel views", checkoutStarts: "Checkout starts", bookingHolds: "Booking holds", confirmed: "Confirmed bookings", bookedValue: "Active booked value", conversionFunnel: "Conversion funnel", drop: "Where guests drop", opportunity: "Opportunity engine", signals: "Signals worth looking at", actualData: "Explicit rules from actual funnel data—not generated claims.", marketDemand: "Market demand", requestedDates: "Most requested future arrival dates in", demandIntro: "Aggregated destination searches inside the selected reporting window. No guest fingerprint or visitor identity is stored.", noDemand: "Not enough future search demand yet.", arrival: "Arrival", searches: "Searches", guestDemand: "Guest demand", zeroResult: "Zero-result",
    commercial: "Commercial", promotionsTitle: "Promotions", promotionsBody: "Build targeted deals without rewriting the hotel’s daily rates.", oneEngine: "One pricing engine", oneEngineBody: "Eligible deals are applied server-side across search, hotel offers, quotes and bookings.",
    guestCommunication: "Guest communication", messagesTitle: "Messages", messagesBody: "Booking-context conversations for", everyThread: "Every thread has a reservation behind it", everyThreadBody: "Guest messages stay separate from private front-desk notes and anonymous public chat.",
    guestTrust: "Guest trust", reviewsTitle: "Reviews", reviewsBody: "Verified-stay feedback for", verifiedOnly: "Only completed stays can review", repliesScoped: "Property replies are permission-scoped, editable by the property and attached to the verified review.", verifiedReviews: "Verified reviews", average: "Average", awaitingResponse: "Awaiting response", noReviews: "No verified reviews yet", noReviewsBody: "Reviews appear only after a completed booking.", verifiedStay: "verified stay", stayCompleted: "Stay completed", cleanliness: "Cleanliness", staff: "Staff", location: "Location", comfort: "Comfort", value: "Value", yourResponse: "Your response", publicResponse: "Public hotel response", publishResponse: "Publish response", editResponse: "Edit response", updateResponse: "Update response", responsePublished: "Hotel response published.", responseUpdated: "Hotel response updated.",
    partnerAccess: "Partner access", authHero: "Your property business, behind one secure door.", authBody: "Sign in to manage listings, live rates, reservations, guest communication and performance.", propertyControl: "Property control", propertyControlBody: "Manage only the hotels your account is authorized to access.", commercialVisibility: "Commercial visibility", commercialVisibilityBody: "See conversion, demand dates and active booked value.", reviewPublishing: "Review-gated publishing", reviewPublishingBody: "No property goes live until the submitted revision is approved.", travelerInstead: "Booking a stay instead?", travelerSignIn: "Use traveler sign in", backMarketplace: "Back to HandMeKey",
    onboarding: "Partner onboarding", openHub: "Open Partner Hub", stepOne: "Step 1 of your property setup", onboardingHero: "Start with the property. Build the listing around it.", onboardingBody: "Create the hotel workspace first. HandMeKey keeps it private while you add the content and commercial setup required for review.", draftDefault: "Draft by default", draftDefaultBody: "Creating the property never publishes it.", sourceTruth: "One source of truth", sourceTruthBody: "Rooms, rates, policies and inventory attach to this property workspace.", reviewBeforeLive: "Review before go-live", reviewBeforeLiveBody: "The exact submitted revision must pass platform verification.", propertyBasics: "Property basics", createWorkspace: "Create your hotel workspace", completeLater: "You can complete photos, rooms, rates and verification after this step.", propertyName: "Property name", city: "City", countryCode: "Country code", fullAddress: "Full property address", propertyTimezone: "Property timezone", primaryCurrency: "Primary currency", next: "What happens next?", nextBody: "The property is created as a private draft. Nothing appears to travelers until readiness and platform review are complete.", creating: "Creating property…", create: "Create property workspace",
  },
};

const ar: typeof en = {
  common: {
    save: "حفظ التغييرات", saving: "جارٍ الحفظ…", search: "بحث", all: "الكل", edit: "تعديل", cancel: "إلغاء", back: "رجوع", open: "فتح", reason: "السبب", status: "الحالة", actions: "الإجراءات", signedInAs: "مسجل الدخول باسم", signOut: "تسجيل الخروج", signingOut: "جارٍ تسجيل الخروج…", noResults: "لا توجد نتائج مطابقة", language: "اللغة",
  },
  admin: {
    name: "مركز التحكم", operate: "التشغيل", control: "الرقابة", overview: "نظرة عامة", verification: "التحقق", properties: "المنشآت", reviews: "تقييمات الضيوف", access: "الصلاحيات", audit: "سجل التدقيق",
    eyebrow: "إدارة المنصة", title: "مركز التحكم", intro: "راجع القرارات المطلوبة على مستوى المنصة، مع إبقاء كل إجراء حساس موثقًا باسم منفذه.", secureSession: "جلسة إدارية مستقلة", expires: "تنتهي",
    liveState: "حالة المنصة الآن", attention: "ما الذي يحتاج انتباهك", decisionsPending: "قرارات معلقة", queuesClear: "لا توجد مهام معلقة", allProperties: "كل مساحات عمل المنشآت", live: "نشطة", activeDiscoverable: "نشطة وظاهرة في البحث", propertyReviews: "طلبات اعتماد المنشآت", waitingDecision: "بانتظار قرار", documents: "المستندات", privatePending: "ملفات خاصة بانتظار المراجعة", suspended: "موقوفة", removedDiscovery: "محجوبة عن البحث", accounts: "الحسابات", hotelUsers: "مستخدمي فنادق",
    publishingGate: "بوابة النشر", verificationQueues: "قوائم التحقق", verificationIntro: "لا تُنشر المنشأة إلا بعد اعتماد النسخة نفسها والمستندات المطلوبة.",
    propertyNetwork: "شبكة المنشآت", publishingStatus: "حالة النشر", propertyIntro: "افتح أي منشأة لتعديل هويتها العامة وإعداداتها التشغيلية والتجارية. كل تغيير مسجل.", manageProperties: "إدارة المنشآت", property: "المنشأة", location: "الموقع", verificationLabel: "التوثيق", revision: "النسخة", verified: "موثقة", notVerified: "غير موثقة", unpublished: "غير منشورة",
    identityAccess: "الهوية والصلاحيات", administrators: "مديرو المنصة", accessIntro: "لا يوجد تسجيل عام للمديرين. تبقى صلاحية الإدارة مستقلة وصريحة وخاضعة للتدقيق.", travelers: "مسافرين", administratorSince: "مدير منذ", activeSession: "جلسة إدارية نشطة", activeSessions: "جلسات إدارية نشطة", lastActivity: "آخر نشاط", noActiveSession: "لا توجد جلسة نشطة",
    accountability: "المساءلة", recentAudit: "أحدث أنشطة التدقيق", auditIntro: "آخر العمليات الحساسة والتشغيلية المسجلة من خدمات المنصة.", noAudit: "لم يُسجل أي نشاط تدقيق بعد.", systemAction: "إجراء آلي",
    propertyManager: "إدارة المنشآت", propertyManagerTitle: "ابحث وشغّل كل منشأة.", propertyManagerIntro: "ابحث بالاسم أو الرابط أو المدينة أو العنوان، ثم افتح المنشأة لتعديلها بإجراء إداري موثق.", searchPlaceholder: "فندق أو رابط أو مدينة أو عنوان", anyStatus: "أي حالة", rooms: "الغرف", bookings: "الحجوزات", guestReviews: "التقييمات", team: "الفريق", openEditor: "فتح التعديل",
    editProperty: "تعديل المنشأة", editPropertyIntro: "حدّث بيانات المنشأة التي تديرها المنصة. الحفظ ينشئ نسخة نشر جديدة وسجلًا كاملًا قبل وبعد التغيير.", identity: "الهوية والموقع", publicContent: "المحتوى العام", operations: "التشغيل", commercial: "الحوكمة التجارية", amenities: "المرافق", nameLabel: "اسم المنشأة", slug: "الرابط المختصر", city: "المدينة", country: "رمز الدولة", address: "العنوان الكامل", area: "المنطقة / الحي", description: "الوصف", stars: "التصنيف الرسمي", latitude: "خط العرض", longitude: "خط الطول", checkIn: "وقت الدخول", checkOut: "وقت المغادرة", timezone: "المنطقة الزمنية", currency: "العملة", commission: "عمولة المنصة %", service: "رسوم الخدمة %", tax: "الضريبة / الرسوم الإلزامية %", overbooking: "السماح بالحجز الزائد المنضبط", amenityHelp: "مرفق في كل سطر: CODE | الاسم الظاهر | التصنيف اختياري", saved: "تم حفظ تغييرات المنشأة وتوثيقها.", integrityNote: "الرابط وقرار النشر محميان هنا. استخدم إجراء الإيقاف أو التحقق المخصص لتغيير الحالة.",
    moderation: "إدارة التقييمات", moderationTitle: "احمِ الثقة دون تغيير كلام الضيوف.", moderationIntro: "يمكن للمدير إخفاء تقييم أو استعادته مع سبب مسجل. يبقى نص الضيف ورد الفندق كما هو.", reviewSearch: "نص التقييم أو الفندق أو مرجع الحجز", anyVisibility: "أي ظهور", published: "منشور", hidden: "مخفي", verifiedStay: "إقامة موثقة", hotelResponse: "رد الفندق", noResponse: "لا يوجد رد من الفندق", moderationReason: "سبب الإشراف", moderatedBy: "تم الإجراء بواسطة", hide: "إخفاء التقييم", restore: "استعادة التقييم", hideConfirm: "إخفاء هذا التقييم عن صفحات الفندق؟ سيبقى النص الأصلي محفوظًا.", restoreConfirm: "إعادة نشر هذا التقييم دون تغيير نصه؟", reasonPlaceholder: "اشرح سبب السياسة أو الثقة (10 أحرف على الأقل)", moderated: "تم حفظ قرار الإشراف.", integrity: "قاعدة النزاهة", integrityBody: "لا يسمح HandMeKey للمدير بتغيير كلمات الضيف بصمت. الإشراف يغيّر الظهور فقط ويسجل من نفذ القرار ووقته وسببه.",
    restricted: "دخول مقيّد", signIn: "دخول مدير المنصة", loginIntro: "استخدم حساب مدير منصة مفعّل مسبقًا. التسجيل العام معطل.", email: "البريد الإلكتروني", password: "كلمة المرور", verifying: "جارٍ التحقق…", enter: "دخول مركز التحكم", sessionNote: "تنتهي جلسة المدير بشكل مستقل ولا تستخدم ملف جلسة المسافر.", loginHero: "بوابة آمنة واحدة لقرارات المنصة.", loginBody: "يبقى نشر المنشآت والمستندات الخاصة والعمليات الحساسة خلف جلسة إدارية مستقلة.", returnMarketplace: "العودة إلى الموقع", separateScope: "جلسة مستقلة", separateScopeBody: "دخول المسافر لا يمنح صلاحية لأي مسار إداري.", auditedActions: "إجراءات موثقة", auditedActionsBody: "تبقى قرارات النشر والصلاحيات مرتبطة بمن نفذها.", noRegistration: "لا يوجد تسجيل عام للمدير", noRegistrationBody: "يتم تفعيل المدير الأول مرة واحدة من مشغّل النظام.", invalidCredentials: "تعذر تسجيل دخول المدير",
  },
  partner: {
    name: "بوابة الشركاء", currentProperty: "المنشأة الحالية", operate: "التشغيل", property: "المنشأة", rooms: "الغرف والوحدات", reservations: "الحجوزات", grow: "النمو", performance: "الأداء", promotions: "العروض", guests: "الضيوف", messages: "الرسائل", reviews: "التقييمات", addProperty: "إضافة منشأة أخرى", openMarketplace: "فتح HandMeKey",
    workspace: "مساحة عمل المنشأة", addPropertyShort: "إضافة منشأة", publishingReadiness: "جاهزية النشر", requirementsComplete: "متطلبات مكتملة", roomTypes: "أنواع الغرف", configuredCategories: "فئات مجهزة", ratePlans: "خطط الأسعار", commercialPackages: "باقات تجارية", teamMembers: "أعضاء الفريق", propertyAccess: "صلاحيات المنشأة", serviceCharge: "رسوم الخدمة", pricingConfiguration: "إعدادات التسعير", taxCharges: "الضريبة / الرسوم", reviewGated: "النشر مرتبط بالمراجعة", reviewGatedBody: "لا تصبح المنشأة متاحة إلا بعد اعتماد نسخة النشر المقدمة نفسها.", completeListing: "أكمل الملف قبل البيع", completeListingBody: "المحتوى والصور والإعداد التجاري والمستندات المعتمدة تدخل جميعها في بوابة جاهزية واحدة.",
    reservationsEyebrow: "الحجوزات", stayOperations: "تشغيل الإقامات", commercialContext: "الحجز التجاري وسياق الضيف", commercialContextBody: "تبقى حالة الوصول وطلبات الضيف وملاحظات الموظفين منفصلة تشغيليًا عن الحالة التجارية للحجز.",
    performanceEyebrow: "ذكاء الأداء", performanceTitle: "اعرف أين يتحول الطلب إلى إيراد.", firstParty: "إشارات المنصة المباشرة فقط", days: "يوم", impressions: "ظهور البحث", views: "مشاهدات الفندق", checkoutStarts: "بدء الدفع", bookingHolds: "حجوزات معلقة", confirmed: "حجوزات مؤكدة", bookedValue: "قيمة الحجوزات النشطة", conversionFunnel: "مسار التحويل", drop: "أين يغادر الضيوف", opportunity: "محرك الفرص", signals: "إشارات تستحق المراجعة", actualData: "قواعد صريحة مبنية على بيانات المسار الفعلية، دون ادعاءات مولّدة.", marketDemand: "طلب السوق", requestedDates: "أكثر تواريخ الوصول طلبًا في", demandIntro: "عمليات بحث مجمعة عن الوجهة ضمن فترة التقرير، دون حفظ بصمة الزائر أو هويته.", noDemand: "لا توجد بيانات طلب مستقبلية كافية بعد.", arrival: "الوصول", searches: "عمليات البحث", guestDemand: "طلب الضيوف", zeroResult: "دون نتائج",
    commercial: "التجاري", promotionsTitle: "العروض", promotionsBody: "أنشئ عروضًا مستهدفة دون إعادة كتابة السعر اليومي للفندق.", oneEngine: "محرك تسعير واحد", oneEngineBody: "تطبق العروض المؤهلة من الخادم على البحث وعروض الفندق والتسعير والحجز.",
    guestCommunication: "التواصل مع الضيف", messagesTitle: "الرسائل", messagesBody: "محادثات مرتبطة بالحجوزات لدى", everyThread: "كل محادثة مرتبطة بحجز", everyThreadBody: "تبقى رسائل الضيف منفصلة عن ملاحظات الاستقبال الخاصة والدردشة العامة.",
    guestTrust: "ثقة الضيوف", reviewsTitle: "التقييمات", reviewsBody: "آراء الإقامات الموثقة لدى", verifiedOnly: "فقط الإقامات المكتملة يمكنها التقييم", repliesScoped: "ردود المنشأة مقيدة بالصلاحيات وقابلة للتعديل من الفندق ومرتبطة بالتقييم الموثق.", verifiedReviews: "تقييمات موثقة", average: "المتوسط", awaitingResponse: "بانتظار الرد", noReviews: "لا توجد تقييمات موثقة بعد", noReviewsBody: "لا تظهر التقييمات إلا بعد حجز مكتمل.", verifiedStay: "إقامة موثقة", stayCompleted: "اكتملت الإقامة", cleanliness: "النظافة", staff: "الموظفون", location: "الموقع", comfort: "الراحة", value: "القيمة", yourResponse: "ردك", publicResponse: "رد الفندق العام", publishResponse: "نشر الرد", editResponse: "تعديل الرد", updateResponse: "تحديث الرد", responsePublished: "تم نشر رد الفندق.", responseUpdated: "تم تحديث رد الفندق.",
    partnerAccess: "دخول الشريك", authHero: "إدارة منشأتك خلف بوابة آمنة واحدة.", authBody: "سجل الدخول لإدارة الملف والأسعار المباشرة والحجوزات والتواصل والأداء.", propertyControl: "تحكم بالمنشأة", propertyControlBody: "لا تدير إلا الفنادق المصرح لحسابك بالوصول إليها.", commercialVisibility: "رؤية تجارية", commercialVisibilityBody: "تابع التحويل وتواريخ الطلب وقيمة الحجوزات النشطة.", reviewPublishing: "نشر خاضع للمراجعة", reviewPublishingBody: "لا تنشر أي منشأة قبل اعتماد النسخة المقدمة.", travelerInstead: "هل تريد حجز إقامة؟", travelerSignIn: "استخدم دخول المسافر", backMarketplace: "العودة إلى HandMeKey",
    onboarding: "إضافة منشأة", openHub: "فتح بوابة الشركاء", stepOne: "الخطوة الأولى من إعداد منشأتك", onboardingHero: "ابدأ بالمنشأة وابنِ الملف حولها.", onboardingBody: "أنشئ مساحة عمل الفندق أولًا. يبقيها HandMeKey خاصة أثناء إضافة المحتوى والإعداد التجاري المطلوب للمراجعة.", draftDefault: "مسودة افتراضيًا", draftDefaultBody: "إنشاء المنشأة لا ينشرها أبدًا.", sourceTruth: "مصدر واحد للحقيقة", sourceTruthBody: "ترتبط الغرف والأسعار والسياسات والمخزون بمساحة المنشأة.", reviewBeforeLive: "مراجعة قبل النشر", reviewBeforeLiveBody: "يجب أن تجتاز النسخة المقدمة نفسها تحقق المنصة.", propertyBasics: "أساسيات المنشأة", createWorkspace: "أنشئ مساحة عمل الفندق", completeLater: "يمكنك إكمال الصور والغرف والأسعار والتحقق بعد هذه الخطوة.", propertyName: "اسم المنشأة", city: "المدينة", countryCode: "رمز الدولة", fullAddress: "العنوان الكامل", propertyTimezone: "المنطقة الزمنية", primaryCurrency: "العملة الأساسية", next: "ماذا يحدث بعد ذلك؟", nextBody: "تُنشأ المنشأة كمسودة خاصة ولا تظهر للمسافرين حتى تكتمل الجاهزية ومراجعة المنصة.", creating: "جارٍ إنشاء المنشأة…", create: "إنشاء مساحة العمل",
  },
};

export function portalDictionary(locale: Locale) {
  return locale === "ar" ? ar : en;
}
