import type {GuestLocale} from "./guest-market";

type Copy=Readonly<{
  loadFail:string;noRooms:string;chooseFirst:string;createFail:string;eyebrow:string;title:string;intro:string;roomType:string;loading:string;chooseRoom:string;optionalTarget:string;starting:string;watchButton:string;
  success:(room:string)=>string;current:(room:string,total:string,currency:string)=>string;
}>;

const COPY:Record<GuestLocale,Copy>={
  en:{loadFail:"Unable to load room types",noRooms:"No room types are available to watch for these dates.",chooseFirst:"Choose the room type you want to track first.",createFail:"Unable to create price watch",eyebrow:"Price watch",title:"Choose which room price to track",intro:"Choose a room type first, then set an optional target total or leave it blank to watch for a new low.",roomType:"Room type",loading:"Loading rooms…",chooseRoom:"Choose a room type",optionalTarget:"Optional target total",starting:"Starting watch…",watchButton:"Watch this room price",success:r=>`Price watch active for ${r}. We will track this room type only and will not switch to another type.`,current:(r,t,c)=>`Current live price for ${r}: ${t} ${c}. Future drops will be compared only against this room type.`},
  ar:{loadFail:"تعذر تحميل أنواع الغرف",noRooms:"لا توجد غرف متاحة للمراقبة لهذه التواريخ.",chooseFirst:"اختر نوع الغرفة التي تريد متابعة سعرها أولًا.",createFail:"تعذر إنشاء مراقبة السعر",eyebrow:"مراقبة السعر",title:"اختر الغرفة التي تريد متابعة سعرها",intro:"اختر نوع الغرفة أولًا، ثم ضع إجماليًا مستهدفًا اختياريًا أو اتركه فارغًا لمراقبة أي سعر أدنى جديد.",roomType:"نوع الغرفة",loading:"جارٍ تحميل الغرف…",chooseRoom:"اختر نوع الغرفة",optionalTarget:"إجمالي مستهدف اختياري",starting:"جارٍ بدء المراقبة…",watchButton:"راقب سعر هذه الغرفة",success:r=>`تم تفعيل مراقبة سعر ${r}. سنراقب هذا النوع من الغرف فقط ولن ننتقل إلى نوع آخر.`,current:(r,t,c)=>`السعر المباشر الحالي لـ ${r}: ${t} ${c}. سنقارن أي انخفاضات مستقبلية بنفس نوع الغرفة فقط.`},
  zh:{loadFail:"无法加载房型",noRooms:"这些日期没有可监控的房型。",chooseFirst:"请先选择要跟踪价格的房型。",createFail:"无法创建价格监控",eyebrow:"价格监控",title:"选择要跟踪的房型价格",intro:"先选择房型，然后可设置目标总价；留空则监控新的最低价。",roomType:"房型",loading:"正在加载房型…",chooseRoom:"选择房型",optionalTarget:"可选目标总价",starting:"正在启动监控…",watchButton:"监控此房型价格",success:r=>`${r} 的价格监控已启用。我们只跟踪此房型，不会切换到其他房型。`,current:(r,t,c)=>`${r} 当前实时价格：${t} ${c}。未来降价只会与此房型比较。`},
  fr:{loadFail:"Impossible de charger les types de chambre",noRooms:"Aucun type de chambre n’est disponible à surveiller pour ces dates.",chooseFirst:"Choisissez d’abord le type de chambre à suivre.",createFail:"Impossible de créer l’alerte de prix",eyebrow:"Suivi de prix",title:"Choisissez le prix de chambre à suivre",intro:"Choisissez d’abord un type de chambre, puis définissez un total cible facultatif ou laissez vide pour suivre un nouveau prix minimum.",roomType:"Type de chambre",loading:"Chargement des chambres…",chooseRoom:"Choisir un type de chambre",optionalTarget:"Total cible facultatif",starting:"Activation du suivi…",watchButton:"Suivre le prix de cette chambre",success:r=>`Le suivi de prix est actif pour ${r}. Nous suivrons uniquement ce type de chambre.`,current:(r,t,c)=>`Prix actuel en direct pour ${r} : ${t} ${c}. Les baisses futures seront comparées uniquement à ce type de chambre.`},
  de:{loadFail:"Zimmertypen konnten nicht geladen werden",noRooms:"Für diese Daten sind keine beobachtbaren Zimmertypen verfügbar.",chooseFirst:"Wählen Sie zuerst den Zimmertyp, dessen Preis Sie beobachten möchten.",createFail:"Preisbeobachtung konnte nicht erstellt werden",eyebrow:"Preisbeobachtung",title:"Wählen Sie den zu beobachtenden Zimmerpreis",intro:"Wählen Sie zuerst einen Zimmertyp und setzen Sie optional einen Zielgesamtpreis oder lassen Sie das Feld leer, um neue Tiefstpreise zu beobachten.",roomType:"Zimmertyp",loading:"Zimmer werden geladen…",chooseRoom:"Zimmertyp wählen",optionalTarget:"Optionaler Zielgesamtpreis",starting:"Beobachtung wird gestartet…",watchButton:"Diesen Zimmerpreis beobachten",success:r=>`Preisbeobachtung für ${r} ist aktiv. Es wird nur dieser Zimmertyp verfolgt.`,current:(r,t,c)=>`Aktueller Live-Preis für ${r}: ${t} ${c}. Künftige Preissenkungen werden nur mit diesem Zimmertyp verglichen.`},
  es:{loadFail:"No se pudieron cargar los tipos de habitación",noRooms:"No hay tipos de habitación disponibles para vigilar en estas fechas.",chooseFirst:"Elige primero el tipo de habitación cuyo precio quieres seguir.",createFail:"No se pudo crear la alerta de precio",eyebrow:"Seguimiento de precio",title:"Elige qué precio de habitación seguir",intro:"Elige primero un tipo de habitación y luego fija un total objetivo opcional o déjalo vacío para vigilar un nuevo mínimo.",roomType:"Tipo de habitación",loading:"Cargando habitaciones…",chooseRoom:"Elige un tipo de habitación",optionalTarget:"Total objetivo opcional",starting:"Iniciando seguimiento…",watchButton:"Seguir el precio de esta habitación",success:r=>`El seguimiento de precio está activo para ${r}. Solo seguiremos este tipo de habitación.`,current:(r,t,c)=>`Precio actual en vivo para ${r}: ${t} ${c}. Las futuras bajadas se compararán solo con este tipo de habitación.`},
  it:{loadFail:"Impossibile caricare i tipi di camera",noRooms:"Nessun tipo di camera è disponibile da monitorare per queste date.",chooseFirst:"Scegli prima il tipo di camera di cui vuoi monitorare il prezzo.",createFail:"Impossibile creare il monitoraggio prezzo",eyebrow:"Monitoraggio prezzo",title:"Scegli quale prezzo camera monitorare",intro:"Scegli prima un tipo di camera, quindi imposta un totale obiettivo facoltativo oppure lascia vuoto per monitorare un nuovo minimo.",roomType:"Tipo di camera",loading:"Caricamento camere…",chooseRoom:"Scegli un tipo di camera",optionalTarget:"Totale obiettivo facoltativo",starting:"Avvio monitoraggio…",watchButton:"Monitora il prezzo di questa camera",success:r=>`Monitoraggio prezzo attivo per ${r}. Seguiremo solo questo tipo di camera.`,current:(r,t,c)=>`Prezzo live attuale per ${r}: ${t} ${c}. I futuri ribassi saranno confrontati solo con questo tipo di camera.`},
  tr:{loadFail:"Oda türleri yüklenemedi",noRooms:"Bu tarihler için izlenebilecek oda türü yok.",chooseFirst:"Önce fiyatını takip etmek istediğiniz oda türünü seçin.",createFail:"Fiyat takibi oluşturulamadı",eyebrow:"Fiyat takibi",title:"Takip edilecek oda fiyatını seçin",intro:"Önce oda türünü seçin; ardından isteğe bağlı hedef toplam belirleyin veya yeni bir düşük fiyatı izlemek için boş bırakın.",roomType:"Oda türü",loading:"Odalar yükleniyor…",chooseRoom:"Oda türü seçin",optionalTarget:"İsteğe bağlı hedef toplam",starting:"Takip başlatılıyor…",watchButton:"Bu oda fiyatını takip et",success:r=>`${r} için fiyat takibi etkin. Yalnızca bu oda türünü takip edeceğiz.`,current:(r,t,c)=>`${r} için güncel canlı fiyat: ${t} ${c}. Gelecekteki düşüşler yalnızca bu oda türüyle karşılaştırılacak.`},
  ru:{loadFail:"Не удалось загрузить типы номеров",noRooms:"На эти даты нет типов номеров, доступных для отслеживания.",chooseFirst:"Сначала выберите тип номера, цену которого хотите отслеживать.",createFail:"Не удалось создать отслеживание цены",eyebrow:"Отслеживание цены",title:"Выберите цену номера для отслеживания",intro:"Сначала выберите тип номера, затем при желании укажите целевую сумму или оставьте поле пустым для отслеживания нового минимума.",roomType:"Тип номера",loading:"Загрузка номеров…",chooseRoom:"Выберите тип номера",optionalTarget:"Необязательная целевая сумма",starting:"Запуск отслеживания…",watchButton:"Отслеживать цену этого номера",success:r=>`Отслеживание цены для ${r} включено. Мы будем следить только за этим типом номера.`,current:(r,t,c)=>`Текущая цена для ${r}: ${t} ${c}. Будущие снижения будут сравниваться только с этим типом номера.`},
  ja:{loadFail:"客室タイプを読み込めませんでした",noRooms:"この日程で価格を監視できる客室タイプはありません。",chooseFirst:"まず価格を追跡する客室タイプを選択してください。",createFail:"価格監視を作成できませんでした",eyebrow:"価格監視",title:"追跡する客室価格を選択",intro:"まず客室タイプを選び、任意の目標合計額を設定するか、空欄のまま新しい最安値を監視します。",roomType:"客室タイプ",loading:"客室を読み込み中…",chooseRoom:"客室タイプを選択",optionalTarget:"任意の目標合計額",starting:"監視を開始中…",watchButton:"この客室価格を監視",success:r=>`${r} の価格監視を開始しました。この客室タイプのみを追跡します。`,current:(r,t,c)=>`${r} の現在のライブ価格：${t} ${c}。今後の値下がりはこの客室タイプだけと比較します。`},
  ko:{loadFail:"객실 유형을 불러올 수 없습니다",noRooms:"이 날짜에 모니터링할 수 있는 객실 유형이 없습니다.",chooseFirst:"먼저 가격을 추적할 객실 유형을 선택하세요.",createFail:"가격 모니터링을 만들 수 없습니다",eyebrow:"가격 모니터링",title:"추적할 객실 가격을 선택하세요",intro:"먼저 객실 유형을 선택한 뒤 선택적으로 목표 총액을 설정하거나 비워 두어 새로운 최저가를 추적하세요.",roomType:"객실 유형",loading:"객실 불러오는 중…",chooseRoom:"객실 유형 선택",optionalTarget:"선택 목표 총액",starting:"모니터링 시작 중…",watchButton:"이 객실 가격 추적",success:r=>`${r} 가격 모니터링이 활성화되었습니다. 이 객실 유형만 추적합니다.`,current:(r,t,c)=>`${r}의 현재 실시간 가격: ${t} ${c}. 이후 가격 하락은 이 객실 유형과만 비교됩니다.`},
  hi:{loadFail:"कमरे के प्रकार लोड नहीं हो सके",noRooms:"इन तारीखों के लिए निगरानी योग्य कमरे उपलब्ध नहीं हैं।",chooseFirst:"पहले वह कमरा चुनें जिसकी कीमत आप ट्रैक करना चाहते हैं।",createFail:"कीमत निगरानी बनाई नहीं जा सकी",eyebrow:"कीमत निगरानी",title:"ट्रैक करने के लिए कमरे की कीमत चुनें",intro:"पहले कमरे का प्रकार चुनें, फिर वैकल्पिक लक्ष्य कुल सेट करें या नई न्यूनतम कीमत देखने के लिए खाली छोड़ दें।",roomType:"कमरे का प्रकार",loading:"कमरे लोड हो रहे हैं…",chooseRoom:"कमरे का प्रकार चुनें",optionalTarget:"वैकल्पिक लक्ष्य कुल",starting:"निगरानी शुरू हो रही है…",watchButton:"इस कमरे की कीमत ट्रैक करें",success:r=>`${r} के लिए कीमत निगरानी सक्रिय है। हम केवल इसी कमरे के प्रकार को ट्रैक करेंगे।`,current:(r,t,c)=>`${r} की वर्तमान लाइव कीमत: ${t} ${c}। भविष्य की गिरावट की तुलना केवल इसी कमरे के प्रकार से होगी।`},
  pt:{loadFail:"Não foi possível carregar os tipos de quarto",noRooms:"Não há tipos de quarto disponíveis para acompanhar nestas datas.",chooseFirst:"Escolha primeiro o tipo de quarto cujo preço deseja acompanhar.",createFail:"Não foi possível criar o acompanhamento de preço",eyebrow:"Acompanhamento de preço",title:"Escolha qual preço de quarto acompanhar",intro:"Escolha primeiro um tipo de quarto e depois defina um total alvo opcional ou deixe vazio para acompanhar um novo menor preço.",roomType:"Tipo de quarto",loading:"Carregando quartos…",chooseRoom:"Escolha um tipo de quarto",optionalTarget:"Total alvo opcional",starting:"Iniciando acompanhamento…",watchButton:"Acompanhar preço deste quarto",success:r=>`Acompanhamento de preço ativo para ${r}. Acompanharemos apenas este tipo de quarto.`,current:(r,t,c)=>`Preço atual ao vivo para ${r}: ${t} ${c}. Futuras quedas serão comparadas apenas com este tipo de quarto.`},
  id:{loadFail:"Tidak dapat memuat tipe kamar",noRooms:"Tidak ada tipe kamar yang dapat dipantau untuk tanggal ini.",chooseFirst:"Pilih dulu tipe kamar yang ingin Anda pantau harganya.",createFail:"Tidak dapat membuat pemantauan harga",eyebrow:"Pantau harga",title:"Pilih harga kamar yang ingin dipantau",intro:"Pilih tipe kamar terlebih dahulu, lalu tentukan total target opsional atau biarkan kosong untuk memantau harga terendah baru.",roomType:"Tipe kamar",loading:"Memuat kamar…",chooseRoom:"Pilih tipe kamar",optionalTarget:"Total target opsional",starting:"Memulai pemantauan…",watchButton:"Pantau harga kamar ini",success:r=>`Pemantauan harga aktif untuk ${r}. Kami hanya akan memantau tipe kamar ini.`,current:(r,t,c)=>`Harga live saat ini untuk ${r}: ${t} ${c}. Penurunan berikutnya hanya akan dibandingkan dengan tipe kamar ini.`},
  th:{loadFail:"ไม่สามารถโหลดประเภทห้องได้",noRooms:"ไม่มีประเภทห้องที่สามารถติดตามราคาได้สำหรับวันที่เลือก",chooseFirst:"เลือกประเภทห้องที่ต้องการติดตามราคาก่อน",createFail:"ไม่สามารถสร้างการติดตามราคาได้",eyebrow:"ติดตามราคา",title:"เลือกราคาห้องที่ต้องการติดตาม",intro:"เลือกประเภทห้องก่อน จากนั้นตั้งยอดเป้าหมายแบบไม่บังคับ หรือเว้นว่างเพื่อติดตามราคาต่ำสุดใหม่",roomType:"ประเภทห้อง",loading:"กำลังโหลดห้อง…",chooseRoom:"เลือกประเภทห้อง",optionalTarget:"ยอดเป้าหมาย (ไม่บังคับ)",starting:"กำลังเริ่มติดตาม…",watchButton:"ติดตามราคาห้องนี้",success:r=>`เปิดการติดตามราคาสำหรับ ${r} แล้ว เราจะติดตามเฉพาะประเภทห้องนี้`,current:(r,t,c)=>`ราคาปัจจุบันของ ${r}: ${t} ${c} การลดราคาในอนาคตจะเปรียบเทียบกับห้องประเภทนี้เท่านั้น`},
};

export function priceWatchUiCopy(locale:GuestLocale):Copy{return COPY[locale];}
