import type {GuestLocale} from "./guest-market";

type AdvancedSearchCopy=Readonly<{
  guestRating:string;
  anyRating:string;
  propertyType:string;
  anyProperty:string;
  topRated:string;
  dealsOnly:string;
  accessible:string;
  hotel:string;
  resort:string;
  apartment:string;
  villa:string;
}>;

type SearchUiCopy=Readonly<{
  destinationMatched:string;
  unavailableTitle:string;
  unavailableBody:string;
  sponsored:string;
  showMore:string;
  amenities:Readonly<Record<string,string>>;
  advanced:AdvancedSearchCopy;
}>;

const EN_AMENITIES={WIFI:"Wi-Fi",PARKING:"Parking",POOL:"Pool",GYM:"Gym",BREAKFAST:"Breakfast"};
const EN_ADVANCED:AdvancedSearchCopy={guestRating:"Guest rating",anyRating:"Any guest rating",propertyType:"Property type",anyProperty:"Any property type",topRated:"Highest guest rating",dealsOnly:"Deals only",accessible:"Wheelchair accessible",hotel:"Hotel",resort:"Resort",apartment:"Apartment",villa:"Villa"};

const COPY:Record<GuestLocale,SearchUiCopy>={
  en:{destinationMatched:"Destination matched",unavailableTitle:"Search is temporarily unavailable",unavailableBody:"Hotel data could not be reached right now. Please try again shortly.",sponsored:"Sponsored",showMore:"Show more hotels",amenities:EN_AMENITIES,advanced:EN_ADVANCED},
  ar:{destinationMatched:"تم فهم الوجهة",unavailableTitle:"البحث غير متاح مؤقتًا",unavailableBody:"تعذر الوصول إلى بيانات الفنادق الآن. حاول مرة أخرى بعد قليل.",sponsored:"مموّل",showMore:"عرض المزيد من الفنادق",amenities:{WIFI:"واي فاي",PARKING:"مواقف سيارات",POOL:"مسبح",GYM:"نادي رياضي",BREAKFAST:"إفطار"},advanced:{guestRating:"تقييم الضيوف",anyRating:"أي تقييم",propertyType:"نوع مكان الإقامة",anyProperty:"كل أنواع الإقامة",topRated:"أعلى تقييم للضيوف",dealsOnly:"العروض فقط",accessible:"مناسب للكراسي المتحركة",hotel:"فندق",resort:"منتجع",apartment:"شقة",villa:"فيلا"}},
  zh:{destinationMatched:"已匹配目的地",unavailableTitle:"搜索暂时不可用",unavailableBody:"目前无法访问酒店数据，请稍后再试。",sponsored:"推广",showMore:"查看更多酒店",amenities:{WIFI:"无线网络",PARKING:"停车场",POOL:"游泳池",GYM:"健身房",BREAKFAST:"早餐"},advanced:{guestRating:"住客评分",anyRating:"任何住客评分",propertyType:"住宿类型",anyProperty:"任何住宿类型",topRated:"住客评分最高",dealsOnly:"仅优惠",accessible:"无障碍通行",hotel:"酒店",resort:"度假村",apartment:"公寓",villa:"别墅"}},
  fr:{destinationMatched:"Destination reconnue",unavailableTitle:"La recherche est temporairement indisponible",unavailableBody:"Les données des hôtels sont momentanément inaccessibles. Réessayez dans quelques instants.",sponsored:"Sponsorisé",showMore:"Afficher plus d’hôtels",amenities:{WIFI:"Wi-Fi",PARKING:"Parking",POOL:"Piscine",GYM:"Salle de sport",BREAKFAST:"Petit-déjeuner"},advanced:{guestRating:"Note des clients",anyRating:"Toute note",propertyType:"Type d’hébergement",anyProperty:"Tout type",topRated:"Meilleure note client",dealsOnly:"Offres uniquement",accessible:"Accessible en fauteuil roulant",hotel:"Hôtel",resort:"Complexe hôtelier",apartment:"Appartement",villa:"Villa"}},
  de:{destinationMatched:"Reiseziel erkannt",unavailableTitle:"Suche vorübergehend nicht verfügbar",unavailableBody:"Hoteldaten sind derzeit nicht erreichbar. Bitte versuchen Sie es gleich erneut.",sponsored:"Gesponsert",showMore:"Mehr Hotels anzeigen",amenities:{WIFI:"WLAN",PARKING:"Parkplatz",POOL:"Pool",GYM:"Fitnessraum",BREAKFAST:"Frühstück"},advanced:{guestRating:"Gästebewertung",anyRating:"Beliebige Bewertung",propertyType:"Unterkunftsart",anyProperty:"Beliebige Unterkunftsart",topRated:"Beste Gästebewertung",dealsOnly:"Nur Angebote",accessible:"Rollstuhlgerecht",hotel:"Hotel",resort:"Resort",apartment:"Apartment",villa:"Villa"}},
  es:{destinationMatched:"Destino reconocido",unavailableTitle:"La búsqueda no está disponible temporalmente",unavailableBody:"No se puede acceder a los datos de hoteles ahora. Inténtalo de nuevo en unos instantes.",sponsored:"Patrocinado",showMore:"Mostrar más hoteles",amenities:{WIFI:"Wi-Fi",PARKING:"Aparcamiento",POOL:"Piscina",GYM:"Gimnasio",BREAKFAST:"Desayuno"},advanced:{guestRating:"Puntuación de los huéspedes",anyRating:"Cualquier puntuación",propertyType:"Tipo de alojamiento",anyProperty:"Cualquier tipo",topRated:"Mejor puntuación",dealsOnly:"Solo ofertas",accessible:"Accesible en silla de ruedas",hotel:"Hotel",resort:"Resort",apartment:"Apartamento",villa:"Villa"}},
  it:{destinationMatched:"Destinazione riconosciuta",unavailableTitle:"Ricerca temporaneamente non disponibile",unavailableBody:"I dati degli hotel non sono raggiungibili al momento. Riprova tra poco.",sponsored:"Sponsorizzato",showMore:"Mostra altri hotel",amenities:{WIFI:"Wi-Fi",PARKING:"Parcheggio",POOL:"Piscina",GYM:"Palestra",BREAKFAST:"Colazione"},advanced:{guestRating:"Punteggio ospiti",anyRating:"Qualsiasi punteggio",propertyType:"Tipo di struttura",anyProperty:"Qualsiasi tipo",topRated:"Punteggio ospiti più alto",dealsOnly:"Solo offerte",accessible:"Accessibile in sedia a rotelle",hotel:"Hotel",resort:"Resort",apartment:"Appartamento",villa:"Villa"}},
  tr:{destinationMatched:"Destinasyon eşleşti",unavailableTitle:"Arama geçici olarak kullanılamıyor",unavailableBody:"Otel verilerine şu anda ulaşılamıyor. Lütfen biraz sonra tekrar deneyin.",sponsored:"Sponsorlu",showMore:"Daha fazla otel göster",amenities:{WIFI:"Wi-Fi",PARKING:"Otopark",POOL:"Havuz",GYM:"Spor salonu",BREAKFAST:"Kahvaltı"},advanced:{guestRating:"Misafir puanı",anyRating:"Tüm puanlar",propertyType:"Tesis türü",anyProperty:"Tüm tesis türleri",topRated:"En yüksek misafir puanı",dealsOnly:"Yalnızca fırsatlar",accessible:"Tekerlekli sandalye erişimi",hotel:"Otel",resort:"Tatil köyü",apartment:"Daire",villa:"Villa"}},
  ru:{destinationMatched:"Направление распознано",unavailableTitle:"Поиск временно недоступен",unavailableBody:"Данные отелей сейчас недоступны. Повторите попытку немного позже.",sponsored:"Реклама",showMore:"Показать больше отелей",amenities:{WIFI:"Wi-Fi",PARKING:"Парковка",POOL:"Бассейн",GYM:"Фитнес-зал",BREAKFAST:"Завтрак"},advanced:{guestRating:"Оценка гостей",anyRating:"Любая оценка",propertyType:"Тип размещения",anyProperty:"Любой тип",topRated:"Самая высокая оценка",dealsOnly:"Только предложения",accessible:"Доступ для колясок",hotel:"Отель",resort:"Курорт",apartment:"Апартаменты",villa:"Вилла"}},
  ja:{destinationMatched:"目的地を認識しました",unavailableTitle:"検索は一時的に利用できません",unavailableBody:"現在ホテルデータにアクセスできません。しばらくしてからもう一度お試しください。",sponsored:"スポンサー",showMore:"ホテルをさらに表示",amenities:{WIFI:"Wi-Fi",PARKING:"駐車場",POOL:"プール",GYM:"ジム",BREAKFAST:"朝食"},advanced:{guestRating:"ゲスト評価",anyRating:"すべての評価",propertyType:"宿泊施設タイプ",anyProperty:"すべてのタイプ",topRated:"ゲスト評価が高い順",dealsOnly:"セールのみ",accessible:"車椅子対応",hotel:"ホテル",resort:"リゾート",apartment:"アパートメント",villa:"ヴィラ"}},
  ko:{destinationMatched:"목적지가 확인되었습니다",unavailableTitle:"검색을 일시적으로 사용할 수 없습니다",unavailableBody:"현재 호텔 데이터에 접근할 수 없습니다. 잠시 후 다시 시도해 주세요.",sponsored:"스폰서",showMore:"호텔 더 보기",amenities:{WIFI:"Wi-Fi",PARKING:"주차",POOL:"수영장",GYM:"피트니스 센터",BREAKFAST:"조식"},advanced:{guestRating:"투숙객 평점",anyRating:"모든 평점",propertyType:"숙소 유형",anyProperty:"모든 숙소 유형",topRated:"투숙객 평점 높은 순",dealsOnly:"할인 상품만",accessible:"휠체어 이용 가능",hotel:"호텔",resort:"리조트",apartment:"아파트",villa:"빌라"}},
  hi:{destinationMatched:"गंतव्य मिल गया",unavailableTitle:"खोज अस्थायी रूप से उपलब्ध नहीं है",unavailableBody:"अभी होटल डेटा उपलब्ध नहीं है। कृपया थोड़ी देर बाद फिर प्रयास करें।",sponsored:"प्रायोजित",showMore:"और होटल दिखाएँ",amenities:{WIFI:"वाई-फाई",PARKING:"पार्किंग",POOL:"पूल",GYM:"जिम",BREAKFAST:"नाश्ता"},advanced:{guestRating:"अतिथि रेटिंग",anyRating:"कोई भी रेटिंग",propertyType:"प्रॉपर्टी का प्रकार",anyProperty:"कोई भी प्रकार",topRated:"सबसे अधिक अतिथि रेटिंग",dealsOnly:"केवल ऑफ़र",accessible:"व्हीलचेयर अनुकूल",hotel:"होटल",resort:"रिसॉर्ट",apartment:"अपार्टमेंट",villa:"विला"}},
  pt:{destinationMatched:"Destino identificado",unavailableTitle:"A pesquisa está temporariamente indisponível",unavailableBody:"Os dados dos hotéis não estão acessíveis no momento. Tente novamente em instantes.",sponsored:"Patrocinado",showMore:"Mostrar mais hotéis",amenities:{WIFI:"Wi-Fi",PARKING:"Estacionamento",POOL:"Piscina",GYM:"Academia",BREAKFAST:"Café da manhã"},advanced:{guestRating:"Avaliação dos hóspedes",anyRating:"Qualquer avaliação",propertyType:"Tipo de acomodação",anyProperty:"Qualquer tipo",topRated:"Melhor avaliação",dealsOnly:"Somente ofertas",accessible:"Acessível para cadeiras de rodas",hotel:"Hotel",resort:"Resort",apartment:"Apartamento",villa:"Villa"}},
  id:{destinationMatched:"Destinasi dikenali",unavailableTitle:"Pencarian sementara tidak tersedia",unavailableBody:"Data hotel sedang tidak dapat diakses. Silakan coba lagi sebentar lagi.",sponsored:"Bersponsor",showMore:"Tampilkan hotel lainnya",amenities:{WIFI:"Wi-Fi",PARKING:"Parkir",POOL:"Kolam renang",GYM:"Pusat kebugaran",BREAKFAST:"Sarapan"},advanced:{guestRating:"Ulasan tamu",anyRating:"Semua penilaian",propertyType:"Jenis properti",anyProperty:"Semua jenis",topRated:"Penilaian tamu tertinggi",dealsOnly:"Hanya promo",accessible:"Akses kursi roda",hotel:"Hotel",resort:"Resor",apartment:"Apartemen",villa:"Vila"}},
  th:{destinationMatched:"พบจุดหมายแล้ว",unavailableTitle:"การค้นหาไม่พร้อมใช้งานชั่วคราว",unavailableBody:"ขณะนี้ไม่สามารถเข้าถึงข้อมูลโรงแรมได้ โปรดลองอีกครั้งในอีกสักครู่",sponsored:"ผู้สนับสนุน",showMore:"แสดงโรงแรมเพิ่มเติม",amenities:{WIFI:"Wi-Fi",PARKING:"ที่จอดรถ",POOL:"สระว่ายน้ำ",GYM:"ฟิตเนส",BREAKFAST:"อาหารเช้า"},advanced:{guestRating:"คะแนนจากผู้เข้าพัก",anyRating:"ทุกคะแนน",propertyType:"ประเภทที่พัก",anyProperty:"ทุกประเภท",topRated:"คะแนนผู้เข้าพักสูงสุด",dealsOnly:"เฉพาะดีล",accessible:"รองรับรถเข็น",hotel:"โรงแรม",resort:"รีสอร์ต",apartment:"อพาร์ตเมนต์",villa:"วิลลา"}},
};

export function searchUiCopy(locale:GuestLocale):SearchUiCopy{return COPY[locale];}
