import type {GuestLocale} from "./guest-market";

type Copy=Readonly<{
  adminSession:string;unexpected:string;closedSessions:(count:number)=>string;
  emailEyebrow:string;emailTitle:string;alreadyVerified:string;verificationSent:string;requestFailed:string;verified:string;needsVerification:string;sending:string;sendLink:string;
}>;
const COPY:Record<GuestLocale,Copy>={
  en:{adminSession:"Admin portal session",unexpected:"An unexpected error occurred",closedSessions:n=>`${n} other session${n===1?"":"s"} closed.`,emailEyebrow:"Verified email",emailTitle:"Verify account email",alreadyVerified:"Email is already verified.",verificationSent:"Verification link sent. Check your inbox.",requestFailed:"Request failed",verified:"Verified",needsVerification:"Verification needed",sending:"Sending…",sendLink:"Send verification link"},
  ar:{adminSession:"جلسة بوابة الإدارة",unexpected:"حدث خطأ غير متوقع",closedSessions:n=>`تم إغلاق ${n} جلسة أخرى.`,emailEyebrow:"البريد الآمن",emailTitle:"تأكيد بريد الحساب",alreadyVerified:"البريد مؤكد بالفعل.",verificationSent:"أرسلنا رابط التأكيد. تحقق من صندوق الوارد.",requestFailed:"تعذر تنفيذ الطلب",verified:"مؤكد",needsVerification:"بحاجة للتأكيد",sending:"جارٍ الإرسال…",sendLink:"إرسال رابط التأكيد"},
  zh:{adminSession:"管理后台会话",unexpected:"发生了意外错误",closedSessions:n=>`已关闭 ${n} 个其他会话。`,emailEyebrow:"已验证邮箱",emailTitle:"验证账户邮箱",alreadyVerified:"邮箱已验证。",verificationSent:"验证链接已发送，请检查收件箱。",requestFailed:"请求失败",verified:"已验证",needsVerification:"需要验证",sending:"正在发送…",sendLink:"发送验证链接"},
  fr:{adminSession:"Session du portail administrateur",unexpected:"Une erreur inattendue s’est produite",closedSessions:n=>`${n} autre${n>1?"s":""} session${n>1?"s":""} fermée${n>1?"s":""}.`,emailEyebrow:"E-mail vérifié",emailTitle:"Vérifier l’e-mail du compte",alreadyVerified:"L’e-mail est déjà vérifié.",verificationSent:"Lien de vérification envoyé. Consultez votre boîte de réception.",requestFailed:"La demande a échoué",verified:"Vérifié",needsVerification:"Vérification requise",sending:"Envoi…",sendLink:"Envoyer le lien de vérification"},
  de:{adminSession:"Admin-Portal-Sitzung",unexpected:"Ein unerwarteter Fehler ist aufgetreten",closedSessions:n=>`${n} weitere Sitzung${n===1?"":"en"} geschlossen.`,emailEyebrow:"Bestätigte E-Mail",emailTitle:"Konto-E-Mail bestätigen",alreadyVerified:"Die E-Mail ist bereits bestätigt.",verificationSent:"Bestätigungslink gesendet. Prüfen Sie Ihren Posteingang.",requestFailed:"Anfrage fehlgeschlagen",verified:"Bestätigt",needsVerification:"Bestätigung erforderlich",sending:"Wird gesendet…",sendLink:"Bestätigungslink senden"},
  es:{adminSession:"Sesión del portal de administración",unexpected:"Se produjo un error inesperado",closedSessions:n=>`${n} sesión${n===1?"":"es"} adicional${n===1?"":"es"} cerrada${n===1?"":"s"}.`,emailEyebrow:"Correo verificado",emailTitle:"Verificar correo de la cuenta",alreadyVerified:"El correo ya está verificado.",verificationSent:"Enlace de verificación enviado. Revisa tu bandeja de entrada.",requestFailed:"La solicitud falló",verified:"Verificado",needsVerification:"Se necesita verificación",sending:"Enviando…",sendLink:"Enviar enlace de verificación"},
  it:{adminSession:"Sessione portale amministratore",unexpected:"Si è verificato un errore imprevisto",closedSessions:n=>`${n} session${n===1?"e":"i"} aggiuntiv${n===1?"a":"e"} chius${n===1?"a":"e"}.`,emailEyebrow:"E-mail verificata",emailTitle:"Verifica e-mail dell’account",alreadyVerified:"L’e-mail è già verificata.",verificationSent:"Link di verifica inviato. Controlla la posta in arrivo.",requestFailed:"Richiesta non riuscita",verified:"Verificata",needsVerification:"Verifica necessaria",sending:"Invio…",sendLink:"Invia link di verifica"},
  tr:{adminSession:"Yönetici portalı oturumu",unexpected:"Beklenmeyen bir hata oluştu",closedSessions:n=>`${n} diğer oturum kapatıldı.`,emailEyebrow:"Doğrulanmış e-posta",emailTitle:"Hesap e-postasını doğrula",alreadyVerified:"E-posta zaten doğrulanmış.",verificationSent:"Doğrulama bağlantısı gönderildi. Gelen kutunuzu kontrol edin.",requestFailed:"İstek başarısız oldu",verified:"Doğrulandı",needsVerification:"Doğrulama gerekli",sending:"Gönderiliyor…",sendLink:"Doğrulama bağlantısı gönder"},
  ru:{adminSession:"Сессия портала администратора",unexpected:"Произошла непредвиденная ошибка",closedSessions:n=>`Закрыто других сессий: ${n}.`,emailEyebrow:"Подтверждённая почта",emailTitle:"Подтвердить e-mail аккаунта",alreadyVerified:"E-mail уже подтверждён.",verificationSent:"Ссылка подтверждения отправлена. Проверьте почту.",requestFailed:"Запрос не выполнен",verified:"Подтверждено",needsVerification:"Требуется подтверждение",sending:"Отправка…",sendLink:"Отправить ссылку подтверждения"},
  ja:{adminSession:"管理者ポータルのセッション",unexpected:"予期しないエラーが発生しました",closedSessions:n=>`他のセッションを ${n} 件終了しました。`,emailEyebrow:"確認済みメール",emailTitle:"アカウントのメールを確認",alreadyVerified:"メールはすでに確認済みです。",verificationSent:"確認リンクを送信しました。受信トレイをご確認ください。",requestFailed:"リクエストに失敗しました",verified:"確認済み",needsVerification:"確認が必要",sending:"送信中…",sendLink:"確認リンクを送信"},
  ko:{adminSession:"관리자 포털 세션",unexpected:"예기치 않은 오류가 발생했습니다",closedSessions:n=>`다른 세션 ${n}개를 종료했습니다.`,emailEyebrow:"확인된 이메일",emailTitle:"계정 이메일 확인",alreadyVerified:"이메일이 이미 확인되었습니다.",verificationSent:"확인 링크를 보냈습니다. 받은편지함을 확인하세요.",requestFailed:"요청에 실패했습니다",verified:"확인됨",needsVerification:"확인 필요",sending:"전송 중…",sendLink:"확인 링크 보내기"},
  hi:{adminSession:"एडमिन पोर्टल सत्र",unexpected:"एक अप्रत्याशित त्रुटि हुई",closedSessions:n=>`${n} अन्य सत्र बंद किए गए।`,emailEyebrow:"सत्यापित ईमेल",emailTitle:"खाता ईमेल सत्यापित करें",alreadyVerified:"ईमेल पहले से सत्यापित है।",verificationSent:"सत्यापन लिंक भेजा गया। अपना इनबॉक्स देखें।",requestFailed:"अनुरोध विफल हुआ",verified:"सत्यापित",needsVerification:"सत्यापन आवश्यक",sending:"भेजा जा रहा है…",sendLink:"सत्यापन लिंक भेजें"},
  pt:{adminSession:"Sessão do portal administrativo",unexpected:"Ocorreu um erro inesperado",closedSessions:n=>`${n} outra${n===1?"":"s"} sessão${n===1?"":"ões"} encerrada${n===1?"":"s"}.`,emailEyebrow:"E-mail verificado",emailTitle:"Verificar e-mail da conta",alreadyVerified:"O e-mail já está verificado.",verificationSent:"Link de verificação enviado. Confira sua caixa de entrada.",requestFailed:"A solicitação falhou",verified:"Verificado",needsVerification:"Verificação necessária",sending:"Enviando…",sendLink:"Enviar link de verificação"},
  id:{adminSession:"Sesi portal admin",unexpected:"Terjadi kesalahan tak terduga",closedSessions:n=>`${n} sesi lain ditutup.`,emailEyebrow:"Email terverifikasi",emailTitle:"Verifikasi email akun",alreadyVerified:"Email sudah terverifikasi.",verificationSent:"Tautan verifikasi dikirim. Periksa kotak masuk Anda.",requestFailed:"Permintaan gagal",verified:"Terverifikasi",needsVerification:"Perlu verifikasi",sending:"Mengirim…",sendLink:"Kirim tautan verifikasi"},
  th:{adminSession:"เซสชันพอร์ทัลผู้ดูแล",unexpected:"เกิดข้อผิดพลาดที่ไม่คาดคิด",closedSessions:n=>`ปิดเซสชันอื่นแล้ว ${n} เซสชัน`,emailEyebrow:"อีเมลยืนยันแล้ว",emailTitle:"ยืนยันอีเมลบัญชี",alreadyVerified:"อีเมลได้รับการยืนยันแล้ว",verificationSent:"ส่งลิงก์ยืนยันแล้ว โปรดตรวจสอบกล่องจดหมาย",requestFailed:"คำขอล้มเหลว",verified:"ยืนยันแล้ว",needsVerification:"ต้องยืนยัน",sending:"กำลังส่ง…",sendLink:"ส่งลิงก์ยืนยัน"},
};
export function securityUiCopy(locale:GuestLocale):Copy{return COPY[locale];}
