import Link from "next/link";
import { Baby, BadgeCheck, Bath, BedDouble, ChevronLeft, CircleCheck, CreditCard, Gift, Home, Image as ImageIcon, MapPin, Ruler, ShieldCheck, Star, UserRound, Utensils } from "lucide-react";
import { calculateLoyaltyPoints } from "@platform/core";
import { publicStaySchema } from "@platform/contracts";
import { getPublicHotelDetails, getPublicHotelReviews } from "@platform/server";
import { CustomerHeader } from "@/components/customer-header";
import { dictionary, interpolate, type Locale } from "@/lib/i18n";
import { requestLocale } from "@/lib/request-locale";
import { defaultStayDates } from "@/lib/stay-dates";
import { PriceWatch } from "./price-watch";

type SearchParams = Record<string, string | string[] | undefined>;

export default async function HotelPage({params, searchParams}: {params: Promise<{id:string}>; searchParams: Promise<SearchParams>}) {
  const [{id},query,locale]=await Promise.all([params,searchParams,requestLocale()]);
  const copy=dictionary(locale);
  const defaults=defaultStayDates();
  const parsed=publicStaySchema.safeParse({arrival:first(query.arrival)??defaults.arrival,departure:first(query.departure)??defaults.departure,adults:first(query.adults)??"2",children:first(query.children)??"0"});
  const stay=parsed.success?parsed.data:{arrival:defaults.arrival,departure:defaults.departure,adults:2,children:0};
  const [hotel,reviewData]=await Promise.all([getPublicHotelDetails(id,stay),getPublicHotelReviews(id,6)]);
  const cheapest=hotel.offers[0]??null;
  const roomGroups=groupOffers(hotel.offers);
  const cheapestPoints=cheapest?calculateLoyaltyPoints(cheapest.amounts.base,"MEMBER",hotel.currency):0;
  return <main className="hotelExperience">
    <CustomerHeader/>
    <section className="shell hotelDetailSection">
      <Link className="backLink" href={`/search?destination=${encodeURIComponent(hotel.city)}&arrival=${stay.arrival}&departure=${stay.departure}&adults=${stay.adults}&children=${stay.children}`}><ChevronLeft size={16}/>{interpolate(copy.hotel.back,{city:hotel.city})}</Link>
      <div className="premiumHotelHead"><div><div className="hotelBadges"><span><BadgeCheck size={14}/>{hotel.slug.startsWith("demo-")?copy.hotel.demoProperty:copy.hotel.verified}</span>{hotel.starRating&&<span><Star size={14} fill="currentColor"/>{hotel.starRating} {copy.hotel.star}</span>}</div><h1>{hotel.name}</h1><p><MapPin size={16}/>{hotel.area?`${hotel.area}, `:""}{hotel.city} · {hotel.address}</p>{hotel.reviewSummary.overall!==null&&<div className="hotelRatingSummary"><strong>{hotel.reviewSummary.overall.toFixed(1)}</strong><span>{copy.hotel.guestSignal}<br/><small>{hotel.reviewSummary.count} {hotel.reviewSummary.count===1?copy.hotel.stayReview:copy.hotel.stayReviews}</small></span></div>}</div><div className="hotelQuickFacts"><div><span>{copy.hotel.checkIn}</span><strong>{hotel.checkInTime??copy.hotel.propertyPolicy}</strong></div><div><span>{copy.hotel.checkOut}</span><strong>{hotel.checkOutTime??copy.hotel.propertyPolicy}</strong></div></div></div>
      {hotel.photos.length?<div className="premiumGallery">{hotel.photos.slice(0,5).map((photo,index)=><img className={`galleryPhoto${index+1}`} key={`${photo.url}-${photo.sortOrder}`} src={photo.url} alt={photo.alt??hotel.name} loading={index===0?"eager":"lazy"} decoding="async"/>)}</div>:<div className="hotelMediaEmpty"><span>{copy.hotel.noPhotos}</span></div>}
      <div className="hotelTrustBar"><span><ShieldCheck size={17}/>{copy.hotel.finalPrice}</span><span><BadgeCheck size={17}/>{copy.hotel.liveInventory}</span><span><BadgeCheck size={17}/>{copy.hotel.verifiedReviews}</span></div>
      <div className="hotelInfoGrid"><div className="hotelAbout"><span className="eyebrow">{copy.hotel.property}</span><h2>{interpolate(copy.hotel.about,{hotel:hotel.name})}</h2>{hotel.description?<p>{hotel.description}</p>:<p className="muted">{copy.hotel.noDescription}</p>}</div><aside className="hotelFacilities"><span className="eyebrow">{copy.hotel.facilities}</span><div>{hotel.amenities.length?hotel.amenities.map((amenity)=><span key={amenity.code}>{amenity.name}</span>):<p className="muted">{copy.hotel.noFacilities}</p>}</div></aside></div>
      <div className="availabilityCard"><div><span className="eyebrow">{copy.hotel.yourStay}</span><h2>{copy.hotel.chooseDates}</h2></div><form className="availabilityForm" method="get"><label><span>{copy.hotel.checkIn}</span><input name="arrival" type="date" defaultValue={stay.arrival} required/></label><label><span>{copy.hotel.checkOut}</span><input name="departure" type="date" defaultValue={stay.departure} required/></label><label><span>{copy.hotel.adults}</span><input name="adults" type="number" min="1" max="20" defaultValue={stay.adults}/></label><label><span>{copy.hotel.children}</span><input name="children" type="number" min="0" max="20" defaultValue={stay.children}/></label><button type="submit">{copy.hotel.availability}</button></form></div>
      {!parsed.success&&<div className="inlineWarning">{copy.hotel.invalidStay}</div>}
      {cheapest&&<PriceWatch locale={locale} hotelId={hotel.id} arrival={stay.arrival} departure={stay.departure} adults={stay.adults} children={stay.children} currentTotal={cheapest.total} currency={hotel.currency}/>} 
      <div className="hotelBookingWorkspace">
        <div className="hotelBookingMain">
          <div className="rateSectionHead"><div><span className="eyebrow">{copy.hotel.available}</span><h2>{hotel.offers.length} {hotel.offers.length===1?copy.hotel.liveRate:copy.hotel.liveRates}</h2><p>{hotel.stay.nights} {hotel.stay.nights===1?copy.hotel.night:copy.hotel.nights} · {copy.hotel.totalsNote}</p></div>{cheapest&&<div><span>{copy.hotel.from}</span><strong>{cheapest.total.toFixed(2)} {hotel.currency}</strong><small>{copy.hotel.stayTotal}</small></div>}</div>
          {hotel.offers.length===0?<div className="premiumEmpty"><h3>{copy.hotel.noRooms}</h3><p>{copy.hotel.noRoomsBody}</p></div>:<div className="roomOfferList" id="room-offers">{roomGroups.map(({room,offers})=>{
            const lowInventory=Math.min(...offers.map((offer)=>offer.availableToSell));
            return <article className="roomOfferCard" key={room.roomTypeId}>
              <section className="publicRoomProduct">
                <div className="publicRoomMedia">{room.roomPhotos[0]?<img src={room.roomPhotos[0].url} alt={room.roomPhotos[0].alt??room.roomName}/>:<><ImageIcon size={28}/><span>{locale==="ar"?"صورة الغرفة قيد الإضافة":"Room photo pending"}</span></>}</div>
                <div className="publicRoomContent"><span className="eyebrow">{unitTypeLabel(room.unitType,locale)}</span><h3>{room.roomName}</h3><div className="publicRoomFits"><strong>{locale==="ar"?"تتسع:":"Fits:"}</strong><span aria-label={`${room.maxGuests} guests`}>{Array.from({length:Math.min(room.maxGuests,6)},(_,index)=><UserRound size={18} fill="currentColor" key={index}/>)}{room.maxGuests>6&&<b>× {room.maxGuests}</b>}</span><small>{room.maxAdults} {copy.hotel.adults}{room.maxChildren?` · ${room.maxChildren} ${copy.hotel.children}`:""}{room.maxInfants?` · ${room.maxInfants} ${locale==="ar"?"رضّع":"infants"}`:""}</small></div>
                <div className="publicBedLayout">{groupBeds(room.beds).map(([area,beds])=><p key={area}><strong>{bedAreaLabel(area,locale)}:</strong> {beds.map((bed)=>`${bed.quantity} ${bedLabel(bed.type,locale)}`).join(" + ")} <BedDouble size={16}/></p>)}</div>
                {(room.cribCount>0||room.extraBedCount>0)&&<div className="publicRoomExtras">{room.cribCount>0&&<span><Baby size={15}/>{locale==="ar"?"مهد متاح عند الطلب":"Crib available on request"}</span>}{room.extraBedCount>0&&<span><BedDouble size={15}/>{locale==="ar"?"سرير إضافي عند الطلب":"Extra bed on request"}</span>}</div>}
                <div className="publicRoomTags"><span><Home size={14}/>{unitTypeLabel(room.unitType,locale)}</span>{room.sizeValue&&<span><Ruler size={14}/>{room.sizeValue} {room.sizeUnit==="SQM"?"m²":"ft²"}</span>}{room.privateBathroom&&<span><Bath size={14}/>{locale==="ar"?"حمام خاص":"Private bathroom"}</span>}{room.roomAmenities.slice(0,8).map((amenity)=><span key={amenity.code}>{roomFacilityLabel(amenity.code,amenity.name,locale)}</span>)}</div>
                {room.roomDescription&&<p className="publicRoomDescription">{room.roomDescription}</p>}{lowInventory<=3&&<strong className="scarcityNote">{copy.hotel.only} {lowInventory} {copy.hotel.left}</strong>}</div>
              </section>
              <section className="publicRateOptions">
                <div className="publicRateHead"><span>{locale==="ar"?"العرض والوجبة":"Offer & meal"}</span><span>{copy.hotel.cancellation}</span><span>{locale==="ar"?"الدفع والمزايا":"Payment & benefits"}</span><span>{copy.hotel.finalTotal}</span></div>
                {offers.map((offer)=>{
                  const points=calculateLoyaltyPoints(offer.amounts.base,"MEMBER",hotel.currency);
                  const badges=rateBadges(offer,offers,locale);
                  return <div className="publicRateRow" key={offer.ratePlanId}>
                    <div className="publicRateCell packageCell"><span>{copy.hotel.package}</span><h4>{mealPlan(offer.mealPlan,locale)}</h4><div className="rateBadges">{badges.map((badge)=><span className={`rateBadge ${badge.kind}`} key={badge.text}>{badge.text}</span>)}</div>{offer.promotion&&<strong className="dealPill">{offer.promotion.discountPercent}% {locale==="ar"?"خصم":"off"} · {offer.promotion.name}</strong>}</div>
                    <div className="publicRateCell"><span>{copy.hotel.cancellation}</span><h4 className="rateCancellationTitle">{offer.cancellationPolicy.name}</h4><p className={offer.freeCancellationNow?"positiveText":"ratePenalty"}>{offer.freeCancellationNow?<><CircleCheck size={13}/> {copy.hotel.freeNow}</>:<>{copy.hotel.currentPenalty} {offer.cancellationNow.penaltyAmount.toFixed(2)} {hotel.currency}</>}</p></div>
                    <div className="publicRateCell"><span>{locale==="ar"?"يشمل":"Includes"}</span><div className="rateFeatureChips"><span><Utensils size={12}/>{mealPlan(offer.mealPlan,locale)}</span>{offer.paymentModes.map((mode)=><span className={mode==="PAY_AT_HOTEL"?"positive":""} key={mode}><CreditCard size={12}/>{mode==="PAY_AT_HOTEL"?copy.hotel.payHotel:copy.hotel.payNow}</span>)}</div>{points>0&&<p className="rateReward"><Gift size={13}/>{locale==="ar"?`اكسب من ${points.toLocaleString("en-US")} نقطة HandMeKey`:`Earn at least ${points.toLocaleString("en-US")} HandMeKey points`}</p>}</div>
                    <div className="publicRateAction"><span>{copy.hotel.finalTotal}</span><div className="ratePrice"><strong>{offer.total.toFixed(2)} {hotel.currency}</strong><small>{hotel.stay.nights} {hotel.stay.nights===1?copy.hotel.night:copy.hotel.nights}</small></div><small>{offer.averageNightlyTotal.toFixed(2)} {copy.hotel.average}</small><small className="rateBreakdown">{copy.hotel.base} {offer.amounts.base.toFixed(2)} + {copy.hotel.service} {offer.amounts.service.toFixed(2)} + {copy.hotel.tax} {offer.amounts.tax.toFixed(2)}</small>{offer.availableToSell<=3&&<span className="rateInventory">{copy.hotel.only} {offer.availableToSell} {copy.hotel.left}</span>}<Link className="bookRateButton" href={checkoutHref(hotel.id,offer.roomTypeId,offer.ratePlanId,stay.arrival,stay.departure,stay.adults,stay.children)}>{copy.hotel.choose}</Link></div>
                  </div>;
                })}
              </section>
            </article>;
          })}</div>}
        </div>
        {cheapest&&<aside className="hotelBookingRail">
          <div className="hotelRailTop"><span>{locale==="ar"?"أفضل سعر مباشر متاح الآن":"Best live rate available now"}</span><strong>{cheapest.total.toFixed(2)} {hotel.currency}</strong><small>{hotel.stay.nights} {hotel.stay.nights===1?copy.hotel.night:copy.hotel.nights} · {copy.hotel.stayTotal}</small>{cheapestPoints>0&&<div className="hotelRailReward"><Gift size={15}/>{locale==="ar"?`من ${cheapestPoints.toLocaleString("en-US")} نقطة Rewards`:`From ${cheapestPoints.toLocaleString("en-US")} Rewards points`}</div>}</div>
          <div className="hotelRailBody"><div className="hotelRailFacts"><div><span>{copy.hotel.checkIn}</span><strong>{stay.arrival}</strong></div><div><span>{copy.hotel.checkOut}</span><strong>{stay.departure}</strong></div><div><span>{locale==="ar"?"الضيوف":"Guests"}</span><strong>{stay.adults} {copy.hotel.adults}{stay.children?` · ${stay.children} ${copy.hotel.children}`:""}</strong></div><div><span>{locale==="ar"?"خيارات الأسعار":"Rate choices"}</span><strong>{hotel.offers.length}</strong></div></div><div><a className="hotelRailButton" href="#room-offers">{locale==="ar"?"شاهد الغرف والأسعار":"See rooms & rates"}</a><Link className="hotelRailLink" href={`/rewards/${locale}`}>{locale==="ar"?"اعرف أكثر عن HandMeKey Rewards":"Learn about HandMeKey Rewards"}</Link><div className="hotelRailTrust"><span><ShieldCheck size={13}/>{copy.hotel.finalPrice}</span><span><BadgeCheck size={13}/>{copy.hotel.liveInventory}</span><span><BadgeCheck size={13}/>{copy.hotel.verifiedReviews}</span></div></div></div>
        </aside>}
      </div>
      <section className="reviewsSection"><div className="premiumSectionHead"><div><span className="eyebrow">{copy.hotel.verifiedStays}</span><h2>{copy.hotel.reviewsTitle}</h2></div></div>{reviewData.summary.count===0?<div className="premiumEmpty"><h3>{copy.hotel.noReviews}</h3><p>{copy.hotel.noReviewsBody}</p></div>:<><div className="reviewScoreGrid"><div className="reviewOverall"><strong>{reviewData.summary.overall?.toFixed(1)}</strong><span>{copy.hotel.outOf10}</span><small>{reviewData.summary.count} {copy.hotel.verifiedStaysCount}</small></div>{[[copy.hotel.cleanliness,reviewData.summary.cleanliness],[copy.hotel.staff,reviewData.summary.staff],[copy.hotel.location,reviewData.summary.location],[copy.hotel.comfort,reviewData.summary.comfort],[copy.hotel.value,reviewData.summary.value]].map(([label,value])=><div className="reviewMetric" key={String(label)}><span>{label}</span><strong>{typeof value==="number"?value.toFixed(1):"—"}</strong></div>)}</div><div className="reviewCards">{reviewData.reviews.map((review)=><article key={review.id}><div className="reviewCardTop"><strong>{review.overall}/10</strong><span>{review.guestName}<small>{copy.hotel.verifiedStay} · {review.stayCompleted}</small></span></div>{review.title&&<h3>{review.title}</h3>}<p>{review.comment}</p>{review.hotelReply&&<div className="hotelReply"><strong>{copy.hotel.propertyResponse}</strong><p>{review.hotelReply}</p></div>}</article>)}</div></>}
      </section>
    </section>
  </main>;
}

function first(value:string|string[]|undefined):string|undefined{return Array.isArray(value)?value[0]:value;}
function checkoutHref(hotelId:string,roomTypeId:string,ratePlanId:string,arrival:string,departure:string,adults:number,children:number){const query=new URLSearchParams({hotelId,roomTypeId,ratePlanId,arrival,departure,adults:String(adults),children:String(children)});return `/checkout?${query.toString()}`;}
function mealPlan(value:string,locale:Locale){const copy=dictionary(locale).hotel;if(value==="BREAKFAST")return copy.breakfast;if(value==="HALF_BOARD")return copy.halfBoard;if(value==="FULL_BOARD")return copy.fullBoard;return copy.roomOnly;}
type Offer = Awaited<ReturnType<typeof getPublicHotelDetails>>["offers"][number];
function groupOffers(offers:Offer[]){const groups=new Map<string,{room:Offer;offers:Offer[]}>();for(const offer of offers){const group=groups.get(offer.roomTypeId);if(group)group.offers.push(offer);else groups.set(offer.roomTypeId,{room:offer,offers:[offer]});}return [...groups.values()];}
function rateBadges(offer:Offer,offers:Offer[],locale:Locale):Array<{text:string;kind:"best"|"flex"|"included"}>{const badges:Array<{text:string;kind:"best"|"flex"|"included"}>=[];const cheapest=Math.min(...offers.map((candidate)=>candidate.total));if(Math.abs(offer.total-cheapest)<0.01)badges.push({text:locale==="ar"?"أفضل سعر":"Best price",kind:"best"});if(offer.freeCancellationNow)badges.push({text:locale==="ar"?"مرن":"Flexible",kind:"flex"});if(offer.mealPlan==="FULL_BOARD")badges.push({text:locale==="ar"?"إقامة شاملة":"Most included",kind:"included"});return badges.slice(0,2);}
function groupBeds(beds:Offer["beds"]){const groups=new Map<string,Offer["beds"]>();for(const bed of beds)groups.set(bed.area,[...(groups.get(bed.area)??[]),bed]);return [...groups.entries()];}
function bedLabel(value:string,locale:Locale){const en:Record<string,string>={SINGLE:"single bed",DOUBLE:"double bed",QUEEN:"queen bed",KING:"king bed",EXTRA_LARGE_DOUBLE:"extra-large double bed",SOFA_BED:"sofa bed",BUNK_BED:"bunk bed",FUTON:"futon bed",MURPHY_BED:"Murphy bed"};const ar:Record<string,string>={SINGLE:"سرير فردي",DOUBLE:"سرير مزدوج",QUEEN:"سرير كوين",KING:"سرير كينغ",EXTRA_LARGE_DOUBLE:"سرير مزدوج كبير جدًا",SOFA_BED:"سرير أريكة",BUNK_BED:"سرير بطابقين",FUTON:"سرير فوتون",MURPHY_BED:"سرير جداري"};return (locale==="ar"?ar:en)[value]??value;}
function bedAreaLabel(value:string,locale:Locale){if(locale!=="ar")return value;const bedroom=/^bedroom\s*(\d+)?$/i.exec(value.trim());if(bedroom)return bedroom[1]?`غرفة النوم ${bedroom[1]}`:"غرفة النوم";if(/^living room$/i.test(value.trim()))return "غرفة المعيشة";return value;}
function unitTypeLabel(value:string,locale:Locale){const en:Record<string,string>={ROOM:"Room",STUDIO:"Entire studio",SUITE:"Suite",APARTMENT:"Entire apartment",VILLA:"Villa",CHALET:"Chalet",BUNGALOW:"Bungalow",HOLIDAY_HOME:"Holiday home",DORMITORY_ROOM:"Dormitory room",BED_IN_DORMITORY:"Bed in dormitory"};const ar:Record<string,string>={ROOM:"غرفة",STUDIO:"استوديو كامل",SUITE:"جناح",APARTMENT:"شقة كاملة",VILLA:"فيلا",CHALET:"شاليه",BUNGALOW:"بنغلو",HOLIDAY_HOME:"بيت عطلات",DORMITORY_ROOM:"غرفة مشتركة",BED_IN_DORMITORY:"سرير في غرفة مشتركة"};return (locale==="ar"?ar:en)[value]??value;}
function roomFacilityLabel(code:string,fallback:string,locale:Locale){if(locale!=="ar")return fallback;const labels:Record<string,string>={AIR_CONDITIONING:"تكييف",FLAT_SCREEN_TV:"تلفاز بشاشة مسطحة",SOUNDPROOFING:"عزل صوتي",PRIVATE_ENTRANCE:"مدخل خاص",REFRIGERATOR:"ثلاجة",TEA_COFFEE:"آلة شاي وقهوة",BALCONY:"شرفة",GARDEN_VIEW:"إطلالة على الحديقة",POOL_VIEW:"إطلالة على المسبح",CITY_VIEW:"إطلالة على المدينة",KITCHENETTE:"مطبخ صغير",WIFI:"واي فاي",SAFE:"خزنة",MINIBAR:"ميني بار",DESK:"مكتب",WASHING_MACHINE:"غسالة",SEATING_AREA:"منطقة جلوس",SEA_VIEW:"إطلالة بحرية",PRIVATE_POOL:"مسبح خاص"};return labels[code]??fallback;}
