import Link from "next/link";
import { BadgeCheck, ChevronLeft, MapPin, ShieldCheck, Star } from "lucide-react";
import { publicStaySchema } from "@platform/contracts";
import { getPublicHotelDetails, getPublicHotelReviews } from "@platform/server";
import { CustomerHeader } from "@/components/customer-header";
import { defaultStayDates } from "@/lib/stay-dates";
import { PriceWatch } from "./price-watch";

type SearchParams = Record<string, string | string[] | undefined>;

export default async function HotelPage({params, searchParams}: {params: Promise<{id:string}>; searchParams: Promise<SearchParams>}) {
  const {id}=await params;
  const query=await searchParams;
  const defaults=defaultStayDates();
  const parsed=publicStaySchema.safeParse({arrival:first(query.arrival)??defaults.arrival,departure:first(query.departure)??defaults.departure,adults:first(query.adults)??"2",children:first(query.children)??"0"});
  const stay=parsed.success?parsed.data:{arrival:defaults.arrival,departure:defaults.departure,adults:2,children:0};
  const [hotel,reviewData]=await Promise.all([getPublicHotelDetails(id,stay),getPublicHotelReviews(id,6)]);
  const cheapest=hotel.offers[0]??null;
  return <main className="hotelExperience">
    <CustomerHeader/>
    <section className="shell hotelDetailSection">
      <Link className="backLink" href={`/search?destination=${encodeURIComponent(hotel.city)}&arrival=${stay.arrival}&departure=${stay.departure}&adults=${stay.adults}&children=${stay.children}`}><ChevronLeft size={16}/>Back to {hotel.city} stays</Link>
      <div className="premiumHotelHead"><div><div className="hotelBadges"><span><BadgeCheck size={14}/>Verified property</span>{hotel.starRating&&<span><Star size={14} fill="currentColor"/>{hotel.starRating} star</span>}</div><h1>{hotel.name}</h1><p><MapPin size={16}/>{hotel.area?`${hotel.area}, `:""}{hotel.city} · {hotel.address}</p>{hotel.reviewSummary.overall!==null&&<div className="hotelRatingSummary"><strong>{hotel.reviewSummary.overall.toFixed(1)}</strong><span>Excellent guest signal<br/><small>{hotel.reviewSummary.count} verified stay review{hotel.reviewSummary.count===1?"":"s"}</small></span></div>}</div><div className="hotelQuickFacts"><div><span>Check-in</span><strong>{hotel.checkInTime??"Property policy"}</strong></div><div><span>Check-out</span><strong>{hotel.checkOutTime??"Property policy"}</strong></div></div></div>
      {hotel.photos.length?<div className="premiumGallery">{hotel.photos.slice(0,5).map((photo,index)=><img className={`galleryPhoto${index+1}`} key={`${photo.url}-${photo.sortOrder}`} src={photo.url} alt={photo.alt??hotel.name}/>)}</div>:<div className="hotelMediaEmpty"><span>Property photos are not published yet.</span></div>}
      <div className="hotelTrustBar"><span><ShieldCheck size={17}/>Final price before booking</span><span><BadgeCheck size={17}/>Live room inventory</span><span><BadgeCheck size={17}/>Verified-stay reviews only</span></div>
      <div className="hotelInfoGrid"><div className="hotelAbout"><span className="eyebrow">The property</span><h2>About {hotel.name}</h2>{hotel.description?<p>{hotel.description}</p>:<p className="muted">The property has not published a description yet.</p>}</div><aside className="hotelFacilities"><span className="eyebrow">Facilities</span><div>{hotel.amenities.length?hotel.amenities.map((amenity)=><span key={amenity.code}>{amenity.name}</span>):<p className="muted">Facilities have not been published yet.</p>}</div></aside></div>
      <div className="availabilityCard"><div><span className="eyebrow">Your stay</span><h2>Choose dates and see the live total.</h2></div><form className="availabilityForm" method="get"><label><span>Check in</span><input name="arrival" type="date" defaultValue={stay.arrival} required/></label><label><span>Check out</span><input name="departure" type="date" defaultValue={stay.departure} required/></label><label><span>Adults</span><input name="adults" type="number" min="1" max="20" defaultValue={stay.adults}/></label><label><span>Children</span><input name="children" type="number" min="0" max="20" defaultValue={stay.children}/></label><button type="submit">Check availability</button></form></div>
      {!parsed.success&&<div className="inlineWarning">The requested stay was invalid, so HandMeKey loaded the next default dates.</div>}
      {cheapest&&<PriceWatch hotelId={hotel.id} arrival={stay.arrival} departure={stay.departure} adults={stay.adults} children={stay.children} currentTotal={cheapest.total} currency={hotel.currency}/>} 
      <div className="rateSectionHead"><div><span className="eyebrow">Available for your dates</span><h2>{hotel.offers.length} live rate plan{hotel.offers.length===1?"":"s"}</h2><p>{hotel.stay.nights} night{hotel.stay.nights===1?"":"s"} · final totals include configured service and mandatory charges.</p></div>{cheapest&&<div><span>From</span><strong>{cheapest.total.toFixed(2)} {hotel.currency}</strong><small>stay total</small></div>}</div>
      {hotel.offers.length===0?<div className="premiumEmpty"><h3>No rooms are sellable for this stay</h3><p>A rate only appears when every night has valid pricing, restrictions and remaining inventory.</p></div>:<div className="rateCards">{hotel.offers.map((offer)=><article className="rateCard" key={`${offer.roomTypeId}-${offer.ratePlanId}`}><div className="rateRoom"><span>Room</span><h3>{offer.roomName}</h3><p>Up to {offer.maxAdults} adult{offer.maxAdults===1?"":"s"}{offer.maxChildren?` + ${offer.maxChildren} children`:""}</p>{offer.availableToSell<=3&&<strong className="scarcityNote">Only {offer.availableToSell} left</strong>}</div><div className="ratePackage"><span>Package</span><h3>{mealPlan(offer.mealPlan)}</h3>{offer.promotion&&<strong className="dealPill">{offer.promotion.discountPercent}% off · {offer.promotion.name}</strong>}<p>{offer.paymentModes.map((mode)=>mode==="PAY_AT_HOTEL"?"Pay at hotel":"Pay now").join(" · ")}</p></div><div className="ratePolicy"><span>Cancellation</span><h3>{offer.cancellationPolicy.name}</h3><p className={offer.freeCancellationNow?"positiveText":"muted"}>{offer.freeCancellationNow?"Free cancellation right now":`Current penalty ${offer.cancellationNow.penaltyAmount.toFixed(2)} ${hotel.currency}`}</p></div><div className="ratePrice"><span>Final stay total</span><strong>{offer.total.toFixed(2)} {hotel.currency}</strong><small>{offer.averageNightlyTotal.toFixed(2)} average / night</small><small>Base {offer.amounts.base.toFixed(2)} + service {offer.amounts.service.toFixed(2)} + tax {offer.amounts.tax.toFixed(2)}</small><Link className="bookRateButton" href={checkoutHref(hotel.id,offer.roomTypeId,offer.ratePlanId,stay.arrival,stay.departure)}>Choose this room</Link></div></article>)}</div>}
      <section className="reviewsSection"><div className="premiumSectionHead"><div><span className="eyebrow">Verified stays</span><h2>What guests actually rated.</h2></div></div>{reviewData.summary.count===0?<div className="premiumEmpty"><h3>No verified reviews yet</h3><p>Only guests with completed bookings can publish a review.</p></div>:<><div className="reviewScoreGrid"><div className="reviewOverall"><strong>{reviewData.summary.overall?.toFixed(1)}</strong><span>out of 10</span><small>{reviewData.summary.count} verified stays</small></div>{[["Cleanliness",reviewData.summary.cleanliness],["Staff",reviewData.summary.staff],["Location",reviewData.summary.location],["Comfort",reviewData.summary.comfort],["Value",reviewData.summary.value]].map(([label,value])=><div className="reviewMetric" key={String(label)}><span>{label}</span><strong>{typeof value==="number"?value.toFixed(1):"—"}</strong></div>)}</div><div className="reviewCards">{reviewData.reviews.map((review)=><article key={review.id}><div className="reviewCardTop"><strong>{review.overall}/10</strong><span>{review.guestName}<small>Verified stay · {review.stayCompleted}</small></span></div>{review.title&&<h3>{review.title}</h3>}<p>{review.comment}</p>{review.hotelReply&&<div className="hotelReply"><strong>Property response</strong><p>{review.hotelReply}</p></div>}</article>)}</div></>}
      </section>
    </section>
  </main>;
}

function first(value:string|string[]|undefined):string|undefined{return Array.isArray(value)?value[0]:value;}
function checkoutHref(hotelId:string,roomTypeId:string,ratePlanId:string,arrival:string,departure:string){const query=new URLSearchParams({hotelId,roomTypeId,ratePlanId,arrival,departure});return `/checkout?${query.toString()}`;}
function mealPlan(value:string){if(value==="BREAKFAST")return "Breakfast included";if(value==="HALF_BOARD")return "Half board";if(value==="FULL_BOARD")return "Full board";return "Room only";}
