"use client";

import { useEffect } from "react";
import { localeFromLanguageTag, type GuestLocale } from "@/lib/guest-market";

type ExtraCopy=Readonly<{meal:string;breakfast:string;halfBoard:string;fullBoard:string;roomOnly:string;roomFeatures:string;kingBed:string;twinBeds:string;familyRoom:string;smoking:string;nonSmoking:string;balcony:string;seaView:string;connecting:string;benefits:string;dealsOnly:string;accessible:string;ratingSort:string}>;
const EN:ExtraCopy={meal:"Meal options",breakfast:"Breakfast included",halfBoard:"Half board",fullBoard:"Full board",roomOnly:"Room only",roomFeatures:"Room features",kingBed:"King bed",twinBeds:"Twin beds",familyRoom:"Family room",smoking:"Smoking room",nonSmoking:"Non-smoking",balcony:"Balcony",seaView:"Sea view",connecting:"Connecting rooms",benefits:"Deals & accessibility",dealsOnly:"Deals only",accessible:"Wheelchair accessible",ratingSort:"Guest rating"};
const COPY:Partial<Record<GuestLocale,ExtraCopy>>={
 ar:{meal:"خيارات الوجبات",breakfast:"الإفطار مشمول",halfBoard:"نصف إقامة",fullBoard:"إقامة كاملة",roomOnly:"الغرفة فقط",roomFeatures:"مواصفات الغرفة",kingBed:"سرير كينغ",twinBeds:"سريران منفصلان",familyRoom:"غرفة عائلية",smoking:"غرفة تدخين",nonSmoking:"لغير المدخنين",balcony:"شرفة",seaView:"إطلالة بحرية",connecting:"غرف متصلة",benefits:"العروض وسهولة الوصول",dealsOnly:"العروض فقط",accessible:"مناسب للكراسي المتحركة",ratingSort:"تقييم الضيوف"},
 zh:{meal:"餐食选项",breakfast:"含早餐",halfBoard:"半膳",fullBoard:"全膳",roomOnly:"仅住宿",roomFeatures:"客房设施",kingBed:"特大床",twinBeds:"双床",familyRoom:"家庭房",smoking:"吸烟房",nonSmoking:"禁烟房",balcony:"阳台",seaView:"海景",connecting:"连通房",benefits:"优惠与无障碍",dealsOnly:"仅优惠",accessible:"无障碍客房",ratingSort:"住客评分"},
 fr:{meal:"Options repas",breakfast:"Petit-déjeuner inclus",halfBoard:"Demi-pension",fullBoard:"Pension complète",roomOnly:"Hébergement seul",roomFeatures:"Caractéristiques de la chambre",kingBed:"Lit king-size",twinBeds:"Lits jumeaux",familyRoom:"Chambre familiale",smoking:"Chambre fumeurs",nonSmoking:"Non-fumeurs",balcony:"Balcon",seaView:"Vue mer",connecting:"Chambres communicantes",benefits:"Offres et accessibilité",dealsOnly:"Offres uniquement",accessible:"Accessible en fauteuil roulant",ratingSort:"Note des clients"},
 de:{meal:"Verpflegung",breakfast:"Frühstück inklusive",halfBoard:"Halbpension",fullBoard:"Vollpension",roomOnly:"Nur Zimmer",roomFeatures:"Zimmermerkmale",kingBed:"Kingsize-Bett",twinBeds:"Zwei Einzelbetten",familyRoom:"Familienzimmer",smoking:"Raucherzimmer",nonSmoking:"Nichtraucher",balcony:"Balkon",seaView:"Meerblick",connecting:"Zimmer mit Verbindungstür",benefits:"Angebote & Barrierefreiheit",dealsOnly:"Nur Angebote",accessible:"Rollstuhlgerecht",ratingSort:"Gästebewertung"},
 es:{meal:"Opciones de comida",breakfast:"Desayuno incluido",halfBoard:"Media pensión",fullBoard:"Pensión completa",roomOnly:"Solo alojamiento",roomFeatures:"Características de la habitación",kingBed:"Cama king",twinBeds:"Camas individuales",familyRoom:"Habitación familiar",smoking:"Habitación para fumadores",nonSmoking:"No fumadores",balcony:"Balcón",seaView:"Vista al mar",connecting:"Habitaciones comunicadas",benefits:"Ofertas y accesibilidad",dealsOnly:"Solo ofertas",accessible:"Accesible en silla de ruedas",ratingSort:"Puntuación de huéspedes"},
 it:{meal:"Opzioni pasti",breakfast:"Colazione inclusa",halfBoard:"Mezza pensione",fullBoard:"Pensione completa",roomOnly:"Solo camera",roomFeatures:"Caratteristiche camera",kingBed:"Letto king",twinBeds:"Letti singoli",familyRoom:"Camera familiare",smoking:"Camera fumatori",nonSmoking:"Non fumatori",balcony:"Balcone",seaView:"Vista mare",connecting:"Camere comunicanti",benefits:"Offerte e accessibilità",dealsOnly:"Solo offerte",accessible:"Accessibile in sedia a rotelle",ratingSort:"Valutazione ospiti"},
 tr:{meal:"Yemek seçenekleri",breakfast:"Kahvaltı dahil",halfBoard:"Yarım pansiyon",fullBoard:"Tam pansiyon",roomOnly:"Sadece oda",roomFeatures:"Oda özellikleri",kingBed:"King yatak",twinBeds:"İki ayrı yatak",familyRoom:"Aile odası",smoking:"Sigara içilen oda",nonSmoking:"Sigara içilmeyen",balcony:"Balkon",seaView:"Deniz manzarası",connecting:"Bağlantılı odalar",benefits:"Fırsatlar ve erişilebilirlik",dealsOnly:"Sadece fırsatlar",accessible:"Tekerlekli sandalye erişimi",ratingSort:"Misafir puanı"},
 ru:{meal:"Питание",breakfast:"Завтрак включен",halfBoard:"Полупансион",fullBoard:"Полный пансион",roomOnly:"Только номер",roomFeatures:"Особенности номера",kingBed:"Кровать king-size",twinBeds:"Две кровати",familyRoom:"Семейный номер",smoking:"Для курящих",nonSmoking:"Для некурящих",balcony:"Балкон",seaView:"Вид на море",connecting:"Смежные номера",benefits:"Предложения и доступность",dealsOnly:"Только предложения",accessible:"Доступ для колясок",ratingSort:"Оценка гостей"},
 ja:{meal:"食事オプション",breakfast:"朝食付き",halfBoard:"2食付き",fullBoard:"3食付き",roomOnly:"食事なし",roomFeatures:"客室設備",kingBed:"キングベッド",twinBeds:"ツインベッド",familyRoom:"ファミリールーム",smoking:"喫煙室",nonSmoking:"禁煙",balcony:"バルコニー",seaView:"シービュー",connecting:"コネクティングルーム",benefits:"特典・バリアフリー",dealsOnly:"セールのみ",accessible:"車椅子対応",ratingSort:"ゲスト評価"},
 ko:{meal:"식사 옵션",breakfast:"조식 포함",halfBoard:"하프보드",fullBoard:"풀보드",roomOnly:"룸 온리",roomFeatures:"객실 특징",kingBed:"킹베드",twinBeds:"트윈베드",familyRoom:"가족 객실",smoking:"흡연 객실",nonSmoking:"금연",balcony:"발코니",seaView:"바다 전망",connecting:"커넥팅 룸",benefits:"특가 및 접근성",dealsOnly:"특가만",accessible:"휠체어 이용 가능",ratingSort:"투숙객 평점"},
 hi:{meal:"भोजन विकल्प",breakfast:"नाश्ता शामिल",halfBoard:"हाफ बोर्ड",fullBoard:"फुल बोर्ड",roomOnly:"केवल कमरा",roomFeatures:"कमरे की सुविधाएँ",kingBed:"किंग बेड",twinBeds:"ट्विन बेड",familyRoom:"फैमिली रूम",smoking:"स्मोकिंग रूम",nonSmoking:"नॉन-स्मोकिंग",balcony:"बालकनी",seaView:"समुद्र दृश्य",connecting:"कनेक्टिंग रूम",benefits:"डील और एक्सेसिबिलिटी",dealsOnly:"केवल डील",accessible:"व्हीलचेयर एक्सेस",ratingSort:"मेहमान रेटिंग"},
 pt:{meal:"Opções de refeição",breakfast:"Café da manhã incluído",halfBoard:"Meia pensão",fullBoard:"Pensão completa",roomOnly:"Somente quarto",roomFeatures:"Características do quarto",kingBed:"Cama king",twinBeds:"Camas de solteiro",familyRoom:"Quarto familiar",smoking:"Quarto para fumantes",nonSmoking:"Não fumante",balcony:"Varanda",seaView:"Vista para o mar",connecting:"Quartos conjugados",benefits:"Ofertas e acessibilidade",dealsOnly:"Somente ofertas",accessible:"Acessível para cadeira de rodas",ratingSort:"Nota dos hóspedes"},
 id:{meal:"Pilihan makanan",breakfast:"Sarapan termasuk",halfBoard:"Half board",fullBoard:"Full board",roomOnly:"Kamar saja",roomFeatures:"Fitur kamar",kingBed:"Tempat tidur king",twinBeds:"Tempat tidur twin",familyRoom:"Kamar keluarga",smoking:"Kamar merokok",nonSmoking:"Bebas rokok",balcony:"Balkon",seaView:"Pemandangan laut",connecting:"Kamar terhubung",benefits:"Promo dan aksesibilitas",dealsOnly:"Promo saja",accessible:"Akses kursi roda",ratingSort:"Rating tamu"},
 th:{meal:"ตัวเลือกอาหาร",breakfast:"รวมอาหารเช้า",halfBoard:"ฮาล์ฟบอร์ด",fullBoard:"ฟูลบอร์ด",roomOnly:"ห้องพักอย่างเดียว",roomFeatures:"คุณสมบัติห้อง",kingBed:"เตียงคิงไซส์",twinBeds:"เตียงแฝด",familyRoom:"ห้องครอบครัว",smoking:"ห้องสูบบุหรี่",nonSmoking:"ห้องปลอดบุหรี่",balcony:"ระเบียง",seaView:"วิวทะเล",connecting:"ห้องเชื่อมกัน",benefits:"ดีลและการเข้าถึง",dealsOnly:"เฉพาะดีล",accessible:"รองรับรถเข็น",ratingSort:"คะแนนผู้เข้าพัก"}
};

const MEALS=[['FILTER:MEAL:BREAKFAST','breakfast'],['FILTER:MEAL:HALF_BOARD','halfBoard'],['FILTER:MEAL:FULL_BOARD','fullBoard'],['FILTER:MEAL:ROOM_ONLY','roomOnly']] as const;
const ROOMS=[['FILTER:ROOM:KING_BED','kingBed'],['FILTER:ROOM:TWIN_BEDS','twinBeds'],['FILTER:ROOM:FAMILY_ROOM','familyRoom'],['FILTER:ROOM:SMOKING','smoking'],['FILTER:ROOM:NON_SMOKING','nonSmoking'],['FILTER:ROOM:BALCONY','balcony'],['FILTER:ROOM:SEA_VIEW','seaView'],['FILTER:ROOM:CONNECTING_ROOMS','connecting']] as const;

export function SearchFilterExtras(){
 useEffect(()=>{
  const locale=localeFromLanguageTag(document.querySelector<HTMLElement>('.searchExperience')?.lang||document.documentElement.lang)||'en';
  const copy=COPY[locale]??EN;
  const selected=new Set(new URLSearchParams(window.location.search).getAll('amenities').map((v)=>v.toUpperCase()));
  const enhanceSort=()=>document.querySelectorAll<HTMLSelectElement>('select[name="sort"]').forEach((select)=>{if(select.querySelector('option[value="RATING_DESC"]'))return;const option=document.createElement('option');option.value='RATING_DESC';option.textContent=copy.ratingSort;select.appendChild(option);if(new URLSearchParams(window.location.search).get('sort')==='RATING_DESC')select.value='RATING_DESC';});
  const enhanceBody=(body:HTMLElement)=>{
   if(body.dataset.filterExtras==='true')return;body.dataset.filterExtras='true';
   body.appendChild(section(copy.meal,MEALS.map(([value,key])=>({value,label:copy[key]})),selected));
   body.appendChild(section(copy.roomFeatures,ROOMS.map(([value,key])=>({value,label:copy[key]})),selected));
   body.appendChild(section(copy.benefits,[{value:'FILTER:DEAL:ONLY',label:copy.dealsOnly},{value:'FILTER:ACCESSIBLE',label:copy.accessible}],selected));
  };
  const enhanceAll=()=>{enhanceSort();document.querySelectorAll<HTMLElement>('.advancedFiltersBody').forEach(enhanceBody);};
  enhanceAll();const observer=new MutationObserver(enhanceAll);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect();
 },[]);
 return null;
}

function section(title:string,items:ReadonlyArray<{value:string;label:string}>,selected:Set<string>){
 const wrapper=document.createElement('div');wrapper.className='advancedCheckSection';const heading=document.createElement('strong');heading.textContent=title;wrapper.appendChild(heading);const grid=document.createElement('div');grid.className='advancedCheckGrid';for(const item of items){const label=document.createElement('label');label.className='advancedCheck';const input=document.createElement('input');input.type='checkbox';input.name='amenities';input.value=item.value;input.defaultChecked=selected.has(item.value.toUpperCase());const text=document.createElement('span');text.textContent=item.label;label.append(input,text);grid.appendChild(label);}wrapper.appendChild(grid);return wrapper;
}
