"use client";

import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type RoomType={id:string;name:string;code:string;ratePlans:{id:string;name:string;code:string}[]};

export default function SetupManager({hotelId,roomTypes,overbookingEnabled}:{hotelId:string;roomTypes:RoomType[];overbookingEnabled:boolean}){const router=useRouter();const[message,setMessage]=useState<string|null>(null);const ratePlans=useMemo(()=>roomTypes.flatMap((room)=>room.ratePlans.map((plan)=>({...plan,roomTypeId:room.id,roomName:room.name}))),[roomTypes]);
async function post(path:string,body:unknown,method="POST"){setMessage(null);const response=await fetch(path,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result?.error?.message??"Request failed");setMessage("Saved successfully");router.refresh();}
async function createRoomType(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{await post(`/api/v1/hotels/${hotelId}/room-types`,{name:form.get("name"),code:form.get("code"),maxAdults:Number(form.get("maxAdults")),maxChildren:Number(form.get("maxChildren"))});event.currentTarget.reset();}catch(cause){setMessage(cause instanceof Error?cause.message:"Request failed");}}
async function createRatePlan(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{await post(`/api/v1/hotels/${hotelId}/rate-plans`,{roomTypeId:form.get("roomTypeId"),name:form.get("name"),code:form.get("code"),refundable:form.get("refundable")==="on",mealPlan:form.get("mealPlan")});event.currentTarget.reset();}catch(cause){setMessage(cause instanceof Error?cause.message:"Request failed");}}
async function updateCalendar(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const ratePlanId=String(form.get("ratePlanId")??"");const plan=ratePlans.find((item)=>item.id===ratePlanId);if(!plan)return setMessage("Select a valid rate plan");try{await post(`/api/v1/hotels/${hotelId}/calendar`,{entries:[{date:form.get("date"),roomTypeId:plan.roomTypeId,ratePlanId,baseRate:Number(form.get("baseRate")),available:Number(form.get("available")),overbookingLimit:Number(form.get("overbookingLimit")),minStay:Number(form.get("minStay")),maxStay:null,closed:false,stopSell:form.get("stopSell")==="on"}]},"PUT");}catch(cause){setMessage(cause instanceof Error?cause.message:"Request failed");}}
return <div className="setupGrid"><section className="panel setupPanel"><span className="eyebrow">Step 2</span><h2>Room types</h2><form onSubmit={createRoomType} className="stackForm"><input name="name" placeholder="Deluxe King" required/><input name="code" placeholder="DLX-K" required/><div className="formGrid"><input name="maxAdults" type="number" min="1" defaultValue="2" required/><input name="maxChildren" type="number" min="0" defaultValue="0" required/></div><button className="primaryButton">Add room type</button></form><div className="setupList">{roomTypes.map((room)=><div key={room.id}><strong>{room.name}</strong><span>{room.code} · {room.ratePlans.length} plans</span></div>)}</div></section><section className="panel setupPanel"><span className="eyebrow">Step 3</span><h2>Rate plans</h2><form onSubmit={createRatePlan} className="stackForm"><select name="roomTypeId" required defaultValue=""><option value="" disabled>Select room type</option>{roomTypes.map((room)=><option key={room.id} value={room.id}>{room.name}</option>)}</select><input name="name" placeholder="Breakfast Flexible" required/><input name="code" placeholder="BF-FLEX" required/><select name="mealPlan" defaultValue="BREAKFAST"><option value="ROOM_ONLY">Room only</option><option value="BREAKFAST">Breakfast</option><option value="HALF_BOARD">Half board</option><option value="FULL_BOARD">Full board</option></select><label className="inlineCheck"><input type="checkbox" name="refundable" defaultChecked/> Refundable</label><button className="primaryButton" disabled={roomTypes.length===0}>Add rate plan</button></form></section><section className="panel setupPanel wideSetup"><span className="eyebrow">Step 4</span><h2>First rate & inventory day</h2><form onSubmit={updateCalendar} className="calendarForm"><label>Date<input name="date" type="date" required/></label><label>Rate plan<select name="ratePlanId" required defaultValue=""><option value="" disabled>Select plan</option>{ratePlans.map((plan)=><option value={plan.id} key={plan.id}>{plan.roomName} · {plan.name}</option>)}</select></label><label>Base rate<input name="baseRate" type="number" min="0" step="0.01" required/></label><label>Available<input name="available" type="number" min="0" required/></label><label>Min stay<input name="minStay" type="number" min="1" defaultValue="1" required/></label><label>Overbooking limit<input name="overbookingLimit" type="number" min="0" defaultValue="0" disabled={!overbookingEnabled} required/></label><label className="inlineCheck"><input name="stopSell" type="checkbox"/> Stop sell</label><button className="primaryButton" disabled={ratePlans.length===0}>Save calendar day</button></form>{!overbookingEnabled&&<p className="muted">Overbooking is disabled at hotel level, so this field is intentionally locked.</p>}</section>{message&&<div className="setupMessage">{message}</div>}</div>;
}
