export const fr = {
  language:{english:"English",arabic:"العربية",label:"Langue"},
  nav:{stays:"Hébergements",trips:"Mes voyages",alerts:"Alertes de prix",partner:"Ajouter votre établissement",account:"Compte",signIn:"Se connecter",signOut:"Se déconnecter",signingOut:"Déconnexion…"},
  home:{
    kicker:"Hôtels, prix transparents",title:"Trouvez le séjour qui vous convient. Voyez le prix que vous paierez vraiment.",intro:"Disponibilités en direct, établissements vérifiés, vrais avis clients et conditions d’annulation affichées avant votre réservation.",verified:"Établissements vérifiés",cancellation:"Conditions d’annulation enregistrées",total:"Total final du séjour",
    livePlaceholder:"Les séjours disponibles apparaîtront ici",livePlaceholderSub:"Seuls les établissements actifs, vérifiés et dotés de médias publiés sont affichés.",where:"Destination",whereHint:"Ville, quartier ou hôtel",checkIn:"Arrivée",checkOut:"Départ",guests:"Voyageurs",adults:"Adultes",search:"Rechercher des séjours",
    liveEyebrow:"En direct sur HandMeKey",liveTitle:"Des séjours vérifiés qui valent le détour.",liveIntro:"Les établissements apparaissent ici uniquement après vérification par la plateforme et publication de leur contenu en direct.",explore:"Explorer tous les séjours",noHotels:"Aucun établissement vérifié n’est encore publié",noHotelsSub:"Les hôtels en brouillon ou non vérifiés restent privés jusqu’à la fin du contrôle de publication.",photoPending:"Photo en attente",verifiedLabel:"Vérifié",demoProperty:"Établissement de démonstration",review:"avis vérifié",reviews:"avis vérifiés",checkPrice:"Voir le prix en direct",
    valueEyebrow:"Pensé autour de la réservation",valueTitle:"Moins d’incertitude entre la recherche et la confirmation.",finalTitle:"Le total final d’abord",finalBody:"Les frais de service et obligatoires sont inclus dans le total calculé par le serveur avant la réservation.",policyTitle:"Des conditions qui restent liées à la réservation",policyBody:"La politique d’annulation est enregistrée au moment de la réservation afin que les modifications ultérieures ne changent pas vos conditions initiales.",watchTitle:"Suivre le prix d’un vrai séjour",watchBody:"Suivez le même hôtel et les mêmes dates. HandMeKey recalcule le prix selon les tarifs, les disponibilités et les promotions en direct.",partnerEyebrow:"Pour les partenaires hôteliers",partnerTitle:"Gérez votre annonce, vos tarifs et votre conversion.",partnerBody:"Partner Hub réunit la configuration de l’établissement, les réservations, les promotions, les messages clients et les données de performance propriétaires.",partnerCta:"Découvrir Partner Hub"
  },
  search:{
    destination:"Destination",checkIn:"Arrivée",checkOut:"Départ",adults:"Adultes",children:"Enfants",again:"Rechercher à nouveau",filter:"Filtrer votre séjour",nightly:"Total par nuit",min:"Min.",max:"Max.",stars:"Classement par étoiles",anyStars:"Toutes les catégories",payment:"Paiement",anyPayment:"Tous les modes de paiement",payHotel:"Payer à l’hôtel",payNow:"Payer maintenant",sort:"Trier par",recommended:"Recommandé",lowPrice:"Prix le plus bas",highPrice:"Prix le plus élevé",highStars:"Plus grand nombre d’étoiles",freeCancel:"Annulation gratuite maintenant",facilities:"Équipements",apply:"Appliquer les filtres",
    live:"Disponibilité en direct",verifiedProperty:"établissement vérifié",verifiedProperties:"établissements vérifiés",for:"pour",save:"Enregistrer la recherche",badTitle:"Vérifiez les détails de votre recherche",invalid:"Recherche invalide",noneTitle:"Aucune offre en direct ne correspond à ce séjour",noneBody:"Essayez d’autres dates, un autre nombre de voyageurs ou moins de filtres. Les tarifs incomplets et les chambres indisponibles sont volontairement exclus.",photoPending:"Photo en attente",verified:"Vérifié",demoProperty:"établissement de démonstration",demoProperties:"établissements de démonstration",review:"avis vérifié",reviews:"avis vérifiés",off:"de réduction",freeNow:"Annulation gratuite actuellement",penalty:"Des frais d’annulation peuvent s’appliquer",only:"Plus que",roomLeft:"chambre restante pour ces dates",roomsLeft:"chambres restantes pour ces dates",finalTotal:"Total final du séjour",average:"moyenne / nuit",seeRooms:"Voir les chambres"
  },
  hotel:{
    back:"Retour aux hébergements à {city}",verified:"Établissement vérifié",demoProperty:"Établissement de démonstration",star:"étoile",guestSignal:"Excellent avis des clients",stayReview:"avis de séjour vérifié",stayReviews:"avis de séjours vérifiés",checkIn:"Arrivée",checkOut:"Départ",propertyPolicy:"Politique de l’établissement",noPhotos:"Les photos de l’établissement ne sont pas encore publiées.",finalPrice:"Prix final avant réservation",liveInventory:"Disponibilité des chambres en direct",verifiedReviews:"Uniquement des avis de séjours vérifiés",property:"L’établissement",about:"À propos de {hotel}",noDescription:"L’établissement n’a pas encore publié de description.",facilities:"Équipements",noFacilities:"Les équipements ne sont pas encore publiés.",yourStay:"Votre séjour",chooseDates:"Choisissez vos dates et consultez le total en direct.",adults:"Adultes",children:"Enfants",availability:"Vérifier les disponibilités",invalidStay:"Le séjour demandé n’était pas valide. HandMeKey a chargé les prochaines dates par défaut.",available:"Disponible pour vos dates",liveRate:"tarif en direct",liveRates:"tarifs en direct",night:"nuit",nights:"nuits",totalsNote:"les totaux finaux incluent les frais de service et obligatoires configurés.",from:"À partir de",stayTotal:"total du séjour",noRooms:"Aucune chambre n’est vendable pour ce séjour",noRoomsBody:"Un tarif n’apparaît que si chaque nuit dispose d’un prix valide, de restrictions compatibles et d’un stock restant.",room:"Chambre",upTo:"Jusqu’à",adult:"adulte",adultsPlural:"adultes",package:"Formule",cancellation:"Annulation",freeNow:"Annulation gratuite maintenant",currentPenalty:"Frais actuels",finalTotal:"Total final du séjour",average:"moyenne / nuit",base:"Base",service:"service",tax:"taxes",choose:"Choisir cette chambre",only:"Plus que",left:"restantes",breakfast:"Petit-déjeuner inclus",halfBoard:"Demi-pension",fullBoard:"Pension complète",roomOnly:"Chambre seule",payHotel:"Payer à l’hôtel",payNow:"Payer maintenant",verifiedStays:"Séjours vérifiés",reviewsTitle:"Les notes réellement données par les clients.",noReviews:"Aucun avis vérifié pour le moment",noReviewsBody:"Seuls les clients ayant terminé leur séjour peuvent publier un avis.",outOf10:"sur 10",verifiedStaysCount:"séjours vérifiés",cleanliness:"Propreté",staff:"Personnel",location:"Emplacement",comfort:"Confort",value:"Rapport qualité-prix",verifiedStay:"Séjour vérifié",propertyResponse:"Réponse de l’établissement"
  },
  checkout:{
    secure:"Réservation sécurisée",title:"Vérifiez le tarif en direct avant de confirmer.",intro:"Le total, le mode de paiement et la politique d’annulation proviennent du même moteur de réservation qui crée votre réservation.",session:"Session de compte sécurisée",terms:"Conditions de réservation enregistrées",selectionTitle:"Une chambre disponible en direct doit être sélectionnée",selectionBody:"Choisissez un hôtel, une chambre et un tarif avant d’ouvrir le paiement. HandMeKey n’utilise pas de parcours de paiement de démonstration caché.",back:"Retour à la recherche",checking:"Vérification du tarif et des disponibilités…",loadFail:"Impossible de charger ce séjour",guestInfo:"Informations du voyageur",fullName:"Nom complet",email:"E-mail",payment:"Option de paiement",payHotel:"Payer à l’hôtel",payNow:"Payer maintenant",gatewayMissing:"passerelle de paiement en ligne non configurée",noPayment:"Ce tarif exige actuellement un paiement en ligne, mais aucun prestataire de paiement n’est configuré pour ce déploiement.",reserve:"Réserver et continuer",securing:"Réservation temporaire de votre chambre…",holdNote:"Votre chambre est conservée temporairement côté serveur. Le tarif final est revérifié avant de réduire le stock.",yourStay:"Votre séjour",roomBase:"Prix de base de la chambre",service:"Frais de service",tax:"Taxes / frais obligatoires",final:"Total final",cancellation:"Annulation",noShow:"Non-présentation",inventory:"Stock vendable en direct",offIncluded:"de réduction sur le prix de base est déjà inclus ci-dessous.",paymentAction:"Le paiement a commencé mais nécessite une action du prestataire avant confirmation de la réservation."
  },
  login:{eyebrow:"Votre séjour, au même endroit",title:"Réservez une fois. Gardez tous vos voyages à portée de main.",intro:"Connectez-vous pour gérer vos réservations, suivre les prix des hôtels et conserver vos échanges avec l’établissement liés au séjour.",verified:"Réservations vérifiées",verifiedSub:"Accédez aux séjours confirmés et à leurs conditions d’annulation.",alerts:"Alertes de prix",alertsSub:"Suivez un séjour et recevez une alerte lorsque le tarif en direct baisse.",messages:"Messages de l’hôtel",messagesSub:"Conservez les demandes clients et les réponses de l’établissement avec la réservation.",partner:"Vous gérez un hôtel ?",partnerCta:"Accéder à Partner Hub"},
  account:{my:"Mon compte",overview:"Vue d’ensemble",profile:"Informations personnelles",security:"Sécurité",trips:"Mes voyages",alerts:"Alertes de prix",preferences:"Préférences",overviewEyebrow:"Compte voyageur",overviewTitle:"Tout ce qui concerne vos séjours, au même endroit.",overviewBody:"Vos réservations, suivis de prix et contrôles de sécurité sont liés à votre compte connecté, et non au navigateur utilisé.",upcoming:"Voyages à venir",activeWatches:"Suivis de prix actifs",unreadAlerts:"Alertes non lues",totalTrips:"Voyages du compte",profileCard:"Informations personnelles",profileCardBody:"Gardez à jour le nom utilisé pour préremplir les nouvelles réservations.",securityCard:"Sécurité",securityCardBody:"Modifiez votre mot de passe et fermez les sessions auxquelles vous ne faites plus confiance.",tripsCard:"Voyages",tripsCardBody:"Ouvrez vos réservations confirmées, en cours, passées et annulées.",alertsCard:"Suivi des prix",alertsCardBody:"Gérez les recherches enregistrées, les suivis et les alertes persistantes dans l’application.",open:"Ouvrir",prefTitle:"Langue",prefBody:"Choisissez la langue des pages clients HandMeKey. Votre préférence vous suit sur vos autres appareils lorsque vous êtes connecté.",english:"English",arabic:"العربية"},
  profile:{eyebrow:"Profil du compte",title:"Informations personnelles",body:"Gardez exactes les informations utilisées pour préremplir vos futures réservations. Votre e-mail de connexion reste protégé jusqu’à la disponibilité des changements d’e-mail vérifiés.",fullName:"Nom complet",email:"E-mail de connexion",protected:"L’e-mail est protégé.",protectedBody:"HandMeKey n’autorisera un changement d’e-mail qu’après connexion d’un processus de vérification. Nous ne remplaçons jamais silencieusement l’identité utilisée pour accéder aux réservations.",smart:"Paiement plus rapide.",smartBody:"Le nom du compte et l’e-mail de connexion sont préremplis lorsque vous réservez en étant connecté, mais vous pouvez toujours modifier le nom du voyageur pour une réservation donnée.",saved:"Informations personnelles enregistrées.",save:"Enregistrer les modifications",saving:"Enregistrement…"},
  security:{eyebrow:"Protection du compte",title:"Sécurité",body:"Modifiez votre mot de passe et examinez les sessions serveur actives sans exposer les jetons d’authentification au navigateur.",change:"Modifier le mot de passe",changeBody:"La modification du mot de passe ferme toutes les sessions existantes et crée une nouvelle session pour ce navigateur.",currentPassword:"Mot de passe actuel",newPassword:"Nouveau mot de passe",hint:"Utilisez au moins 12 caractères.",update:"Mettre à jour le mot de passe",updating:"Mise à jour…",sessions:"Sessions actives",sessionsBody:"HandMeKey utilise des sessions serveur opaques. Vous pouvez fermer celles auxquelles vous ne faites plus confiance sans exposer les jetons de session au navigateur.",checking:"Vérification des sessions actives…",thisBrowser:"Ce navigateur",other:"Autre session active",current:"Actuelle",lastActive:"Dernière activité",created:"Créée",expires:"Expire",close:"Fermer",closing:"Fermeture…",none:"Aucune session active.",signOutOthers:"Déconnecter les autres sessions",changed:"Mot de passe modifié. Vos anciennes sessions ont été fermées et cette session a été renouvelée en toute sécurité.",closed:"Session fermée.",noOthers:"Aucune autre session n’était active."},
  trips:{eyebrow:"Compte client",title:"Mes voyages",bodyPrefix:"Réservations liées à",bodySuffix:"Les réservations invité ne peuvent être liées qu’avec leur jeton d’accès.",noTrips:"Aucun voyage lié pour le moment",noTripsBody:"Réservez en étant connecté, ou ouvrez une réservation existante dans le navigateur où elle a été créée et liez-la à ce compte.",find:"Trouver un hôtel",current:"Séjours en cours",upcoming:"Voyages à venir",past:"Voyages passés",cancelled:"Annulés / expirés",noPhoto:"Aucune photo",expected:"Arrivée prévue",openRequest:"demande ouverte",openRequests:"demandes ouvertes",noRequests:"Aucune demande ouverte"},
  alerts:{eyebrow:"Intelligence du compte",title:"Alertes et suivis",body:"Les recherches enregistrées et le suivi des prix utilisent les mêmes tarifs, promotions et disponibilités que ceux affichés lors de la réservation."}
} as const;
