export const ja = {
  language:{english:"English",arabic:"العربية",label:"言語"},
  nav:{stays:"宿泊施設",trips:"予約・旅行",alerts:"料金アラート",partner:"施設を掲載",account:"アカウント",signIn:"ログイン",signOut:"ログアウト",signingOut:"ログアウト中…"},
  home:{kicker:"料金がわかりやすいホテル",title:"泊まりたい宿を見つけ、実際に支払う料金を確認。",intro:"リアルタイムの空室、確認済み施設、実際の宿泊者レビュー、キャンセル条件を予約前に確認できます。",verified:"確認済み施設",cancellation:"保存されたキャンセル条件",total:"宿泊の最終合計",livePlaceholder:"予約可能な宿泊施設がここに表示されます",livePlaceholderSub:"公開済みコンテンツを持つ、営業中かつ確認済みの施設のみ表示します。",where:"目的地",whereHint:"都市・エリア・ホテル",checkIn:"チェックイン",checkOut:"チェックアウト",guests:"宿泊者",adults:"大人",search:"宿泊施設を検索",liveEyebrow:"HandMeKey のリアルタイム情報",liveTitle:"確認済みのおすすめ宿泊施設。",liveIntro:"施設はプラットフォーム審査を通過し、最新コンテンツを公開した後に表示されます。",explore:"すべての宿泊施設を見る",noHotels:"公開済みの確認済み施設はまだありません",noHotelsSub:"下書きまたは未確認のホテルは、公開審査が完了するまで非公開です。",photoPending:"写真準備中",verifiedLabel:"確認済み",demoProperty:"デモ施設",review:"確認済みレビュー",reviews:"確認済みレビュー",checkPrice:"最新料金を確認",valueEyebrow:"予約を中心に設計",valueTitle:"検索から確定まで、迷いを少なく。",finalTitle:"最終合計を先に表示",finalBody:"サービス料と必須料金は、予約前にサーバーが計算する合計に含まれます。",policyTitle:"予約時の条件をそのまま保存",policyBody:"キャンセルポリシーは予約時点で保存されるため、その後の変更で元の条件が書き換わることはありません。",watchTitle:"実際の宿泊料金を追跡",watchBody:"同じホテルと日程を追跡し、HandMeKey が最新料金・在庫・有効なキャンペーンで再計算します。",partnerEyebrow:"ホテルパートナー向け",partnerTitle:"掲載情報、料金、コンバージョンを管理。",partnerBody:"Partner Hub では施設設定、予約、キャンペーン、ゲストメッセージ、独自のパフォーマンス分析を一元管理できます。",partnerCta:"Partner Hub を見る"},
  search:{destination:"目的地",checkIn:"チェックイン",checkOut:"チェックアウト",adults:"大人",children:"子ども",again:"もう一度検索",filter:"絞り込み",nightly:"1泊あたり合計",min:"最低",max:"最高",stars:"星評価",anyStars:"指定なし",payment:"支払い",anyPayment:"すべての支払い方法",payHotel:"現地払い",payNow:"今すぐ支払う",sort:"並び替え",recommended:"おすすめ",lowPrice:"料金が安い順",highPrice:"料金が高い順",highStars:"星の多い順",freeCancel:"現在キャンセル無料",facilities:"設備",apply:"フィルターを適用",live:"リアルタイム空室",verifiedProperty:"確認済み施設",verifiedProperties:"確認済み施設",for:"対象",save:"検索を保存",badTitle:"検索条件を確認してください",invalid:"検索条件が無効です",noneTitle:"この条件に合うリアルタイム料金はありません",noneBody:"日程、宿泊人数、またはフィルターを変更してください。料金が不完全なプランや空室のないプランは表示されません。",photoPending:"写真準備中",verified:"確認済み",demoProperty:"デモ施設",demoProperties:"デモ施設",review:"確認済みレビュー",reviews:"確認済みレビュー",off:"割引",freeNow:"現在キャンセル無料",penalty:"キャンセル料がかかる場合があります",only:"残り",roomLeft:"室（この日程）",roomsLeft:"室（この日程）",finalTotal:"宿泊の最終合計",average:"平均 / 泊",seeRooms:"客室を見る"},
  hotel:{back:"{city} の宿泊施設に戻る",verified:"確認済み施設",demoProperty:"デモ施設",star:"つ星",guestSignal:"ゲストから高評価",stayReview:"確認済み宿泊レビュー",stayReviews:"確認済み宿泊レビュー",checkIn:"チェックイン",checkOut:"チェックアウト",propertyPolicy:"施設ポリシー",noPhotos:"施設の写真はまだ公開されていません。",finalPrice:"予約前の最終料金",liveInventory:"リアルタイム客室在庫",verifiedReviews:"確認済み宿泊レビューのみ",property:"施設情報",about:"{hotel} について",noDescription:"施設の説明はまだ公開されていません。",facilities:"設備",noFacilities:"設備情報はまだ公開されていません。",yourStay:"宿泊内容",chooseDates:"日程を選んで最新の合計を確認。",adults:"大人",children:"子ども",availability:"空室を確認",invalidStay:"指定した宿泊条件が無効だったため、HandMeKey が次の標準日程を読み込みました。",available:"指定日程で予約可能",liveRate:"リアルタイム料金プラン",liveRates:"リアルタイム料金プラン",night:"泊",nights:"泊",totalsNote:"最終合計には設定済みのサービス料と必須料金が含まれます。",from:"最低",stayTotal:"宿泊合計",noRooms:"この日程で販売可能な客室はありません",noRoomsBody:"すべての宿泊日に有効な料金、条件、残室がある場合のみ料金プランが表示されます。",room:"客室",upTo:"最大",adult:"大人",adultsPlural:"大人",package:"プラン",cancellation:"キャンセル",freeNow:"現在キャンセル無料",currentPenalty:"現在のキャンセル料",finalTotal:"宿泊の最終合計",average:"平均 / 泊",base:"基本料金",service:"サービス料",tax:"税金",choose:"この客室を選ぶ",only:"残り",left:"室",breakfast:"朝食付き",halfBoard:"2食付き",fullBoard:"3食付き",roomOnly:"食事なし",payHotel:"現地払い",payNow:"今すぐ支払う",verifiedStays:"確認済み宿泊",reviewsTitle:"実際の宿泊者による評価。",noReviews:"確認済みレビューはまだありません",noReviewsBody:"宿泊を完了したゲストのみレビューを投稿できます。",outOf10:"10点満点",verifiedStaysCount:"確認済み宿泊",cleanliness:"清潔さ",staff:"スタッフ",location:"ロケーション",comfort:"快適さ",value:"お得感",verifiedStay:"確認済み宿泊",propertyResponse:"施設からの返信"},
  checkout:{secure:"安全な予約",title:"確定前に最新料金を確認してください。",intro:"合計、支払い方法、キャンセルポリシーは、予約を作成する同じ予約エンジンから取得されます。",session:"安全なアカウントセッション",terms:"保存された予約条件",selectionTitle:"リアルタイムの客室選択が必要です",selectionBody:"決済へ進む前にホテル、客室、料金プランを選択してください。HandMeKey は隠れたデモ決済を使用しません。",back:"検索に戻る",checking:"最新料金と空室を確認中…",loadFail:"この宿泊を読み込めませんでした",guestInfo:"宿泊者情報",fullName:"氏名",email:"メールアドレス",payment:"支払い方法",payHotel:"現地払い",payNow:"今すぐ支払う",gatewayMissing:"オンライン決済が未設定です",noPayment:"この料金はオンライン決済が必要ですが、この環境には決済プロバイダーが設定されていません。",reserve:"予約して続ける",securing:"客室を確保中…",holdNote:"客室はサーバー側で一時的に確保されます。在庫を減らす前に最終料金を再確認します。",yourStay:"宿泊内容",roomBase:"客室基本料金",service:"サービス料",tax:"税金 / 必須料金",final:"最終合計",cancellation:"キャンセル",noShow:"不泊",inventory:"リアルタイム販売可能在庫",offIncluded:"の基本料金割引は下記料金に含まれています。",paymentAction:"決済は開始されましたが、予約確定前に決済プロバイダー側で操作が必要です。"},
  login:{eyebrow:"宿泊をひとつの場所で管理",title:"一度予約すれば、すべての旅行をすぐ確認。",intro:"ログインすると予約管理、ホテル料金の追跡、施設とのメッセージを宿泊ごとにまとめて管理できます。",verified:"確認済み予約",verifiedSub:"確定済み宿泊とキャンセル条件を確認できます。",alerts:"料金アラート",alertsSub:"宿泊料金を追跡し、最新料金が下がったら通知を受け取ります。",messages:"ホテルメッセージ",messagesSub:"ゲストのリクエストと施設の返信を予約に紐づけて保存します。",partner:"ホテルを管理していますか？",partnerCta:"Partner Hub へ"},
  account:{my:"マイアカウント",overview:"概要",profile:"個人情報",security:"セキュリティ",trips:"予約・旅行",alerts:"料金アラート",preferences:"設定",overviewEyebrow:"旅行者アカウント",overviewTitle:"宿泊に関するすべてを、ひとつの場所に。",overviewBody:"予約、料金追跡、セキュリティ設定は使用中のブラウザではなく、ログインしたアカウントに紐づきます。",upcoming:"今後の旅行",activeWatches:"追跡中の料金",unreadAlerts:"未読アラート",totalTrips:"アカウントの旅行数",profileCard:"個人情報",profileCardBody:"新しい予約に自動入力される名前を最新に保ちます。",securityCard:"セキュリティ",securityCardBody:"パスワードを変更し、信頼しないセッションを終了します。",tripsCard:"旅行",tripsCardBody:"確定済み、滞在中、過去、キャンセル済みの予約を確認します。",alertsCard:"料金インテリジェンス",alertsCardBody:"保存した検索、料金追跡、アプリ内アラートを管理します。",open:"開く",prefTitle:"言語",prefBody:"HandMeKey のお客様向けページの表示言語を選択します。ログイン中は他の端末にも設定が引き継がれます。",english:"English",arabic:"العربية"},
  profile:{eyebrow:"アカウントプロフィール",title:"個人情報",body:"今後の予約に自動入力される情報を正確に保ちます。確認付きメール変更が利用可能になるまで、ログイン用メールは保護されます。",fullName:"氏名",email:"ログイン用メール",protected:"メールは保護されています。",protectedBody:"HandMeKey は確認済みメール変更フローが接続された後にのみメール変更を許可します。予約へのアクセスに使う本人情報を黙って変更することはありません。",smart:"よりスムーズな予約。",smartBody:"ログイン中に予約するとアカウント名とメールが自動入力されますが、各予約の宿泊者名は変更できます。",saved:"個人情報を保存しました。",save:"変更を保存",saving:"保存中…"},
  security:{eyebrow:"アカウント保護",title:"セキュリティ",body:"認証トークンをブラウザに公開せず、パスワードの変更とアクティブなサーバーセッションの確認ができます。",change:"パスワードを変更",changeBody:"パスワードを変更すると既存のすべてのセッションが終了し、このブラウザ用に新しいセッションが作成されます。",currentPassword:"現在のパスワード",newPassword:"新しいパスワード",hint:"12文字以上を使用してください。",update:"パスワードを更新",updating:"更新中…",sessions:"アクティブなセッション",sessionsBody:"HandMeKey は不透明なサーバーセッションを使用します。セッショントークンをブラウザに公開せず、信頼しないセッションを終了できます。",checking:"アクティブなセッションを確認中…",thisBrowser:"このブラウザ",other:"別のアクティブセッション",current:"現在",lastActive:"最終利用",created:"作成",expires:"有効期限",close:"終了",closing:"終了中…",none:"アクティブなセッションはありません。",signOutOthers:"他のセッションからログアウト",changed:"パスワードを変更しました。以前のセッションは終了し、このセッションは安全に更新されました。",closed:"セッションを終了しました。",noOthers:"他のアクティブなセッションはありませんでした。"},
  trips:{eyebrow:"ゲストアカウント",title:"予約・旅行",bodyPrefix:"次のアカウントに紐づく予約:",bodySuffix:"ゲスト予約は予約アクセス用トークンを使った場合のみアカウントに紐づけられます。",noTrips:"紐づいた旅行はまだありません",noTripsBody:"ログインして予約するか、予約を作成したブラウザで既存の予約を開き、このアカウントに紐づけてください。",find:"ホテルを探す",current:"現在の宿泊",upcoming:"今後の旅行",past:"過去の旅行",cancelled:"キャンセル / 期限切れ",noPhoto:"写真なし",expected:"到着予定",openRequest:"未対応リクエスト",openRequests:"未対応リクエスト",noRequests:"未対応リクエストなし"},
  alerts:{eyebrow:"アカウントインテリジェンス",title:"アラートと料金追跡",body:"保存した検索とリアルタイム料金追跡は、予約時に表示されるものと同じ料金、プロモーション、空室情報を使用します。"}
} as const;
