export const ko = {
  language:{english:"English",arabic:"العربية",label:"언어"},
  nav:{stays:"숙소",trips:"내 여행",alerts:"가격 알림",partner:"숙소 등록",account:"계정",signIn:"로그인",signOut:"로그아웃",signingOut:"로그아웃 중…"},
  home:{kicker:"가격이 명확한 호텔",title:"원하는 숙소를 찾고 실제 결제 금액을 확인하세요.",intro:"실시간 객실 재고, 검증된 숙소, 실제 투숙객 후기와 취소 조건을 예약 전에 확인할 수 있습니다.",verified:"검증된 숙소",cancellation:"저장된 취소 조건",total:"숙박 최종 합계",livePlaceholder:"예약 가능한 숙소가 여기에 표시됩니다",livePlaceholderSub:"활성 상태이며 검증되고 콘텐츠가 공개된 숙소만 표시됩니다.",where:"목적지",whereHint:"도시, 지역 또는 호텔",checkIn:"체크인",checkOut:"체크아웃",guests:"투숙객",adults:"성인",search:"숙소 검색",liveEyebrow:"HandMeKey 실시간",liveTitle:"확인해 볼 만한 검증된 숙소.",liveIntro:"숙소는 플랫폼 심사를 통과하고 실시간 콘텐츠를 공개한 뒤에만 여기에 표시됩니다.",explore:"모든 숙소 보기",noHotels:"아직 공개된 검증 숙소가 없습니다",noHotelsSub:"초안 또는 미검증 호텔은 게시 검토를 완료할 때까지 비공개로 유지됩니다.",photoPending:"사진 준비 중",verifiedLabel:"검증됨",demoProperty:"데모 숙소",review:"검증된 후기",reviews:"검증된 후기",checkPrice:"실시간 가격 확인",valueEyebrow:"예약을 중심으로 설계",valueTitle:"검색부터 확정까지 더 적은 고민.",finalTitle:"최종 합계를 먼저",finalBody:"서비스 및 필수 요금은 예약 전 서버가 계산하는 총액에 포함됩니다.",policyTitle:"예약과 함께 보존되는 조건",policyBody:"취소 정책은 예약 시점에 저장되므로 이후 변경이 처음 동의한 조건을 바꾸지 않습니다.",watchTitle:"실제 숙박 가격 추적",watchBody:"같은 호텔과 날짜를 추적하세요. HandMeKey가 실시간 요금, 재고, 프로모션으로 다시 계산합니다.",partnerEyebrow:"호텔 파트너용",partnerTitle:"숙소를 관리하고, 가격을 제어하고, 전환을 확인하세요.",partnerBody:"Partner Hub는 숙소 설정, 예약, 프로모션, 투숙객 메시지와 자체 성과 데이터를 한곳에 모읍니다.",partnerCta:"Partner Hub 보기"},
  search:{destination:"목적지",checkIn:"체크인",checkOut:"체크아웃",adults:"성인",children:"어린이",again:"다시 검색",filter:"숙박 조건 필터",nightly:"1박 총액",min:"최저",max:"최고",stars:"성급",anyStars:"성급 무관",payment:"결제",anyPayment:"모든 결제 방식",payHotel:"호텔 결제",payNow:"지금 결제",sort:"정렬",recommended:"추천",lowPrice:"낮은 가격순",highPrice:"높은 가격순",highStars:"높은 성급순",freeCancel:"현재 무료 취소",facilities:"시설",apply:"필터 적용",live:"실시간 예약 가능",verifiedProperty:"검증된 숙소",verifiedProperties:"검증된 숙소",for:"기간",save:"검색 저장",badTitle:"검색 조건을 확인하세요",invalid:"잘못된 검색",noneTitle:"이 숙박 조건에 맞는 실시간 상품이 없습니다",noneBody:"다른 날짜나 인원, 또는 더 적은 필터를 사용해 보세요. 불완전한 요금과 예약 불가능한 재고는 표시되지 않습니다.",photoPending:"사진 준비 중",verified:"검증됨",demoProperty:"데모 숙소",demoProperties:"데모 숙소",review:"검증된 후기",reviews:"검증된 후기",off:"할인",freeNow:"현재 무료 취소",penalty:"취소 수수료가 발생할 수 있습니다",only:"남은",roomLeft:"객실",roomsLeft:"객실",finalTotal:"숙박 최종 합계",average:"평균 / 1박",seeRooms:"객실 보기"},
  hotel:{back:"{city} 숙소로 돌아가기",verified:"검증된 숙소",demoProperty:"데모 숙소",star:"성급",guestSignal:"투숙객 평가가 매우 좋음",stayReview:"검증된 숙박 후기",stayReviews:"검증된 숙박 후기",checkIn:"체크인",checkOut:"체크아웃",propertyPolicy:"숙소 정책",noPhotos:"숙소 사진이 아직 공개되지 않았습니다.",finalPrice:"예약 전 최종 가격",liveInventory:"실시간 객실 재고",verifiedReviews:"검증된 숙박 후기만 표시",property:"숙소",about:"{hotel} 소개",noDescription:"숙소 설명이 아직 공개되지 않았습니다.",facilities:"시설",noFacilities:"시설 정보가 아직 공개되지 않았습니다.",yourStay:"내 숙박",chooseDates:"날짜를 선택하고 실시간 총액을 확인하세요.",adults:"성인",children:"어린이",availability:"예약 가능 여부 확인",invalidStay:"요청한 숙박 조건이 올바르지 않아 HandMeKey가 다음 기본 날짜를 불러왔습니다.",available:"선택한 날짜에 예약 가능",liveRate:"실시간 요금제",liveRates:"실시간 요금제",night:"박",nights:"박",totalsNote:"최종 합계에는 설정된 서비스 및 필수 요금이 포함됩니다.",from:"최저",stayTotal:"숙박 총액",noRooms:"이 숙박에는 판매 가능한 객실이 없습니다",noRoomsBody:"모든 숙박일에 유효한 가격, 제한 조건과 남은 재고가 있을 때만 요금이 표시됩니다.",room:"객실",upTo:"최대",adult:"성인",adultsPlural:"성인",package:"상품",cancellation:"취소",freeNow:"현재 무료 취소",currentPenalty:"현재 취소 수수료",finalTotal:"숙박 최종 합계",average:"평균 / 1박",base:"기본",service:"서비스",tax:"세금",choose:"이 객실 선택",only:"남은",left:"객실",breakfast:"조식 포함",halfBoard:"하프보드",fullBoard:"풀보드",roomOnly:"객실만",payHotel:"호텔 결제",payNow:"지금 결제",verifiedStays:"검증된 숙박",reviewsTitle:"실제 투숙객이 평가한 내용.",noReviews:"아직 검증된 후기가 없습니다",noReviewsBody:"숙박을 완료한 투숙객만 후기를 작성할 수 있습니다.",outOf10:"10점 만점",verifiedStaysCount:"검증된 숙박",cleanliness:"청결도",staff:"직원",location:"위치",comfort:"편안함",value:"가성비",verifiedStay:"검증된 숙박",propertyResponse:"숙소 답변"},
  checkout:{secure:"안전한 예약",title:"확정 전에 실시간 요금을 확인하세요.",intro:"총액, 결제 방식과 취소 정책은 예약을 생성하는 동일한 예약 엔진에서 제공됩니다.",session:"안전한 계정 세션",terms:"저장된 예약 조건",selectionTitle:"실시간 객실 선택이 필요합니다",selectionBody:"결제 전에 호텔, 객실, 요금제를 선택하세요. HandMeKey는 숨겨진 데모 결제 경로를 사용하지 않습니다.",back:"검색으로 돌아가기",checking:"실시간 요금과 예약 가능 여부 확인 중…",loadFail:"이 숙박을 불러오지 못했습니다",guestInfo:"투숙객 정보",fullName:"이름",email:"이메일",payment:"결제 방법",payHotel:"호텔 결제",payNow:"지금 결제",gatewayMissing:"온라인 결제 게이트웨이가 설정되지 않음",noPayment:"이 요금은 온라인 결제가 필요하지만 현재 배포 환경에 결제 제공업체가 설정되어 있지 않습니다.",reserve:"예약하고 계속",securing:"객실 확보 중…",holdNote:"객실은 서버에서 일시적으로 확보됩니다. 재고를 줄이기 전에 최종 요금을 다시 검증합니다.",yourStay:"내 숙박",roomBase:"객실 기본 요금",service:"서비스 요금",tax:"세금 / 필수 요금",final:"최종 합계",cancellation:"취소",noShow:"노쇼",inventory:"실시간 판매 가능 재고",offIncluded:"기본 요금 할인이 아래 금액에 이미 포함되어 있습니다.",paymentAction:"결제가 시작되었지만 예약 확정 전에 결제 제공업체에서 추가 작업이 필요합니다."},
  login:{eyebrow:"내 숙박을 한곳에서",title:"한 번 예약하고 모든 여행을 간편하게 관리하세요.",intro:"로그인하면 예약을 관리하고 호텔 가격을 추적하며 숙소와의 대화를 해당 숙박에 연결해 보관할 수 있습니다.",verified:"검증된 예약",verifiedSub:"확정된 숙박과 취소 조건을 확인하세요.",alerts:"가격 알림",alertsSub:"숙박 가격을 추적하고 실시간 요금이 내려가면 알림을 받으세요.",messages:"호텔 메시지",messagesSub:"투숙객 요청과 숙소 답변을 예약과 함께 보관하세요.",partner:"호텔을 운영하시나요?",partnerCta:"Partner Hub로 이동"},
  account:{my:"내 계정",overview:"개요",profile:"개인 정보",security:"보안",trips:"내 여행",alerts:"가격 알림",preferences:"환경설정",overviewEyebrow:"여행자 계정",overviewTitle:"숙박과 관련된 모든 것을 한곳에서.",overviewBody:"예약, 가격 추적과 보안 설정은 사용 중인 브라우저가 아니라 로그인한 계정에 연결됩니다.",upcoming:"예정된 여행",activeWatches:"활성 가격 추적",unreadAlerts:"읽지 않은 알림",totalTrips:"계정의 여행",profileCard:"개인 정보",profileCardBody:"새 예약에 자동 입력되는 이름을 최신 상태로 유지하세요.",securityCard:"보안",securityCardBody:"비밀번호를 변경하고 더 이상 신뢰하지 않는 세션을 종료하세요.",tripsCard:"여행",tripsCardBody:"확정, 진행 중, 과거 및 취소된 예약을 확인하세요.",alertsCard:"가격 인텔리전스",alertsCardBody:"저장된 검색, 가격 추적과 앱 내 지속 알림을 관리하세요.",open:"열기",prefTitle:"언어",prefBody:"HandMeKey 고객 페이지의 표시 언어를 선택하세요. 로그인하면 설정이 다른 기기의 계정에도 적용됩니다.",english:"English",arabic:"العربية"},
  profile:{eyebrow:"계정 프로필",title:"개인 정보",body:"향후 예약 자동 입력에 사용하는 정보를 정확하게 유지하세요. 확인된 이메일 변경 기능이 제공될 때까지 로그인 이메일은 보호됩니다.",fullName:"이름",email:"로그인 이메일",protected:"이메일이 보호됩니다.",protectedBody:"HandMeKey는 검증된 이메일 변경 절차가 연결된 후에만 이메일 변경을 허용합니다. 예약 접근에 사용하는 신원을 조용히 바꾸지 않습니다.",smart:"더 빠른 예약.",smartBody:"로그인 상태로 예약하면 계정 이름과 이메일이 자동 입력되지만 각 예약의 투숙객 이름은 변경할 수 있습니다.",saved:"개인 정보를 저장했습니다.",save:"변경사항 저장",saving:"저장 중…"},
  security:{eyebrow:"계정 보호",title:"보안",body:"인증 토큰을 브라우저에 노출하지 않고 비밀번호를 변경하고 활성 서버 세션을 확인하세요.",change:"비밀번호 변경",changeBody:"비밀번호를 변경하면 기존 모든 세션이 종료되고 이 브라우저에 새 세션이 발급됩니다.",currentPassword:"현재 비밀번호",newPassword:"새 비밀번호",hint:"12자 이상을 사용하세요.",update:"비밀번호 업데이트",updating:"업데이트 중…",sessions:"활성 세션",sessionsBody:"HandMeKey는 불투명한 서버 세션을 사용합니다. 세션 토큰을 브라우저에 노출하지 않고 신뢰하지 않는 세션을 종료할 수 있습니다.",checking:"활성 세션 확인 중…",thisBrowser:"이 브라우저",other:"다른 활성 세션",current:"현재",lastActive:"마지막 활동",created:"생성됨",expires:"만료",close:"종료",closing:"종료 중…",none:"활성 세션이 없습니다.",signOutOthers:"다른 세션에서 로그아웃",changed:"비밀번호가 변경되었습니다. 이전 세션은 종료되었고 현재 세션은 안전하게 갱신되었습니다.",closed:"세션이 종료되었습니다.",noOthers:"다른 활성 세션이 없었습니다."},
  trips:{eyebrow:"투숙객 계정",title:"내 여행",bodyPrefix:"연결된 예약",bodySuffix:"게스트 예약은 예약 접근 토큰을 통해서만 계정에 연결할 수 있습니다.",noTrips:"아직 연결된 여행이 없습니다",noTripsBody:"로그인한 상태로 예약하거나 기존 예약을 만든 브라우저에서 열어 이 계정에 연결하세요.",find:"호텔 찾기",current:"현재 숙박",upcoming:"예정된 여행",past:"지난 여행",cancelled:"취소 / 만료",noPhoto:"사진 없음",expected:"예상 도착",openRequest:"열린 요청",openRequests:"열린 요청",noRequests:"열린 요청 없음"},
  alerts:{eyebrow:"계정 인텔리전스",title:"알림 및 추적",body:"저장된 검색과 실시간 가격 추적은 예약 시 표시되는 동일한 요금, 프로모션과 예약 가능 정보를 사용합니다."}
} as const;
