export const zh = {
  language:{label:"语言",english:"English",arabic:"العربية"},
  nav:{stays:"住宿",trips:"我的行程",alerts:"价格提醒",partner:"发布您的住宿",account:"账户",signIn:"登录",signOut:"退出登录",signingOut:"正在退出…"},
  home:{kicker:"酒店价格清晰透明",title:"找到想住的酒店，先看清最终要付多少钱。",intro:"实时房量、已验证酒店、真实住客评价和取消条款，在确认预订前全部清楚显示。",verified:"已验证住宿",cancellation:"已保存的取消条款",total:"住宿最终总价",livePlaceholder:"可预订住宿将在这里显示",livePlaceholderSub:"仅展示已启用、已验证且已发布图片的住宿。",where:"目的地",whereHint:"城市、地区或酒店",checkIn:"入住",checkOut:"退房",guests:"住客",adults:"成人",search:"搜索住宿",liveEyebrow:"HandMeKey 实时房源",liveTitle:"值得查看的已验证住宿。",liveIntro:"住宿通过平台审核并发布实时内容后才会出现在这里。",explore:"查看全部住宿",noHotels:"暂时没有已发布的验证住宿",noHotelsSub:"未完成或未验证的住宿在通过发布审核前不会公开。",photoPending:"图片待上传",verifiedLabel:"已验证",demoProperty:"演示住宿",review:"条验证评价",reviews:"条验证评价",checkPrice:"查看实时价格",valueEyebrow:"围绕预订而设计",valueTitle:"从搜索到确认，少一点猜测。",finalTitle:"先看最终总价",finalBody:"服务费和必须费用会包含在预订前显示的服务器计算总价中。",policyTitle:"条款随预订保存",policyBody:"预订时会保存取消政策快照，之后的修改不会改变您原本接受的条款。",watchTitle:"关注真实住宿价格",watchBody:"跟踪同一酒店和日期，HandMeKey 会按实时价格、房量和促销重新计算。",partnerEyebrow:"酒店合作伙伴",partnerTitle:"管理房源、价格和转化。",partnerBody:"Partner Hub 集成住宿设置、预订、促销、住客消息和第一方经营数据。",partnerCta:"了解 Partner Hub"},
  search:{destination:"目的地",checkIn:"入住",checkOut:"退房",adults:"成人",children:"儿童",again:"重新搜索",filter:"筛选住宿",nightly:"每晚总价",min:"最低",max:"最高",stars:"星级",anyStars:"不限星级",payment:"付款",anyPayment:"不限付款方式",payHotel:"到店付款",payNow:"立即付款",sort:"排序",recommended:"推荐",lowPrice:"价格从低到高",highPrice:"价格从高到低",highStars:"星级从高到低",freeCancel:"当前可免费取消",facilities:"设施",apply:"应用筛选",live:"实时可订",verifiedProperty:"家已验证住宿",verifiedProperties:"家已验证住宿",for:"日期",save:"保存搜索",badTitle:"请检查搜索条件",invalid:"搜索条件无效",noneTitle:"没有符合条件的实时报价",noneBody:"请尝试其他日期、人数或减少筛选。缺失价格或无房的选项不会显示。",photoPending:"图片待上传",verified:"已验证",demoProperty:"演示住宿",demoProperties:"演示住宿",review:"条验证评价",reviews:"条验证评价",off:"优惠",freeNow:"当前可免费取消",penalty:"可能产生取消费用",only:"仅剩",roomLeft:"间房",roomsLeft:"间房",finalTotal:"住宿最终总价",average:"每晚平均",seeRooms:"查看房型"},
  hotel:{back:"返回 {city} 住宿",verified:"已验证住宿",demoProperty:"演示住宿",star:"星",guestSignal:"住客评价优秀",stayReview:"条验证入住评价",stayReviews:"条验证入住评价",checkIn:"入住",checkOut:"退房",propertyPolicy:"住宿政策",noPhotos:"住宿尚未发布图片。",finalPrice:"预订前显示最终价格",liveInventory:"实时房量",verifiedReviews:"仅限真实入住评价",property:"住宿信息",about:"关于 {hotel}",noDescription:"住宿尚未发布介绍。",facilities:"设施",noFacilities:"住宿尚未发布设施信息。",yourStay:"您的住宿",chooseDates:"选择日期并查看实时总价。",adults:"成人",children:"儿童",availability:"查看房量",invalidStay:"所选日期无效，HandMeKey 已加载默认日期。",available:"所选日期可订",liveRate:"个实时价格方案",liveRates:"个实时价格方案",night:"晚",nights:"晚",totalsNote:"最终总价包含已配置的服务费和必须费用。",from:"起价",stayTotal:"住宿总价",noRooms:"所选日期暂无可售房型",noRoomsBody:"只有每晚价格、限制条件和剩余房量都有效时才会显示报价。",room:"房型",upTo:"最多",adult:"成人",adultsPlural:"成人",package:"套餐",cancellation:"取消",freeNow:"当前可免费取消",currentPenalty:"当前取消费用",finalTotal:"最终总价",average:"每晚平均",base:"房费",service:"服务费",tax:"税费",choose:"选择此房型",only:"仅剩",left:"间",breakfast:"含早餐",halfBoard:"半膳",fullBoard:"全膳",roomOnly:"仅住宿",payHotel:"到店付款",payNow:"立即付款",verifiedStays:"真实入住",reviewsTitle:"真实住客评分。",noReviews:"暂无验证评价",noReviewsBody:"只有已完成入住的住客才能发布评价。",outOf10:"满分 10 分",verifiedStaysCount:"次验证入住",cleanliness:"清洁度",staff:"员工",location:"位置",comfort:"舒适度",value:"性价比",verifiedStay:"已验证入住",propertyResponse:"住宿回复"},
  checkout:{secure:"安全预订",title:"确认前再次核对实时价格。",intro:"总价、付款方式和取消政策都来自创建预订的同一实时预订引擎。",session:"安全账户会话",terms:"已保存预订条款",selectionTitle:"需要选择实时房型",selectionBody:"请先选择酒店、房型和价格方案再进入结账。HandMeKey 不会使用隐藏的演示价格。",back:"返回搜索",checking:"正在检查实时价格和房量…",loadFail:"无法加载此住宿",guestInfo:"住客信息",fullName:"姓名",email:"电子邮箱",payment:"付款方式",payHotel:"到店付款",payNow:"立即付款",gatewayMissing:"在线支付网关未配置",noPayment:"此价格要求在线付款，但当前环境未配置支付服务。",reserve:"预留并继续",securing:"正在锁定房间…",holdNote:"房间会通过服务器临时锁定。减少库存前会再次验证最终价格。",yourStay:"您的住宿",roomBase:"房费",service:"服务费",tax:"税费 / 必须费用",final:"最终总价",cancellation:"取消政策",noShow:"未入住",inventory:"实时可售房量",offIncluded:"房费优惠已包含在下方价格中。",paymentAction:"付款已开始，但需要完成支付服务商步骤后才能确认预订。"},
  login:{eyebrow:"您的住宿，一处管理",title:"一次预订，所有行程随时可查。",intro:"登录后可管理预订、关注酒店价格，并让您与住宿的对话始终关联到对应行程。",verified:"已验证预订",verifiedSub:"查看已确认住宿和取消条款。",alerts:"价格提醒",alertsSub:"关注住宿，当实时价格下降时收到通知。",messages:"酒店消息",messagesSub:"将住客请求和住宿回复保留在对应预订中。",partner:"您在经营酒店吗？",partnerCta:"前往 Partner Hub"},
  account:{my:"我的账户",overview:"概览",profile:"个人资料",security:"安全",trips:"我的行程",alerts:"价格提醒",preferences:"偏好设置",overviewEyebrow:"旅行者账户",overviewTitle:"与住宿有关的一切，都在这里。",overviewBody:"预订、价格关注和安全设置都与您的登录账户绑定，而不是某一台浏览器。",upcoming:"即将到来的行程",activeWatches:"正在关注的价格",unreadAlerts:"未读提醒",totalTrips:"账户中的行程",profileCard:"个人资料",profileCardBody:"保持用于自动填写新预订的姓名为最新状态。",securityCard:"安全",securityCardBody:"修改密码并关闭您不再信任的会话。",tripsCard:"行程",tripsCardBody:"查看已确认、进行中、历史和已取消的预订。",alertsCard:"价格追踪",alertsCardBody:"管理已保存搜索、价格关注和应用内持续提醒。",open:"打开",prefTitle:"语言",prefBody:"选择 HandMeKey 客户页面的显示语言。登录后，此偏好会随账户同步到其他设备。",english:"English",arabic:"العربية"},
  profile:{eyebrow:"账户资料",title:"个人资料",body:"保持用于自动填写未来预订的身份信息准确。登录邮箱在支持验证邮箱变更前会保持受保护状态。",fullName:"姓名",email:"登录邮箱",protected:"邮箱受保护。",protectedBody:"只有在接入经过验证的邮箱变更流程后，HandMeKey 才允许修改邮箱。我们不会静默替换用于访问预订的登录身份。",smart:"更快捷的预订。",smartBody:"登录后预订时，账户姓名和登录邮箱会自动填写，但每笔预订仍可单独修改住客姓名。",saved:"个人资料已保存。",save:"保存更改",saving:"正在保存…"},
  security:{eyebrow:"账户保护",title:"安全",body:"无需向浏览器暴露身份验证令牌，即可更改密码并检查活跃的服务器会话。",change:"修改密码",changeBody:"修改密码会关闭现有所有会话，并为当前浏览器创建新的安全会话。",currentPassword:"当前密码",newPassword:"新密码",hint:"请使用至少 12 个字符。",update:"更新密码",updating:"正在更新…",sessions:"活跃会话",sessionsBody:"HandMeKey 使用不透明的服务器会话。您可以关闭不再信任的会话，而无需向浏览器暴露会话令牌。",checking:"正在检查活跃会话…",thisBrowser:"此浏览器",other:"其他活跃会话",current:"当前",lastActive:"最近活动",created:"创建时间",expires:"到期时间",close:"关闭",closing:"正在关闭…",none:"未找到活跃会话。",signOutOthers:"退出其他会话",changed:"密码已更改。旧会话已关闭，当前会话已安全更新。",closed:"会话已关闭。",noOthers:"没有其他活跃会话。"},
  trips:{eyebrow:"住客账户",title:"我的行程",bodyPrefix:"关联至",bodySuffix:"访客预订只能使用对应的预订访问令牌绑定到账户。",noTrips:"暂时没有关联的行程",noTripsBody:"登录后预订，或在创建原预订的浏览器中打开该预订并将其绑定到此账户。",find:"查找酒店",current:"当前住宿",upcoming:"即将到来的行程",past:"历史行程",cancelled:"已取消 / 已过期",noPhoto:"暂无图片",expected:"预计到达",openRequest:"个待处理请求",openRequests:"个待处理请求",noRequests:"没有待处理请求"},
  alerts:{eyebrow:"账户智能",title:"提醒与关注",body:"已保存搜索和实时价格关注使用与预订时相同的价格、促销和可用房量。"}
} as const;
